<?php

/**
 * Common_Model_Base_Country
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ID
 * @property string $Code
 * @property string $Code2
 * @property string $Code3
 * @property Doctrine_Collection $address
 * @property Doctrine_Collection $invoiceComplaints
 * @property Doctrine_Collection $deliveryComplaints
 * @property Doctrine_Collection $countryLangs
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Common_Model_Base_Country extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('common__model__country');
        $this->hasColumn('ID', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('Code', 'string', 8, array(
             'type' => 'string',
             'length' => '8',
             ));
        $this->hasColumn('Code2', 'string', 8, array(
             'type' => 'string',
             'length' => '8',
             ));
        $this->hasColumn('Code3', 'string', 8, array(
             'type' => 'string',
             'length' => '8',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Admin_Model_Address as address', array(
             'local' => 'ID',
             'foreign' => 'Country_ID'));

        $this->hasMany('Admin_Model_Complaint as invoiceComplaints', array(
             'local' => 'ID',
             'foreign' => 'InvoiceCountry_ID'));

        $this->hasMany('Admin_Model_Complaint as deliveryComplaints', array(
             'local' => 'ID',
             'foreign' => 'DeliveryCountry_ID'));

        $this->hasMany('Common_Model_CountryLang as countryLangs', array(
             'local' => 'ID',
             'foreign' => 'Country_ID'));
    }
}