<?php

/**
 * Common_Model_Base_CountryLang
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ID
 * @property integer $Country_ID
 * @property integer $Language_ID
 * @property string $Name
 * @property Common_Model_Country $country
 * @property Common_Model_Language $language
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Common_Model_Base_CountryLang extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('common__model__country_lang');
        $this->hasColumn('ID', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('Country_ID', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('Language_ID', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('Name', 'string', 128, array(
             'type' => 'string',
             'length' => '128',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Common_Model_Country as country', array(
             'local' => 'Country_ID',
             'foreign' => 'ID'));

        $this->hasOne('Common_Model_Language as language', array(
             'local' => 'Language_ID',
             'foreign' => 'ID'));
    }
}