<?php

/**
 * Common_Model_Base_CronUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ID
 * @property integer $Cron_ID
 * @property integer $User_ID
 * @property Common_Model_Cron $cron
 * @property User_Model_User $user
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Common_Model_Base_CronUser extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('common__model__cron_user');
        $this->hasColumn('ID', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('Cron_ID', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('User_ID', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Common_Model_Cron as cron', array(
             'local' => 'Cron_ID',
             'foreign' => 'ID'));

        $this->hasOne('User_Model_User as user', array(
             'local' => 'User_ID',
             'foreign' => 'ID'));
    }
}