<?php

/**
 * Common_Model_Base_CronLog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ID
 * @property integer $Cron_ID
 * @property timestamp $DateTimeStart
 * @property timestamp $DateTimeStop
 * @property string $Status
 * @property string $Message
 * @property Common_Model_Cron $cron
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Common_Model_Base_CronLog extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('common__model__cron_log');
        $this->hasColumn('ID', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('Cron_ID', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('DateTimeStart', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('DateTimeStop', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('Status', 'string', 32, array(
             'type' => 'string',
             'length' => '32',
             ));
        $this->hasColumn('Message', 'string', null, array(
             'type' => 'string',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Common_Model_Cron as cron', array(
             'local' => 'Cron_ID',
             'foreign' => 'ID'));
    }
}