<?php

/**
 * Common_Model_Base_Eshop
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ID
 * @property integer $Currency_ID
 * @property integer $Language_ID
 * @property integer $Settings_ID
 * @property integer $Vat_ID
 * @property integer $FileLogo_ID
 * @property string $Name
 * @property string $URL
 * @property boolean $Active
 * @property Common_Model_Language $language
 * @property Admin_Model_Currency $currency
 * @property Admin_Model_Vat $vat
 * @property Common_Model_Settings $settings
 * @property Common_Model_File $file
 * @property Doctrine_Collection $categoryEshops
 * @property Doctrine_Collection $productEshops
 * @property Doctrine_Collection $questions
 * @property Doctrine_Collection $carts
 * @property Doctrine_Collection $orders
 * @property Doctrine_Collection $shippings
 * @property Doctrine_Collection $payments
 * @property Doctrine_Collection $banners
 * @property Doctrine_Collection $searchLogs
 * @property Doctrine_Collection $emailLogs
 * @property Doctrine_Collection $menuItems
 * @property Doctrine_Collection $popups
 * @property Doctrine_Collection $news
 * @property Doctrine_Collection $pageEshops
 * @property Doctrine_Collection $announcements
 * @property Doctrine_Collection $newsletterSubscribers
 * @property Doctrine_Collection $feedbacks
 * @property Doctrine_Collection $users
 * @property Doctrine_Collection $userEshops
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Common_Model_Base_Eshop extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('common__model__eshop');
        $this->hasColumn('ID', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('Currency_ID', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('Language_ID', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('Settings_ID', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('Vat_ID', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('FileLogo_ID', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('Name', 'string', 64, array(
             'type' => 'string',
             'length' => '64',
             ));
        $this->hasColumn('URL', 'string', 64, array(
             'type' => 'string',
             'length' => '64',
             ));
        $this->hasColumn('Active', 'boolean', null, array(
             'type' => 'boolean',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Common_Model_Language as language', array(
             'local' => 'Language_ID',
             'foreign' => 'ID'));

        $this->hasOne('Admin_Model_Currency as currency', array(
             'local' => 'Currency_ID',
             'foreign' => 'ID'));

        $this->hasOne('Admin_Model_Vat as vat', array(
             'local' => 'Vat_ID',
             'foreign' => 'ID'));

        $this->hasOne('Common_Model_Settings as settings', array(
             'local' => 'Settings_ID',
             'foreign' => 'ID'));

        $this->hasOne('Common_Model_File as file', array(
             'local' => 'FileLogo_ID',
             'foreign' => 'ID'));

        $this->hasMany('Admin_Model_CategoryEshop as categoryEshops', array(
             'local' => 'ID',
             'foreign' => 'Eshop_ID'));

        $this->hasMany('Admin_Model_ProductEshop as productEshops', array(
             'local' => 'ID',
             'foreign' => 'Eshop_ID'));

        $this->hasMany('Admin_Model_Question as questions', array(
             'local' => 'ID',
             'foreign' => 'Eshop_ID'));

        $this->hasMany('Admin_Model_Cart as carts', array(
             'local' => 'ID',
             'foreign' => 'Eshop_ID'));

        $this->hasMany('Admin_Model_Order as orders', array(
             'local' => 'ID',
             'foreign' => 'Eshop_ID'));

        $this->hasMany('Admin_Model_Shipping as shippings', array(
             'local' => 'ID',
             'foreign' => 'Eshop_ID'));

        $this->hasMany('Admin_Model_Payment as payments', array(
             'local' => 'ID',
             'foreign' => 'Eshop_ID'));

        $this->hasMany('Admin_Model_Banner as banners', array(
             'local' => 'ID',
             'foreign' => 'Eshop_ID'));

        $this->hasMany('Admin_Model_SearchLog as searchLogs', array(
             'local' => 'ID',
             'foreign' => 'Eshop_ID'));

        $this->hasMany('Admin_Model_EmailLog as emailLogs', array(
             'local' => 'ID',
             'foreign' => 'Eshop_ID'));

        $this->hasMany('Admin_Model_MenuItem as menuItems', array(
             'local' => 'ID',
             'foreign' => 'Eshop_ID'));

        $this->hasMany('Admin_Model_Popup as popups', array(
             'local' => 'ID',
             'foreign' => 'Eshop_ID'));

        $this->hasMany('Admin_Model_News as news', array(
             'local' => 'ID',
             'foreign' => 'Eshop_ID'));

        $this->hasMany('Admin_Model_PageEshop as pageEshops', array(
             'local' => 'ID',
             'foreign' => 'Eshop_ID'));

        $this->hasMany('Admin_Model_Announcement as announcements', array(
             'local' => 'ID',
             'foreign' => 'Eshop_ID'));

        $this->hasMany('Admin_Model_NewsletterSubscriber as newsletterSubscribers', array(
             'local' => 'ID',
             'foreign' => 'Eshop_ID'));

        $this->hasMany('Admin_Model_Feedback as feedbacks', array(
             'local' => 'ID',
             'foreign' => 'Eshop_ID'));

        $this->hasMany('User_Model_User as users', array(
             'local' => 'ID',
             'foreign' => 'Eshop_ID'));

        $this->hasMany('User_Model_UserEshop as userEshops', array(
             'local' => 'ID',
             'foreign' => 'Eshop_ID'));
    }
}