<?php

/**
 * Common_Model_Base_File
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ID
 * @property blob $Data
 * @property string $Type
 * @property string $Name
 * @property string $Extension
 * @property Doctrine_Collection $productImage
 * @property Doctrine_Collection $categories
 * @property Doctrine_Collection $productDocumments
 * @property Doctrine_Collection $productAttachments
 * @property Doctrine_Collection $categoryAttachments
 * @property Doctrine_Collection $shippings
 * @property Doctrine_Collection $payments
 * @property Doctrine_Collection $banners
 * @property Doctrine_Collection $manufacturer
 * @property Doctrine_Collection $news
 * @property Doctrine_Collection $newsCategory
 * @property Doctrine_Collection $feedbackFiles
 * @property Doctrine_Collection $dayPhotos
 * @property Doctrine_Collection $eshops
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Common_Model_Base_File extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('common__model__file');
        $this->hasColumn('ID', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('Data', 'blob', null, array(
             'type' => 'blob',
             ));
        $this->hasColumn('Type', 'string', 32, array(
             'type' => 'string',
             'length' => '32',
             ));
        $this->hasColumn('Name', 'string', 256, array(
             'type' => 'string',
             'length' => '256',
             ));
        $this->hasColumn('Extension', 'string', 16, array(
             'type' => 'string',
             'length' => '16',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Admin_Model_ProductImage as productImage', array(
             'local' => 'ID',
             'foreign' => 'File_ID'));

        $this->hasMany('Admin_Model_Category as categories', array(
             'local' => 'ID',
             'foreign' => 'File_ID'));

        $this->hasMany('Admin_Model_ProductDocumment as productDocumments', array(
             'local' => 'ID',
             'foreign' => 'File_ID'));

        $this->hasMany('Admin_Model_ProductAttachment as productAttachments', array(
             'local' => 'ID',
             'foreign' => 'File_ID'));

        $this->hasMany('Admin_Model_CategoryAttachment as categoryAttachments', array(
             'local' => 'ID',
             'foreign' => 'File_ID'));

        $this->hasMany('Admin_Model_Shipping as shippings', array(
             'local' => 'ID',
             'foreign' => 'File_ID'));

        $this->hasMany('Admin_Model_Payment as payments', array(
             'local' => 'ID',
             'foreign' => 'File_ID'));

        $this->hasMany('Admin_Model_Banner as banners', array(
             'local' => 'ID',
             'foreign' => 'File_ID'));

        $this->hasMany('Admin_Model_Manufacturer as manufacturer', array(
             'local' => 'ID',
             'foreign' => 'File_ID'));

        $this->hasMany('Admin_Model_News as news', array(
             'local' => 'ID',
             'foreign' => 'File_ID'));

        $this->hasMany('Admin_Model_NewsCategory as newsCategory', array(
             'local' => 'ID',
             'foreign' => 'File_ID'));

        $this->hasMany('Admin_Model_FeedbackFile as feedbackFiles', array(
             'local' => 'ID',
             'foreign' => 'File_ID'));

        $this->hasMany('Admin_Model_DayPhoto as dayPhotos', array(
             'local' => 'ID',
             'foreign' => 'File_ID'));

        $this->hasMany('Common_Model_Eshop as eshops', array(
             'local' => 'ID',
             'foreign' => 'FileLogo_ID'));
    }
}