<?php
createDir('../data/');
createDir('../data/cache/');
createDir('../data/cache/latte/');
createDir('../data/log/');
createDir('../data/log/tracy/');
createDir('../data/log/hadex-api/');
createDir('../data/ppl/');
createDir('../data/ppl/labels');
createDir('files/');
createDir('files/images/');
createDir('files/images/banner/');
createDir('files/images/category-pictogram/');
createDir('files/images/logo/');
createDir('files/images/manufacturer/');
createDir('files/images/product/');
createDir('files/images/product/50/');
createDir('files/images/product/200/');
createDir('files/images/product/350/');
createDir('files/images/product/800/');
createDir('files/images/product/original/');
createDir('files/images/news/');
createDir('files/images/news/50/');
createDir('files/images/news/200/');
createDir('files/images/news/350/');
createDir('files/images/news/800/');
createDir('files/images/news/original/');
createDir('files/images/daily-photos/');
createDir('files/images/daily-photos/50/');
createDir('files/images/daily-photos/200/');
createDir('files/images/daily-photos/350/');
createDir('files/images/daily-photos/800/');
createDir('files/images/daily-photos/original/');
createDir('files/images/category/');
createDir('files/images/category/50/');
createDir('files/images/category/200/');
createDir('files/images/category/350/');
createDir('files/images/category/800/');
createDir('files/images/category/original/');
createDir('files/images/news/');
createDir('files/images/news/50/');
createDir('files/images/news/200/');
createDir('files/images/news/350/');
createDir('files/images/news/800/');
createDir('files/images/news/original/');
createDir('files/orders/');
createDir('files/sitemaps/');
createDir('files/thumbs/');
createDir('files/upload/');
createDir('files/feedback/');
createDir('files/feeds/');
createDir('files/documments/');
createDir('files/documments/product/');
createDir('files/qrcodes/');

function createDir($dir)
{
    if (!file_exists($dir)) {
        mkdir($dir, 0777, true);
    }
}