<?php

/**
 * Admin_Model_ApiLog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Admin_Model_ApiLog extends Admin_Model_Base_ApiLog
{
    /**
     * @throws Exception
     */
    public static function insertRecord(array $data): void {
        $apiLog = new \Admin_Model_ApiLog();
        $apiLog->DateTime = date('Y-m-d H:i:s');
        $apiLog->User = $data['User']?? null;
        $apiLog->StatusCode = $data['StatusCode']?? null;
        $apiLog->Message = $data['Message']?? null;
        $apiLog->Url = $data['Url']?? null;
        $apiLog->save();
    }

    public static function clearApiLog(): void {
        $query = Doctrine_Query::create();
        $query->delete('Admin_Model_ApiLog object');
        $query->where('object.DateTime < ?', date('Y-m-d H:i:s', strtotime('-2 month')));
        $query->execute();
    }


    public function log(int $code, string $message = NULL, array $input = [], array $output = []): void {
        $this->DateTime = date('Y-m-d H:i:s');
        $this->Url = $_SERVER['REQUEST_METHOD']. ' https://'.$_SERVER['HTTP_HOST'].$_SERVER['REQUEST_URI'];
        $this->StatusCode = $code;
        $this->Message = $message;
//        $this->Input = json_encode($input);
//        $this->Output = json_encode($output);
        $this->save();
    }



}