<?php

/**
 * Admin_Model_Block
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Admin_Model_Block extends Admin_Model_Base_Block {


    /**
     * @param string $code
     * @return string|null
     */
    public static function getBlockContent(string $code): ?string{
        $query = Doctrine_Query::create();
        $query->from('Admin_Model_Block object');
        $query->where('object.Code = ?', $code);
        $block = $query->execute()->toArray();

        return $block ? $block[0]['Content'] : '';
    }

    /**
     * @return []
     */
    public static function getBlocks(): array{
        $query = Doctrine_Query::create();
        $query->from('Admin_Model_Block object');
        $blocks = $query->execute()->toArray();

        $result = [];
        foreach ( $blocks as $block ) {
            $result[$block['Code']] = $block['Content'];
        }

        return $result;
    }
}