<?php

/**
 * Admin_Model_CartLog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Admin_Model_CartLog extends Admin_Model_Base_CartLog {

    /**
     * @param Doctrine_Connection|null $conn
     */
    public function save(Doctrine_Connection $conn = null) {
        if ($this->ID == null) {
            $this->Date = date('Y-m-d');
            $this->Time = date('H:i:s');
        }

        parent::save($conn);
    }

    /**
     * @param int $productID
     * @param int|null $userID
     * @param int $quantity
     */
    public static function creteCartLog(int $productID, ?int $userID, int $quantity) {
        $cartLog = new Admin_Model_CartLog();
        $cartLog->Product_ID = $productID;
        $cartLog->User_ID = $userID;
        $cartLog->Quantity = $quantity;
        $cartLog->IPAddress = $_SERVER['REMOTE_ADDR'];
        $cartLog->save();
    }

}