<?php
use Admin_Model_CategoryEshop as CategoryEshop;
use common\logic\Configs;
use common\logic\Eshop\Eshop;
use Common_Model_Eshop as ModelEshop;

/**
 * Admin_Model_Category
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Admin_Model_Category extends Admin_Model_Base_Category {

    const CATEGORY_SALE = 9835;
    const MENU_CATEGORIES_ID = [1, 2, 3, 4];



    /**
     * @param Doctrine_Connection|null $conn
     */
    public function save(Doctrine_Connection $conn = null) {
        $isNew = $this->ID == null;

        $this->DateTimeUpdated = date('Y-m-d H:i:s');

        parent::save($conn);

        if ( $isNew ) {
            $this->DateTimeCreated = date('Y-m-d H:i:s');
            foreach (ModelEshop::getEshops() as $eshop) {
                $categoryEshop = new CategoryEshop();
                $categoryEshop->Eshop_ID = $eshop->ID;
                $categoryEshop->Category_ID = $this->ID;
                $categoryEshop->Active = true;
                $categoryEshop->save();
            }
        }
    }

    /**
     * Vrací produkty pro sitemapy
     * @param ModelEshop|null $eshop
     * @return array
     */
    public static function loadCategoriesSitemap(?ModelEshop $eshop = null) :array {
        if ( !$eshop )
            $eshop = Eshop::getInstance()->getEshop();

        $query = Doctrine_Query::create();
        $query->from('Admin_Model_Category object');
        $query->select('categoryLangs.slug, object.ID, subCategories.ID, subCategoryLangs.slug');
        $query->innerJoin('object.categoryEshops categoryEshops WITH categoryEshops.Eshop_ID = ? AND categoryEshops.Active = ?', [$eshop->ID, true]);
        $query->innerJoin('object.categoryLangs categoryLangs WITH categoryLangs.Language_ID = ?', [$eshop->Language_ID]);

        $query->leftJoin('object.categories subCategories WITH subCategories.Category_ID = object.ID');
        $query->innerJoin('subCategories.categoryEshops subCategoryEshops WITH subCategoryEshops.Eshop_ID = ? AND subCategoryEshops.Active = ?', [$eshop->ID, true]);
        $query->innerJoin('subCategories.categoryLangs subCategoryLangs WITH subCategoryLangs.Language_ID = ?', [$eshop->Language_ID]);

        return $query->execute()->toArray();
    }

    /**
     * @param string $slug
     * @param Eshop|null $eshop
     * @return array
     */
    public static function getCategoryBySlug(string $slug, Eshop $eshop = null): array {
        if ( !$eshop )
            $eshop = Eshop::getInstance()->getEshop();

        $query = Doctrine_Query::create();
        $query->from('Admin_Model_Category object');
        $query->select('object.*, file.*, categoryLangs.*, categoryEshops.*, categories.*, subCategoryLangs.*');
        $query->addSelect('categoryLangs.Name as Name, categoryLangs.Description as Description, categoryLangs.ShortDescription as ShortDescription, categoryLangs.slug as slug');
        $query->addSelect('categoryLangs.H1Name as H1Name, categoryLangs.Title as Title, categoryLangs.MetaDescription as MetaDescription');
        $query->addSelect('categoryEshops.Active as Active');
        $query->leftJoin('object.file file');
        $query->leftJoin('object.categoryLangs categoryLangs WITH categoryLangs.Language_ID = ?', $eshop->Language_ID);
        $query->leftJoin('object.categoryEshops categoryEshops WITH categoryEshops.Eshop_ID = ?', $eshop->ID);
        $query->where('categoryLangs.slug = ?', $slug);
        $query->andWhere('categoryEshops.Active = ?', true);
        $query->leftJoin('object.categories categories');
        $query->leftJoin('categories.categoryLangs subCategoryLangs WITH subCategoryLangs.Language_ID = ?', $eshop->Language_ID);
        $category = $query->execute()->toArray();

        return $category ? $category[0] : [];
    }

    /**
     * @param int $ID
     * @param Eshop|null $eshop
     * @return array
     */
    public static function getCategoryByID(int $ID, Eshop $eshop = null): array {
        if ( !$eshop )
            $eshop = Eshop::getInstance()->getEshop();

        $query = Doctrine_Query::create();
        $query->from('Admin_Model_Category object');
        $query->select('object.*, file.*, categoryLangs.*, categoryLangs.Name as Name, categoryLangs.slug as slug');
        $query->leftJoin('object.categoryLangs categoryLangs WITH categoryLangs.Language_ID = ?', $eshop->Language_ID);
        $query->leftJoin('object.categoryEshops categoryEshops WITH categoryEshops.Eshop_ID = ?', $eshop->ID);
        $query->leftJoin('object.file file');
        $query->where('object.ID = ?', $ID);

        return $query->execute()->toArray();
    }

    /**
     * @param Eshop|null $eshop
     * @return array
     */
    public static function getMainMenuCategories(Eshop $eshop = null): array {
        if (!$eshop)
            $eshop = Eshop::getInstance()->getEshop();

        $query = Doctrine_Query::create();
        $query->from('Admin_Model_Category object');
        $query->select('object.*, object.Category_ID as Parent_ID, file.*, categoryLangs.Name as Name, categoryLangs.Rank as Rank, categoryLangs.slug as slug');
        $query->leftJoin('object.file file');
        $query->leftJoin('object.categoryLangs categoryLangs WITH categoryLangs.Language_ID = ?', $eshop->Language_ID);
        $query->leftJoin('object.categoryEshops categoryEshops WITH categoryEshops.Eshop_ID = ? AND categoryEshops.Active = ?', [$eshop->ID, true]);
        $query->andWhere('categoryEshops.Active = ?', true);
        $query->addOrderBy('categoryEshops.Rank ASC');

        $allCategories = $query->execute([], Doctrine_Core::HYDRATE_ARRAY);

        $categoriesById = [];
        foreach ($allCategories as $category) {
            $category['categories'] = [];
            $categoriesById[$category['ID']] = $category;
        }

        $rootCategories = [];

        foreach ($allCategories as $category) {
            $parentId = $category['Parent_ID'];

            if ($parentId === null) {
                // Kořenová kategorie
                $rootCategories[] = &$categoriesById[$category['ID']];
            } else {
                if (isset($categoriesById[$parentId])) {
                    $categoriesById[$parentId]['categories'][] = &$categoriesById[$category['ID']];
                }
            }
        }

        self::sortCategoriesByRank($rootCategories);

        return $rootCategories;

    }

    public static function sortCategoriesByRank(array &$categories) {
        usort($categories, function ($a, $b) {
            return ($a['Rank'] ?? 0) <=> ($b['Rank'] ?? 0);
        });

        foreach ($categories as &$category) {
            if (!empty($category['categories'])) {
                self::sortCategoriesByRank($category['categories']);
            }
        }
    }

    /**
     * @param Eshop|null $eshop
     * @param int|null $categoryID
     * @return array
     */
    public static function getMainMenuSubCategory(Eshop $eshop = null, int $categoryID = null): array {
        if ( !$eshop )
            $eshop = Eshop::getInstance()->getEshop();

        $query = Doctrine_Query::create();
        $query->from('Admin_Model_Category object');
        $query->select('object.*, categoryLangs.Name as Name, file.*, categoryLangs.Description as Description, categoryLangs.ShortDescription as ShortDescription, categoryLangs.slug as slug');
        $query->addSelect('categories.*, subCategoryLangs.*, subCategoryEshops.*');
        $query->addSelect('subCategories.*, subSubCategoryLangs.*, subSubCategoryEshops.*');

        $query->leftJoin('object.categoryEshops categoryEshops WITH categoryEshops.Eshop_ID = ? AND categoryEshops.Active = ?', [$eshop->ID, true]);
        $query->leftJoin('object.categoryLangs categoryLangs WITH categoryLangs.Language_ID = ?', $eshop->Language_ID);
        $query->leftJoin('object.file file');

        $query->leftJoin('object.categories categories');
        $query->leftJoin('categories.categoryEshops subCategoryEshops WITH subCategoryEshops.Eshop_ID = ?', [$eshop->ID]);
        $query->leftJoin('categories.categoryLangs subCategoryLangs WITH subCategoryLangs.Language_ID = ?', [$eshop->Language_ID]);

        $query->where('object.Category_ID = ?', $categoryID);
        $query->andWhere('categoryEshops.Active = ?', true);
        $query->addOrderBy('categoryEshops.Rank ASC');

        return $query->execute([], Doctrine_Core::HYDRATE_ARRAY);
    }

    /**
     * @param string $searchTerm
     * @param int|null $limit
     * @param Eshop|null $eshop
     * @return array
     */
    public static function getSearchCategories(string $searchTerm, int $limit = null, Eshop $eshop = null): array {
        if ( !$eshop )
            $eshop = Eshop::getInstance()->getEshop();

        $query = Doctrine_Query::create();
        $query->from('Admin_Model_Category object');
        $query->select('object.*, file.*, categoryLangs.Name as Name, categoryLangs.Description as Description, categoryLangs.ShortDescription as ShortDescription, categoryLangs.slug as slug');
        $query->leftJoin('object.categoryLangs categoryLangs WITH categoryLangs.Language_ID = ?', $eshop->Language_ID);
        $query->leftJoin('object.categoryEshops categoryEshops WITH categoryEshops.Eshop_ID = ?', $eshop->ID);
        $query->leftJoin('object.file file');
        $query->andWhere('categoryLangs.Name LIKE ?', '%' . $searchTerm . '%');
        $query->andWhere('categoryEshops.Active = ?', true);

        if ( $limit != null )
            $query->limit($limit);

        return $query->execute()->toArray();
    }

    /**
     * @param string $searchTerm
     * @param Eshop|null $eshop
     * @return int
     */
    public static function getSearchCategoriesCount(string $searchTerm, Eshop $eshop = null): int {
        if ( !$eshop )
            $eshop = Eshop::getInstance()->getEshop();

        $query = Doctrine_Query::create();
        $query->from('Admin_Model_Category object');
        $query->andWhere('categoryLangs.Name LIKE ?', '%' . $searchTerm . '%');
        $query->leftJoin('object.categoryEshops categoryEshops WITH categoryEshops.Eshop_ID = ?', $eshop->ID);
        $query->leftJoin('object.categoryLangs categoryLangs WITH categoryLangs.Language_ID = ?', $eshop->Language_ID);
        $query->andWhere('categoryEshops.Active = ?', true);

        return $query->count();
    }

    /**
     * @param int $parentCategoryID
     * @return array|Doctrine_Collection|Doctrine_Collection_OnDemand|int
     */
    public static function getSubCategories(int $parentCategoryID) {
        $eshop = Eshop::getInstance()->getEshop();

        $query = \Doctrine_Query::create();
        $query->from('Admin_Model_Category object');
        $query->leftJoin('object.categoryLangs categoryLangs WITH categoryLangs.Language_ID = ?', $eshop->Language_ID);
        $query->leftJoin('object.categoryEshops categoryEshops WITH categoryEshops.Eshop_ID = ?', $eshop->ID);
        $query->leftJoin('object.file file');
        $query->where('object.Category_ID = ?', $parentCategoryID);
        $query->andWhere('categoryEshops.Active = ?', 1);

        return $query->execute([], \Doctrine_Core::HYDRATE_ARRAY);
    }

    /**
     * @return array
     */
    public static function formatCategoryTree(): array {
        $query = Doctrine_Query::create();
        $query->select('object.ID, object.Category_ID, categoryLangs.Name as Name');
        $query->from('Admin_Model_Category object');
        $query->leftJoin('object.categoryLangs categoryLangs WITH Language_ID = 1');
        $resultArray = $query->execute()->toArray();

        $result = array();
        foreach ($resultArray as $item) {
            $itemItem = array();
            $itemItem['id'] = $item['ID'];
            $itemItem['Category_ID'] = $item['Category_ID'];
            $itemItem['text'] = $item['Name'];
            $result[] = $itemItem;
        }

        $dangling = array();
        $output = array();

        foreach ($result as $entry) {
            $entry['children'] = array();
            $id = $entry['id'];

            if ($entry['Category_ID'] == '') {
                $all[$id] = $entry;
                $output[] = & $all[$id];
            } else {
                $dangling[$id] = $entry;
            }
        }

        while (count($dangling) > 0) {
            foreach ($dangling as $entry) {
                $id = $entry['id'];
                $pid = $entry['Category_ID'];

                if (isset($all[$pid])) {
                    $all[$id] = $entry;
                    $all[$pid]['children'][] = & $all[$id];
                    unset($dangling[$entry['id']]);
                }
            }
        }

        return $output;
    }

    public static function getCategoryByCode(string $categoryCode) {
        $query = Doctrine_Query::create();
        $query->from('Admin_Model_Category object');
        $query->select('object.*, categoryLangs.Name as Name');
        $query->leftJoin('object.categoryLangs categoryLangs WITH categoryLangs.Language_ID = 1');
        $query->where('object.Code = ?', $categoryCode);

        return $query->fetchOne();
    }

    public static function getCategoryByIdOrCode(?int $categoryID = null, ?string $categoryCode = null):self {
        $query = Doctrine_Query::create();
        $query->from('Admin_Model_Category object');
        $query->select('object.*, categoryLangs.Name as Name');
        $query->leftJoin('object.categoryLangs categoryLangs WITH categoryLangs.Language_ID = 1');
        if($categoryID)
            $query->where('object.ID = ?', $categoryID);
        else
            $query->where('object.Code = ?', $categoryCode);
        return $query->fetchOne();
    }

    public static function getCategories($id = null, $filter = null, $changedSince =null): Doctrine_Collection {
        $query = Doctrine_Query::create();
        $query->from('Admin_Model_Category object');
        $query->select('object.*, categoryLangs.Name as Name');
        $query->leftJoin('object.categoryLangs categoryLangs WITH categoryLangs.Language_ID = 1');
        $query->where('object.Archived IS NOT TRUE');

        if ($id) {
            $query->where('object.ID = ?', $id);
        }

        //ToDo filter jak má fungovat?
        if ($filter) {
            $query->where('object.Code = ?', $filter);
        }

        if ($changedSince) {
            $query->andWhere('object.DateTimeUpdated > ?', $changedSince);
        }

        return $query->execute();

    }

    public static function getCategoryObjByID(int $ID):self|bool {
        $query = Doctrine_Query::create();
        $query->from('Admin_Model_Category object');
        $query->select('object.*, categoryLangs.Name as Name');
        $query->leftJoin('object.categoryLangs categoryLangs WITH categoryLangs.Language_ID = 1');
        $query->where('object.ID = ?', $ID);

        return $query->fetchOne();
    }

    public static function getCategoryByOldHistorySlug(string $slug) {
        $query = Doctrine_Query::create();
        $query->from('Admin_Model_CategorySlugHistory object');
        $query->addSelect('object.Category_ID, categoryLangs.slug as slug');
        $query->leftJoin('object.category category');
        $query->leftJoin('category.categoryLangs categoryLangs WITH categoryLangs.Language_ID = ?', Eshop::getInstance()->getEshop()->Language_ID);
        $query->where('object.Slug = ?', $slug);
        $query->limit(1);
        $result = $query->execute([], Doctrine_Core::HYDRATE_ARRAY);
        if($result) {
            return $result[0];
        } else {
            return null;
        }

    }


}