<?php

/**
 * Admin_Model_ComplaintItem
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Admin_Model_ComplaintItem extends Admin_Model_Base_ComplaintItem
{

    public static function createItem(int $complatinId,?array $itemData): self {
        $complaintItem = new Admin_Model_ComplaintItem();

        $complaintItem->Complaint_ID = $complatinId;
        $complaintItem->InvoiceNumber = $itemData['InvoiceNumber'];
        $complaintItem->ProductNumber = $itemData['ProductCode'];
        $complaintItem->Amount = $itemData['Quantity'];
        $complaintItem->Description = $itemData['DefectDescription'];

        $complaintItem->save();

        return $complaintItem;
    }

}