<?php

/**
 * Admin_Model_CsobPayment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Admin_Model_CsobPayment extends Admin_Model_Base_CsobPayment
{

    /**
     * @param Doctrine_Connection|null $conn
     */
    public function save(Doctrine_Connection $conn = null) {
        if ($this->ID == null) {
            $this->Date = date('Y-m-d');
            $this->Time = date('H:i:s');
        }

        parent::save($conn);
    }

    /**
     * @param int $orderID
     * @param int $csobID
     * @param string $csobURL
     * @return Admin_Model_CsobPayment
     */
    public static function createCsobPayment(int $orderID, string $csobID, string $csobURL): self {
        $csobPayment = new self();
        $csobPayment->Order_ID = $orderID;
        $csobPayment->CsobID = $csobID;
        $csobPayment->CsobURL = $csobURL;
        $csobPayment->save();

        return $csobPayment;
    }

    /**
     * @param int $csobID
     * @return array
     */
    public static function getPaymentByCsobID(string $csobID): array {
        $query = Doctrine_Query::create();
        $query->from('Admin_Model_CsobPayment object');
        $query->where('object.CsobID = ?', $csobID);

        return $query->execute()->toArray();
    }
}