<?php

/**
 * Admin_Model_Currency
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Admin_Model_Currency extends Admin_Model_Base_Currency {

    const CURRENCY_CZK_ID = 1;
    const CURRENCY_EUR_ID = 2;

    /**
     * @param int $currencyID
     * @return float|null
     */
    public static function getCurrencyRatioByID(int $currencyID): ?float {
        $query = Doctrine_Query::create();
        $query->from('Admin_Model_Currency object');
        $query->where('object.ID = ?', $currencyID);
        $currency = $query->fetchOne();

        return $currency?->Ratio;
    }

    public static function getCurrencyByMark(string $currencyMark)
    {
        $query = Doctrine_Query::create();
        $query->from('Admin_Model_Currency object');
        $query->where('object.Mark = ?', $currencyMark);
        return $query->fetchOne();
    }

    public static function getCurrentCurrency() {
        return self::getCurrencyByMark(self::getCurrency()['currencyMark']);
    }

    public static function getCurrencyByID(mixed $currencyID)
    {
        $query = Doctrine_Query::create();
        $query->from('Admin_Model_Currency object');
        $query->where('object.ID = ?', $currencyID);
        return $query->fetchOne();
    }

    private static function getCurrency(): array
    {
        return [
            'currencyName' => htmlentities(strip_tags($_COOKIE['currencyName'] ?? 'Česká koruna')),
            'currencyMark' => htmlentities(strip_tags($_COOKIE['currencyMark'] ?? 'CZK'))
        ];
    }


}