<?php

/**
 * Admin_Model_DayPhoto
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Admin_Model_DayPhoto extends Admin_Model_Base_DayPhoto
{

    public static function saveDayPhoto($userId, $day, $fileId) {
        $dayPhoto = new Admin_Model_DayPhoto();
        $dayPhoto->User_ID = $userId;
        $dayPhoto->Day_ID = $day;
        $dayPhoto->File_ID = $fileId;

        $dayPhoto->save();

    }

    public static function getPhoto($userId, $day) {
        $query = Doctrine_Query::create();
        $query->from('Admin_Model_DayPhoto object');
        $query->where('object.User_ID = ?', $userId);
        $query->andWhere('object.Day_ID = ?', $day);
        $result = $query->fetchOne();

        return $result;
    }

}