<?php

/**
 * Admin_Model_EmailLog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Admin_Model_EmailLog extends Admin_Model_Base_EmailLog {

    /**
     * @param Doctrine_Connection|null $conn
     */
    public function save(Doctrine_Connection $conn = null) {
        if ($this->ID == null) {
            $this->Date = date('Y-m-d');
            $this->Time = date('H:i:s');            
        }
            
        parent::save($conn);
    }

    /**
     * @param string $body
     * @param string $subject
     * @param string $from
     * @param string $to
     */
    public static function createLog(string $body, string $subject, string $from, string $to) {
        $emailLog = new Admin_Model_EmailLog();
        $emailLog->Body = $body;
        $emailLog->Subject = $subject;
        $emailLog->Sender = $from;
        $emailLog->Recipients = $to;
        $emailLog->save();        
    }
}