<?php

/**
 * Admin_Model_FeedbackFile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Admin_Model_FeedbackFile extends Admin_Model_Base_FeedbackFile
{
    public function preDelete($event)
    {
        $file = $this->file;

        $query = Doctrine_Query::create();
        $query->update('Admin_Model_FeedbackFile object');
        $query->where('object.ID = ?', $this->ID);
        $query->set('object.File_ID', 'NULL');
        $query->execute();

        $file->delete();

        parent::preDelete($event);
    }
}