<?php
use user\logic\UserAdminSession;

/**
 * Admin_Model_FeedbackReadLastState
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Admin_Model_FeedbackReadLastState extends Admin_Model_Base_FeedbackReadLastState {

    /**
     * Označí Feedback jako přečtený
     * @param int $feedback_ID
     * @param int|null $user_ID
     * @return static
     * @throws Exception
     */
    public static function addReaded(int $feedback_ID, ?int $user_ID): self {
        if ( !$user_ID )
            $user_ID = UserAdminSession::getCurrentUserID();

        $readState = new self();
        $readState->User_ID = $user_ID;
        $readState->Feedback_ID = $feedback_ID;
        $readState->save();

        return $readState;
    }

    /**
     * Odstraní zobrazený stav u feedbacku
     * @param $feedback_ID
     * @param $user_ID
     * @throws Doctrine_Query_Exception
     */
    public static function resetRead($feedback_ID, $user_ID = null) {
        $query = Doctrine_Query::create();
        $query->delete('Admin_Model_FeedbackReadLastState object');
        $query->where('object.Feedback_ID = ?', $feedback_ID);
        if ($user_ID)
            $query->addWhere('object.User_ID = ?', $user_ID);

        $query->execute();
    }
}