<?php

use common\logic\Configs;
use common\logic\Eshop\Eshop;

/**
 * Admin_Model_Manufacturer
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Admin_Model_Manufacturer extends Admin_Model_Base_Manufacturer {

    /**
     * @param Doctrine_Connection|null $conn
     * @throws Exception
     */
    public function save(Doctrine_Connection $conn = null) {
        $isNew = $this->ID == null;

        parent::save($conn);

    }

    /**
     * @return array
     */
    public static function getManufacturersForHomepage(): array {
        $query = Doctrine_Query::create();
        $query->from('Admin_Model_Manufacturer object');
        $query->leftJoin('object.manufacturerFile manufacturerFile');
        $query->limit(6);

        return $query->execute()->toArray();
    }

    public static function getManufacturerBySlug(string $slug) {
        $query = Doctrine_Query::create();
        $query->from('Admin_Model_Manufacturer object');
        $query->leftJoin('object.manufacturerFile manufacturerFile');
        $query->where('object.slug=?', $slug);

        return $query->execute()->toArray();
    }

    /**
     * @return array
     */
    public static function getManufacturers() :array  {
        $query = Doctrine_Query::create();
        $query->from('Admin_Model_Manufacturer object');
        $query->leftJoin('object.manufacturerFile manufacturerFile');
        $results = $query->execute()->toArray();

//        if($slugify) {
//            foreach($results as $key=>$value) {
//                $results[$key]['slug'] = self::slugify($value['Name']);
//            }
//        }

        return $results;
    }

    /**
     * @return array
     */
    public static function formatManufacturerTree(): array {
        $query = Doctrine_Query::create();
        $query->select('object.ID, object.Name as Name');
        $query->from('Admin_Model_Manufacturer object');
        $resultArray = $query->execute()->toArray();

        $result = array();
        foreach ($resultArray as $item) {
            $itemItem = array();
            $itemItem['id'] = $item['ID'];
            $itemItem['text'] = $item['Name'];
            $result[] = $itemItem;
        }

        return $result;
    }


    private static function slugify($text, string $divider = '-')
    {
        // replace non letter or digits by divider
        $text = preg_replace('~[^\pL\d]+~u', $divider, $text);

        // remove unwanted characters
        $text = preg_replace('~[^-\w]+~', '', $text);

        // trim
        $text = trim($text, $divider);

        // remove duplicate divider
        $text = preg_replace('~-+~', $divider, $text);

        // lowercase
        $text = strtolower($text);

        if (empty($text)) {
            return 'n-a';
        }

        return $text;
    }
}