<?php
use common\logic\Eshop\Eshop;
/**
 * Admin_Model_MenuItem
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Admin_Model_MenuItem extends Admin_Model_Base_MenuItem {

    /**
     * @param int $menuID
     * @param Eshop|null $eshop
     * @return array
     */
    public static function getMenuItems(int $menuID, Eshop $eshop = null): array {
        if ( !$eshop )
            $eshop = Eshop::getInstance()->getEshop();

        $query = Doctrine_Query::create();
        $query->from('Admin_Model_MenuItem object');
        $query->where('object.Menu_ID = ?', $menuID);
        $query->andWhere('object.Active = ?', true);
        $query->andWhere('object.Eshop_ID = ?', $eshop->ID);
        $query->orderBy('object.Rank ASC');

        return $query->execute()->toArray();
    }
}