<?php

/**
 * Admin_Model_Menu
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Admin_Model_Menu extends Admin_Model_Base_Menu {

    const ID_HEADER_MENU = 1;
    const ID_FOOTER_MENU_1 = 2;
    const ID_FOOTER_MENU_2 = 3;
    const ID_FOOTER_MENU_3 = 4;
    const TYPE_HEADER_MENU = 'header-menu';
    const TYPE_FOOTER_MENU_1 = 'footer-menu-1';
    const TYPE_FOOTER_MENU_2 = 'footer-menu-2';
}