<?php
use common\logic\Eshop\Eshop;

/**
 * Admin_Model_News
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Admin_Model_News extends Admin_Model_Base_News {

    public function save(Doctrine_Connection $conn = null)
    {
        if (array_key_exists('Content', $this->getModified()))
            $this->Content = self::prepareContent($this->Content);
            $this->Active = 1;

        parent::save($conn);
    }

    /**
     * @param string $slug
     * @param Eshop|null $eshop
     * @return Admin_Model_News|null
     */
    public static function getNewsBySlug(string $slug, Eshop $eshop = null): ?Admin_Model_News {
        if ( !$eshop )
            $eshop = Eshop::getInstance()->getEshop();

        $query = Doctrine_Query::create();
        $query->from('Admin_Model_News object');
        $query->leftJoin('object.newsCategory newsCategory');
        $query->leftJoin('newsCategory.newsCategoryLangs newsCategoryLangs');
        $query->where('object.slug = ?', $slug);
        $query->andWhere('object.Eshop_ID = ?', $eshop->ID);
        $news = $query->fetchOne();

        return $news ?: null;
    }

    /**
     * @param array|null $category
     * @return array
     */
    public static function getActiveNews($category = null): array {
        $eshop = Eshop::getInstance()->getEshop();

        $query = Doctrine_Query::create();
        $query->from("Admin_Model_News object");
        $query->leftJoin("object.file file");
        $query->leftJoin("object.newsCategory newsCategory");
        $query->leftJoin("newsCategory.newsCategoryLangs newsCategoryLangs");
        $query->andWhere('object.Active = ?', true);
        $query->andWhere('object.Eshop_ID = ?', $eshop->ID);
        if ( $category )
            $query->andWhere('object.NewsCategory_ID = ?', $category['ID']);
        $query->orderBy('object.Date DESC');

        return $query->execute()->toArray();
    }

    /**
     * @param self $news
     * @return array
     */
    public static function getRelatedNews(self $news): array {
        $eshop = Eshop::getInstance()->getEshop();

        $query = Doctrine_Query::create();
        $query->from("Admin_Model_News object");
        $query->leftJoin("object.file file");
        $query->leftJoin("object.newsCategory newsCategory");
        $query->leftJoin("newsCategory.newsCategoryLangs newsCategoryLangs");
        $query->andWhere('object.Active = ?', true);
        $query->andWhere('object.Eshop_ID = ?', $eshop->ID);
        $query->andWhere('object.NewsCategory_ID = ?', $news->NewsCategory_ID);
        $query->andWhere('object.ID != ?', $news->ID);
        $query->limit(3);
        $query->orderBy('object.Date DESC');

        return $query->execute()->toArray();
    }

    /**
     * @param Eshop|null $eshop
     * @return array
     */
    public static function getNewsOnHomepage(Eshop $eshop = null): array {
        if ( !$eshop )
            $eshop = Eshop::getInstance()->getEshop();

        $query = Doctrine_Query::create();
        $query->from("Admin_Model_News object");
        $query->leftJoin("object.file file");
        $query->andWhere('object.Active = ?', true);
        $query->andWhere('object.Eshop_ID = ?', $eshop->ID);
        $query->limit(2);
        $query->orderBy('object.Date DESC');

        return $query->execute()->toArray();
    }

    public static function getLatestNews() {
        $eshop = Eshop::getInstance()->getEshop();
        $query = Doctrine_Query::create();
        $query->from("Admin_Model_News object");
        $query->leftJoin("object.file file");
        $query->leftJoin("object.newsCategory newsCategory");
        $query->leftJoin("newsCategory.newsCategoryLangs newsCategoryLangs");
        $query->andWhere('object.Active = ?', true);
        $query->andWhere('object.Eshop_ID = ?', $eshop->ID);
        $query->limit(12);
        $query->orderBy('object.Date DESC');

        return $query->execute()->toArray();
    }

    public static function getNewsForCategory(string $categoryIDs, int $currentPage = null, int $offset = null ): array
    {
        $query = Doctrine_Query::create();
        $query->from('Admin_Model_News object');
        $query->addSelect('object.*, file.*');
        $query->addSelect('newsCategory.*');
        $query->leftJoin('object.file file');
        $query->leftJoin('object.newsCategory newsCategory');
        $query->whereIn('object.newsCategory_ID', explode(',', $categoryIDs));

        if ($offset) {
            $query->limit($offset);
            $query->offset(($currentPage - 1) * $offset);
        }

        return $query->execute()->toArray();
    }

    public static function getTotalNewsForCategory($categoryIDs): int
    {
        $query = Doctrine_Query::create();
        $query->from('Admin_Model_News object');
        $query->addSelect('object.*, file.*');
        $query->whereIn('object.newsCategory_ID', explode(',', $categoryIDs));

        return $query->count();
    }

    /**
     * @return string
     */
    private static function prepareContent($content): string
    {
        preg_match_all('/<img[^>]+>/i', $content, $images);
        foreach ($images[0] as $image) {
            preg_match_all('/src="([^"]+)"/', $image, $imageSrc);
            $fileName = 'files/upload/' . uniqid() . '.jpg';

            $imageSrc = $imageSrc[0][0];
            if (base64_to_jpeg($imageSrc, $fileName))
                $content = str_replace($imageSrc, 'src="' . Common_Model_Eshop::getFirstEshop()->URL . '/' . $fileName . '"', $content);
        }

        return html_entity_decode($content, ENT_HTML5 | ENT_NOQUOTES);
    }
}