<?php
use common\logic\Eshop\Eshop;

/**
 * Admin_Model_NewsletterSubscriber
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Admin_Model_NewsletterSubscriber extends Admin_Model_Base_NewsletterSubscriber {

    /**
     * @param string $subscriber
     * @return int
     */
    public static function isAllreadySubscribed(string $subscriber): int {
        $query = Doctrine_Query::create();
        $query->from('Admin_Model_NewsletterSubscriber object');
        $query->where('object.Subscriber = ?', $subscriber);
        $query->andWhere('object.Active = 1');

        return $query->count() == 1 ? 1 : 0;
    }

    /**
     * @param string $subscriber
     * @param Eshop|null $eshop
     */
    public static function createSubscriber(string $subscriber, Eshop $eshop = null) {
        if ( !$eshop )
            $eshop = Eshop::getInstance()->getEshop();

        $query = Doctrine_Query::create();
        $query->from('Admin_Model_NewsletterSubscriber object');
        $query->where('object.Subscriber = ?', $subscriber);
        $query->andWhere('object.Eshop_ID = ?', $eshop->ID);
        $newsletterSubscriber = $query->fetchOne();

        if ( !$newsletterSubscriber )
            $newsletterSubscriber = new Admin_Model_NewsletterSubscriber();

        $newsletterSubscriber->Subscriber = $subscriber;
        $newsletterSubscriber->Date = date('Y-m-d');
        $newsletterSubscriber->Time = date('H:i:s');
        $newsletterSubscriber->Active = true;
        $newsletterSubscriber->save();
    }
}