<?php

/**
 * Admin_Model_ParameterValue
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Admin_Model_ParameterValue extends Admin_Model_Base_ParameterValue {

    public static function getParameterValueByParameterIDAndValue(int $parameterID, string $value) {
        return Doctrine_Query::create()
            ->from('Admin_Model_ParameterValue pv')
            ->where('pv.Parameter_ID = ?', $parameterID)
            ->andWhere('pv.Value = ?', $value)
            ->fetchOne();
    }
}