<?php
use common\logic\Eshop\Eshop;
use common\logic\Helper\Price;
use Common_Model_Eshop as ModelEshop;

/**
 * Admin_Model_Payment
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Admin_Model_Payment extends Admin_Model_Base_Payment {

    /** @var string Typ GOPAY - Platba kartou */
    const TYPE_GOPAY = 'gopay';

    /** @var string Typ GOPAY - Paypal */
    const TYPE_GOPAY_PAYPAL = 'gopaypaypal';
    const TYPE_GOPAY_APPLE_PAY = 'gopayapplepay';

    /** @var string Typ BANK - Bankovní převod */
    const TYPE_BANK = 'bank';

    /** @var string Typ COD - Dobírka */
    const TYPE_COD = 'cod';

    /** @var string Typ CASH - Platba v hotovosti */
    const TYPE_CASH = 'cash';

    const TYPE_CSOB = 'csob';


    /** @var string Defaultní platba */
    const ID_DEFAULT_PAYMENT = 1;

    public static function getTypes(): array {
        $refl = new ReflectionClass(self::class);
        $constants = array_flip(array_filter($refl->getConstants(), function ($constant) {
            return startsWith($constant, 'TYPE_');
        }, ARRAY_FILTER_USE_KEY));

        $constantNames = [
            self::TYPE_GOPAY => 'GoPay',
            self::TYPE_GOPAY_PAYPAL => 'GoPay - PayPal',
            self::TYPE_GOPAY_APPLE_PAY => 'GoPay - ApplePay',
            self::TYPE_CSOB  => 'ČSOB',
            self::TYPE_BANK => translate('Bankovní převod'),
            self::TYPE_COD => translate('Dobírka'),
            self::TYPE_CASH => translate('Platba hotové'),
        ];

        return array_merge($constants, $constantNames);
    }

    /**
     * @param Common_Model_Eshop|null $eshop
     * @return array
     */
    public static function getActivePayments(ModelEshop $eshop = null): array {
        if ( !$eshop )
            $eshop = Eshop::getInstance()->getEshop();

        $query = Doctrine_Query::create();
        $query->from("Admin_Model_Payment object");
        $query->leftJoin('object.vat vat');
        $query->leftJoin('object.file file');
        $query->where('object.Active = ?', true);
        $query->andWhere('object.Eshop_ID = ?', $eshop->ID);
        $query->orderBy('object.ID');
        $payments = $query->execute()->toArray();

        foreach ( $payments as &$payment )
            $payment = Price::addVatPrices($payment);

        return $payments;
    }

    /**
     * @param int $paymentID
     * @return array
     */
    public static function getPaymentByID(int $paymentID): array {
        $query = Doctrine_Query::create();
        $query->from('Admin_Model_Payment object');
        $query->leftJoin('object.vat vat');
        $query->leftJoin('object.file file');
        $query->where('object.ID = ?', $paymentID);

        return Price::addVatPrices($query->execute()->toArray()[0]);
    }

    /**
     * @param int $shippingID
     * @return array
     */
    public static function getPaymentsForShipping(int $shippingID): array {
        $query = Doctrine_Query::create();
        $query->from('Admin_Model_ShippingPayment object');
        $query->where('object.Shipping_ID = ?', $shippingID);

        return $query->execute()->toArray();
    }

    public static function getPaymentByType(string $type, $eshopID = null): array
    {
        if($eshopID == null)
            $eshopID = Eshop::getInstance()->getEshopID();
        $query = Doctrine_Query::create();
        $query->from('Admin_Model_Payment object');
        $query->where('object.Type = ?', $type);
        $query->andWhere('object.Eshop_ID = ?', $eshopID);

        return $query->execute()->toArray()[0];

    }

    public static function getPaymentByCode(string $code) {
        $query = Doctrine_Query::create();
        $query->from('Admin_Model_Payment object');
        $query->where('object.Code = ?', $code);

        return $query->fetchOne();
    }
}