<?php

/**
 * Admin_Model_PPL
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Admin_Model_PPL extends Admin_Model_Base_PPL {
    const PPL_PARCEL_ID = 8;

    const CHECK_TYPE = [
        'OneSide' => 'MaxOneSideLengthInMM',
        'AllSides' => 'MaxTotalSideLengthInMM'
    ];
    const OPTIONS = [
        self::CHECK_TYPE['OneSide'] => 500,
        self::CHECK_TYPE['AllSides'] => 1200,
    ];


    public static function assignPPL(int $pickupPlaceID, string $pickupPlaceName, string $pickupPlaceAddress, string $pickupPlaceCode): Admin_Model_PPL {
        $ppl = new Admin_Model_PPL();
        $ppl->PickupPlace_ID = $pickupPlaceID;
        $ppl->PickupPlaceName = $pickupPlaceName;
        $ppl->PickupPlaceAddress = $pickupPlaceAddress;
        $ppl->PickupPlaceCode = $pickupPlaceCode;

        $ppl->save();

        return $ppl;
    }

    /**
     * @param int $productID
     * @return array
     */
    public static function getPPLDetailsByID(int $ID): array {
        $query = Doctrine_Query::create();
        $query->from('Admin_Model_PPL object');
        $query->where('object.ID = ?', $ID);
        return $query->execute()->toArray()[0];
    }

    /**
     * @param int $productID
     * @return array
     */
    public static function getPPL(int $ID): self|bool {
        $query = Doctrine_Query::create();
        $query->from('Admin_Model_PPL object');
        $query->where('object.ID = ?', $ID);
        return $query->fetchOne();
    }
}