<?php

/**
 * Admin_Model_PPLPackageNrSettings
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Admin_Model_PPLPackageNrSettings extends Admin_Model_Base_PPLPackageNrSettings
{

    public static function getPackageNumber($productTypeID): int
    {
        $query = Doctrine_Query::create();
        $query->from('Admin_Model_PPLPackageNrSettings');
        $query->where('ProductType_ID=?', $productTypeID);
        $record = $query->fetchOne();
        $packageNumber = 0;
        if(!$record->LastPackageNumber)
        {
            $record->LastPackageNumber = $record->PackageNumberSeriesFrom;
            $record->save();
            return $record->LastPackageNumber;
        } elseif( $record->LastPackageNumber < $record->PackageNumberSeriesTo ) {
            $packageNumber = $record->LastPackageNumber + 1;
        } elseif( $record->LastPackageNumber === $record->PackageNumberSeriesFrom ) {
            throw new Error ('Číselná řada je vyčerpaná. Kontaktujte podporu PPL');
        }

        $record->LastPackageNumber = $packageNumber;
        $record->save();

       return $packageNumber;
    }
}