<?php

/**
 * Admin_Model_ProductWatchDog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Admin_Model_ProductWatchDog extends Admin_Model_Base_ProductWatchDog
{
    /**
     * @param Doctrine_Connection|null $conn
     * @return void
     * @throws Exception
     */
    public function save(Doctrine_Connection $conn = null) {
        $isNew = $this->ID == null;

        if ( $isNew ) {
            $this->DateTimeCreated = date('Y-m-d H:i:s');
            $this->Reported = false;
        }

        parent::save($conn);

    }

    /**
     * @throws Exception
     */
    public static function setProductWatchDog(int $productID, int $userID): void {
        if( self::isProductWatchDogSet($productID, $userID) ) {
            return;
        }
        $productWatchDog = new self();
        $productWatchDog->Product_ID = $productID;
        $productWatchDog->User_ID = $userID;

        $productWatchDog->save();

    }

    /**
     * @throws Exception
     */
    public static function disableProductWatchDog(int $productID, int $userID): void {
        if( !$watchDog = self::getWatchdog($productID, $userID) ) {
            return;
        }

        $watchDog->delete();

    }


    public static function getAllWatchDogsForEmailNotificationByUsers(): array {
        $query = Doctrine_Query::create();
        $query->addSelect('pwd.ID, pwd.User_ID, pwd.Product_ID');
        $query->from('Admin_Model_ProductWatchDog pwd');
        $query->groupBy('pwd.Product_ID');
        $query->where('pwd.Reported = ?', false);
        $result = $query->execute([], Doctrine_Core::HYDRATE_ARRAY);
        $finalResult = [];

        if(!$result) {
            return $finalResult;
        }

        foreach ($result as $row) {
            $finalResult[$row['User_ID']][] = $row['Product_ID'];
        }

        return $finalResult;

    }

    public static function setWatchDogAsReported(int$userID, array $productsToBeReported): void {
        foreach ($productsToBeReported as $product) {
            $query = Doctrine_Query::create();
            $query->update('Admin_Model_ProductWatchDog pwd');
            $query->set('pwd.Reported', true);
            $query->where('pwd.User_ID = ?', $userID);
            $query->andWhere('pwd.Product_ID = ?', $product['Product_ID']);
            $query->execute();
        }

    }

    private static function isProductWatchDogSet(int $productID, int $userID) {
        $query = Doctrine_Query::create();
        $query->from('Admin_Model_ProductWatchDog pwd');
        $query->where('pwd.Product_ID = ?', $productID);
        $query->andWhere('pwd.User_ID = ?', $userID);
        return $query->count() > 0;
    }

    private static function getWatchdog(int $productID, int $userID) {
        $query = Doctrine_Query::create();
        $query->from('Admin_Model_ProductWatchDog pwd');
        $query->where('pwd.Product_ID = ?', $productID);
        $query->andWhere('pwd.User_ID = ?', $userID);
        return $query->fetchOne();
    }

}