<?php

/**
 * Admin_Model_ProductPrice
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Admin_Model_ProductPrice extends Admin_Model_Base_ProductPrice {
    public function save(Doctrine_Connection $conn = null) {
        parent::save($conn);
        Admin_Model_Product::updateProductDateTime($this->Product_ID);
    }

}