<?php
use admin\logic\Product\ProductPrice;
use Common_Model_Eshop as ModelEshop;
use common\logic\Eshop\Eshop;
use User\logic\UserSettings;

/**
 * Admin_Model_ProductRelated
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Admin_Model_ProductRelated extends Admin_Model_Base_ProductRelated {



    public function save(Doctrine_Connection $conn = null) {
        parent::save($conn);
        Admin_Model_Product::updateProductDateTime($this->Product_ID);
    }

    /**
     * @param int $productID
     * @param Common_Model_Eshop|null $eshop
     * @return array
     */
    public static function getProductRelateds(int $productID, ModelEshop $eshop = null) :array {
        if ( !$eshop )
            $eshop = Eshop::getInstance()->getEshop();

        $query = Doctrine_Query::create();
        $query->from("Admin_Model_Product product");
        $query->addSelect('product.*, productEshops.*, vat.*, productLangs.*, productLangs.Name as ProductName, productImages.*, file.*');
        $query->addSelect('productLangs.Name as ProductName, productLangs.slug as slug');
        $query->leftJoin('product.productEshops productEshops WITH productEshops.Eshop_ID = ?', $eshop->ID);
        $query->leftJoin('productEshops.vat vat');
        $query->leftJoin('product.productLangs productLangs WITH productLangs.Language_ID = ?', $eshop->Language_ID);
        $query->leftJoin('product.productImages productImages WITH productImages.Main = true');
        $query->leftJoin('productImages.file file');
        $query->leftJoin('product.productRelateds productRelateds');
        $query->andWhere('productEshops.Active = ?', true);
        $query->andWhere('productRelateds.Product_ID = ?', $productID);
        $query->limit(8);
        $products = $query->execute()->toArray();

        foreach ($products as &$product) {
            $productPrice = new ProductPrice($product, UserSettings::getInstance()->getValue('Discount'));
            $product = $productPrice->getProduct();
        }

        return $products;
    }

    public static function deleteProductRelated(int $productID) {
        $query = Doctrine_Query::create();
        $query->delete('Admin_Model_ProductRelated pr');
        $query->where('pr.Product_ID = ?', $productID);
        $query->execute();
    }

    public static function getProductsRelatedByProductID(int $productID): Doctrine_Collection {
        $query = Doctrine_Query::create();
        $query->from('Admin_Model_ProductRelated pr');
        $query->where('pr.Product_ID = ?', $productID);
        return $query->execute();
    }
}