<?php

/**
 * Admin_Model_ProductSlugHistory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Admin_Model_ProductSlugHistory extends Admin_Model_Base_ProductSlugHistory
{
    public function save(Doctrine_Connection $conn = null) {

        if($this->ID == null)
        $this->DateTimeCreated = date('Y-m-d H:i:s');

        parent::save();
    }

    /**
     * @throws Exception
     */
    public static function addSlugHistory(int $productID, string $slug): void {
        if (empty($productID) || empty($slug))
            throw new Exception('Product ID and Slug are required');
        if (self::slugAlreadyExists($slug, $productID)) {
            return;
        };
        $productSlugHistory = new self();
        $productSlugHistory->Product_ID = $productID;
        $productSlugHistory->Slug = trim($slug);

        $productSlugHistory->save();

    }

    private static function slugAlreadyExists(string $slug, int $productID): bool {
        $query = Doctrine_Query::create();
        $query->from('Admin_Model_ProductSlugHistory object');
        $query->where('object.Product_ID = ?', $productID);
        $query->andWhere('object.Slug = ?', trim($slug));
        return boolval($query->count());
    }


}