<?php

use common\logic\Eshop\Eshop;

/**
 * Admin_Model_ProductEshop
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Admin_Model_ProductEshop extends Admin_Model_Base_ProductEshop {


    /**
     * @param Doctrine_Connection|null $conn
     */
    public function save(Doctrine_Connection $conn = null) {
        if ($this->Price == null)
            $this->Price = 0;

        parent::save($conn);
        Admin_Model_Product::updateProductDateTime($this->Product_ID);
    }

    public static function getProductSlugAndNameByEshop(int $productID, Common_Model_Eshop $eshop = null): array {
        if ( !$eshop )
            $eshop = Eshop::getInstance()->getEshop();
        $query = Doctrine_Query::create();
        $query->from("Admin_Model_ProductEshop productEshop");
        $query->addSelect('productLangs.slug as Slug');
        $query->addSelect('productLangs.Name as Name');
        $query->leftJoin('productEshop.product product WITH product.ID = productEshop.Product_ID');
        $query->leftJoin('product.productLangs productLangs WITH productLangs.Language_ID = ?', $eshop->Language_ID);
        $query->addWhere('productEshop.Product_ID= ?', $productID);
        $query->addWhere('productEshop.Eshop_ID= ?', $eshop->ID);
        $result = $query->execute()->toArray()[0];
        return ['Slug' => $result['Slug'], 'Name'=> $result['Name']];
    }

    /**
     * @param string $categoryIDs
     * @return array
     */
    public static function getMinMaxPrice(string $categoryIDs): array{
        $query = Doctrine_Query::create();
        $query->addSelect('MAX(CEIL(object.price*(vat.value/100+1))) as MaxPrice');
        $query->addSelect('MIN(FLOOR(object.price*(vat.value/100+1))) as MinPrice');
        $query->from('Admin_Model_ProductEshop object');
        $query->leftJoin('object.product product');
        $query->leftJoin('product.categories categories');
        $query->leftJoin('object.vat vat');
        $query->andWhereIn('categories.Category_ID', explode(',', $categoryIDs));
        $result = $query->fetchOne();

        if ($result) {
            return [
                'MaxPrice' => $result->MaxPrice,
                'MinPrice' => $result->MinPrice,
            ];
        } else {
            return [];
        }
    }

    public static function deleteProductEshopPrice(int $productID) {
        $query = Doctrine_Query::create();
        $query->delete('Admin_Model_ProductEshop');
        $query->where('Product_ID = ?', $productID);
        $query->execute();
    }

    public static function getProductPrices(int $productID): Doctrine_Collection {
        $query = Doctrine_Query::create();
        $query->from('Admin_Model_ProductEshop pe');
        $query->where('pe.Product_ID = ?', $productID);
        return $query->execute();
    }

}