<?php

/**
 * Admin_Model_ProductImage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Admin_Model_ProductImage extends Admin_Model_Base_ProductImage {


    /**
     * @param Doctrine_Connection|null $conn
     */
    public function save(Doctrine_Connection $conn = null) {
        parent::save($conn);
        Admin_Model_Product::updateProductDateTime($this->Product_ID);

        $this->updateProductMainImage();
    }

    /**
     * @param Doctrine_Connection|null $conn
     */
    public function delete(Doctrine_Connection $conn = null) {
        parent::delete($conn);

        $query = Doctrine_Query::create();
        $query->from('Admin_Model_ProductImage object');
        $query->where('object.Main = ?', true);

        if ( !$query->count() ) {
            $query = Doctrine_Query::create();
            $query->update('Admin_Model_ProductImage object');
            $query->set('object.Main', true);
            $query->limit(1);
            $query->where('object.Product_ID = ?', $this->Product_ID);
            $query->execute();
        }
    }

    /**
     */
    private function updateProductMainImage() :void {
        if ( $this->Main ) {
            $query = Doctrine_Query::create();
            $query->update('Admin_Model_ProductImage object');
            $query->set('object.Main', '?', false);
            $query->where('object.ID != ?', $this->ID);
            $query->andWhere('object.Product_ID = ?', $this->Product_ID);
            $query->execute();
        } else {
            $query = Doctrine_Query::create();
            $query->from('Admin_Model_ProductImage object');
            $query->where('object.Main = ?', true);
            $query->andWhere('object.Product_ID = ?', $this->Product_ID);

            if ( !$query->count() ) {
                $this->Main = true;
                $this->save();
            }
        }
    }

    /**
     * @param int $productID
     * @return array
     */
    public static function getProductImages(int $productID) :array {
        $query = Doctrine_Query::create();
        $query->from('Admin_Model_ProductImage object');
        $query->leftJoin('object.file file');
        $query->orderBy('object.Main DESC');
        $query->where('object.Product_ID = ?', $productID);
        $query->andWhere('object.Main = ? OR object.Main IS NULL', false);

        return $query->execute()->toArray();
    }

    /**
     * @param int $productID
     * @return array
     */
    public static function getProductMainImage(int $productID) :array {
        $query = Doctrine_Query::create();
        $query->from('Admin_Model_ProductImage object');
        $query->leftJoin('object.file file');
        $query->where('object.Product_ID = ?', $productID);
        $query->andWhere('object.Main = ?', true);

        return $query->execute()->toArray();
    }


    public static function getLastRankByProductID(int $productID)
    {
        $query = Doctrine_Query::create();
        $query->from('Admin_Model_ProductImage object');
        $query->select('MAX(object.Rank) as MaxRank');
        $query->where('object.Product_ID=?', $productID);
        $fetch = $query->fetchOne();
        if($fetch) {
            return $fetch->MaxRank;
        } else
            return 0;
    }

    public static function getProductImageByProductAndFileID(int $productID, int $originalFileID) {
        $query = Doctrine_Query::create();
        $query->from('Admin_Model_ProductImage object');
        $query->where('object.Product_ID=?', $productID);
        $query->andWhere('object.File_ID=?', $originalFileID);
        return $query->fetchOne();
    }

}