<?php

/**
 * Admin_Model_ProductParameter
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Admin_Model_ProductParameter extends Admin_Model_Base_ProductParameter {
    public function save(Doctrine_Connection $conn = null) {
        parent::save($conn);
        Admin_Model_Product::updateProductDateTime($this->Product_ID);
    }

    /**
     * @param int $productID
     * @param int $parameterID
     * @param string $value
     * @return Admin_Model_ProductParameter
     */
    public static function createProductParameter(int $productID, int $parameterID, string $value): Admin_Model_ProductParameter {
        $productParameter = new Admin_Model_ProductParameter();
        $productParameter->Product_ID = $productID;
        $productParameter->Parameter_ID = $parameterID;
        $productParameter->Value = $value;
        $productParameter->save();

        return $productParameter;
    }

    public static function deleteProductParameters(int $productID) {
        $query = Doctrine_Query::create();
        $query->delete('Admin_Model_ProductParameter pp');
        $query->where('pp.Product_ID = ?', $productID);
        $query->execute();
    }

    public static function getProductParameters(int $productID) {
        $query = Doctrine_Query::create();
        $query->from('Admin_Model_ProductParameter pp');
        $query->where('pp.Product_ID = ?', $productID);
        return $query->execute();
    }

}