<?php

/**
 * Admin_Model_ProductDescriptionAccordion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Admin_Model_ProductDescriptionAccordion extends Admin_Model_Base_ProductDescriptionAccordion
{
    /**
     * @throws Doctrine_Query_Exception
     */
    public static function getProductDescriptionAccordions(int $productID): array {
        $query = Doctrine_Query::create();
        $query->from('Admin_Model_ProductDescriptionAccordion');
        $query->where('Product_ID=?', $productID);
        return $query->execute()->toArray();
    }

}