<?php

/**
 * Admin_Model_Recomendation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Admin_Model_Recomendation extends Admin_Model_Base_Recomendation
{

    public static function getRecommendations() {
        $types = ['drink', 'meal', 'sleep', 'stress', 'cosmetics'];
        $recommendations = [];

        foreach ($types as $type) {
            $query = Doctrine_Query::create()
                ->from('Admin_Model_Recomendation')
                ->where('Type = ?', $type)
                ->orderBy('RAND()')
                ->limit(1);

            $recommendation = $query->fetchOne(array(), Doctrine_Core::HYDRATE_ARRAY);

            if ($recommendation) {
                $recommendations[$type] = $recommendation;
            }
        }

        return !empty($recommendations) ? $recommendations : null;
    }

}