<?php
use common\logic\Eshop\Eshop;
use user\logic\UserClientSession;

/**
 * Admin_Model_SearchLog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Admin_Model_SearchLog extends Admin_Model_Base_SearchLog {

    /**
     * @param string $term
     * @param Eshop|null $eshop
     */
    public static function createSearchLog(string $term, Eshop $eshop = null) {
        if ( !$eshop )
            $eshop = Eshop::getInstance()->getEshop();

        $searchLog = new Admin_Model_SearchLog();
        $searchLog->Date = date('Y-m-d');
        $searchLog->Time = date('H:i:s');
        $searchLog->SearchTerm = $term;
        $searchLog->Eshop_ID = $eshop->ID;

        if ( UserClientSession::getCurrentUserID() )
            $searchLog->User_ID = UserClientSession::getCurrentUserID();

        $searchLog->save();
    }
}