<?php

/**
 * Admin_Model_ShippingCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Admin_Model_ShippingCategory extends Admin_Model_Base_ShippingCategory {

    /**
     * @param int $shippingID
     * @param string $categoryIDs
     * @return array
     */
    public static function getShippingCategory(int $shippingID, string $categoryIDs): array {
        $query = Doctrine_Query::create();
        $query->from('Admin_Model_ShippingCategory object');
        $query->leftJoin('object.vat vat');
        $query->where('object.Shipping_ID = ?', $shippingID);
        $query->andWhereIn('object.Category_ID', explode(',', $categoryIDs));

        return $query->execute()->toArray();
    }
}