<?php

use admin\logic\Shipping\ShippingDisplay;
use admin\logic\Shipping\ShippingPrice;
use common\logic\Eshop\Eshop;
use common\logic\Front\Cart;
use Common_Model_Eshop as ModelEshop;
use Admin_Model_ProductMeta as ProductMeta;

/**
 * Admin_Model_Shipping
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Admin_Model_Shipping extends Admin_Model_Base_Shipping {

    /**
     * @param Common_Model_Eshop|null $eshop
     * @param Cart|null $cart
     * @return array
     * @throws Doctrine_Query_Exception
     */
    public static function getActiveShippings(ModelEshop $eshop = null, Cart $cart = null): array {
        $forbiddenShippingMethods = [];
        $alwaysAllowedShippingMethods = ['OSO1PATR', 'OSOFRANC'];
        if ($cart) {
            $cartItems = $cart->getCartItems();
            $productIds = [];
            foreach ($cartItems as $cartItem) {
               $productIds[] = $cartItem['product']['ID'];
            }
            $forbiddenShippingMethods = ProductMeta::getDeniedShippingMethodCodes($productIds);
            $requiredShippingMethods = ProductMeta::getRequiredShippingMethodCodes($productIds);
        }

        if ( !$eshop )
            $eshop = Eshop::getInstance()->getEshop();

        $query = Doctrine_Query::create();
        $query->from("Admin_Model_Shipping object");
        $query->leftJoin('object.vat vat');
        $query->leftJoin('object.file file');
        $query->leftJoin('object.shippingPrices shippingPrices');
        $query->where('object.Active = ?', true);
        $query->andWhere('object.Eshop_ID = ?', $eshop->ID);
        if($forbiddenShippingMethods && empty($requiredShippingMethods)) {
            $query->andWhereNotIn('object.Code', $forbiddenShippingMethods);
        }
        if(!empty($requiredShippingMethods)) {
            $query->andWhereIn('object.Code', array_merge($requiredShippingMethods, $alwaysAllowedShippingMethods));
        } else {
            $query->orWhereIn('object.Code', $alwaysAllowedShippingMethods);
        }
        $query->orderBy('object.ID');
        $shippings = $query->execute()->toArray();

        foreach ( $shippings as &$shipping ) {
            $shipping = ShippingPrice::computeShippingPrice($shipping, $cart);
        }

        return $shippings;
    }

    /**
     * @param int $shippingID
     * @param Cart|null $cart
     * @return array
     * @throws Doctrine_Query_Exception
     */
    public static function getShippingByID(int $shippingID, Cart $cart = null): array {
        $query = Doctrine_Query::create();
        $query->from('Admin_Model_Shipping object');
        $query->leftJoin('object.vat vat');
        $query->leftJoin('object.shippingPrices shippingPrices');
        $query->leftJoin('object.file file');
        $query->where('object.ID = ?', $shippingID);

        return ShippingPrice::computeShippingPrice($query->execute()->toArray()[0], $cart);
    }

    /**
     * @param int $shippingID
     * @param Cart|null $cart
     * @return array
     * @throws Doctrine_Query_Exception
     */
    public static function isPPLShipping(int $shippingID): bool {
        return $shippingID == Admin_Model_PPL::PPL_PARCEL_ID;
    }

    public static function getShipping(?int $shippingMethodID) {
        $query = Doctrine_Query::create();
        $query->from('Admin_Model_Shipping object');
        $query->where('object.ID = ?', $shippingMethodID);
        return $query->fetchOne();
    }

    /**
     * @param Common_Model_Eshop|null $eshop
     * @param Cart|null $cart
     * @return array
     * @throws Doctrine_Query_Exception
     */
    public static function getActiveShippingsCollection(): Doctrine_Collection {
        $query = Doctrine_Query::create();
        $query->from("Admin_Model_Shipping object");
        $query->leftJoin('object.vat vat');
        $query->where('object.Active = ?', true);
        $query->orderBy('object.ID');
        return $query->execute();

    }

    public static function getShippingByExternalID(mixed $externalId) {
        $query = Doctrine_Query::create();
        $query->from('Admin_Model_Shipping object');
        $query->where('object.ExternalID = ?', $externalId);
        return $query->fetchOne();
    }

    public static function getShippingByCode(string $code) {
        $query = Doctrine_Query::create();
        $query->from('Admin_Model_Shipping object');
        $query->where('object.Code = ?', $code);
        return $query->fetchOne();
    }

    public static function getFreeShipping() {
        $freeShippingLimit = self::getMinFreeShippingCarrier();
        if(!$freeShippingLimit) {
            return false;
        }
        $cart = Cart::getInstance();
        $totalPriceWithVat =  $cart->getTotalPriceWithVat();
        $result =  $freeShippingLimit - $totalPriceWithVat;
        if($result < 0) {
            return ['Rest' => 0, 'Limit' => $freeShippingLimit];
        } else {
            return ['Rest' => $result, 'Limit' => $freeShippingLimit];
        }
    }


    public static function getMinFreeShippingCarrier() {
        $query = Doctrine_Query::create();
        $query->from('Admin_Model_Shipping');
        $query->addSelect('MIN(freeshipping) as FreeShipping');
        $fetch = $query->fetchOne();
        if($fetch)
            return $fetch->FreeShipping;
    }

}
