<?php

/**
 * Admin_Model_ShippingPrice
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Admin_Model_ShippingPrice extends Admin_Model_Base_ShippingPrice
{

    public static function clearShippingPrices($shippingID) {
        $query = Doctrine_Query::create();
        $query->delete('Admin_Model_ShippingPrice')
            ->where('Shipping_ID = ?', $shippingID)
            ->execute();
    }
}