<?php

use common\logic\Front\Cart;

/**
 * Admin_Model_Zasilkovna
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Admin_Model_Zasilkovna extends Admin_Model_Base_Zasilkovna {

    const ZASILKOVNA_CZ_ID = 13;
    const ZASILKOVNA_SK_ID = 12;
    const ZASILKOVNA_HOUSE_DELIVERY_ID = 2;


    const CHECK_TYPE = [
        'OneSide' => 'MaxOneSideLengthInMM',
        'AllSides' => 'MaxTotalSideLengthInMM'
    ];
    const OPTIONS = [
        self::CHECK_TYPE['OneSide'] => 500,
        self::CHECK_TYPE['AllSides'] => 1200,
    ];

    /**
     * @param int $pickupPlaceID
     * @param string $pickupPlaceName
     * @param string $pickupPlaceAddress
     * @return Admin_Model_Zasilkovna
     */
    public static function assignZasilkovna(int $pickupPlaceID, string $pickupPlaceName, string $pickupPlaceAddress): self {
        $zasilkovna = new Admin_Model_Zasilkovna();
        $zasilkovna->PickupPlace_ID = $pickupPlaceID;
        $zasilkovna->PickupPlaceName = $pickupPlaceName;
        $zasilkovna->PickupPlaceAddress = $pickupPlaceAddress;
        $zasilkovna->save();

        return $zasilkovna;
    }

    /**
     * @param int $productID
     * @return array
     */
    public static function getZasilkovnaDetailsByID(int $ID): array {
        $query = Doctrine_Query::create();
        $query->from('Admin_Model_Zasilkovna object');
        $query->where('object.ID = ?', $ID);
        return $query->execute()->toArray()[0];
    }

    public static function getZasilkovna(int $ID): self|bool {
        $query = Doctrine_Query::create();
        $query->from('Admin_Model_Zasilkovna object');
        $query->where('object.ID = ?', $ID);
        return $query->fetchOne();
    }

    public static function checkShippingDeliveryConditions(?Cart $cart): bool {
        $valid = false;
        if (!$cart) {
            return false;
        }

        function removeNonNumericChars($value): array|string|null {
            return preg_replace("/[^0-9]/", "", trim($value));
        }

        $cartItems = $cart->getCartItems();

        foreach ($cartItems as $cartItem) {

            $dimensionValues = Admin_Model_ProductionInformation::getSizeSheet($cartItem['product']['ID']);
            if(empty($dimensionValues))
                return false;

            $dimensionValues = explode(',', $dimensionValues);

            foreach ($dimensionValues as $dimensionValue) {
                $itemDimensions = array_map('removeNonNumericChars', explode('x', $dimensionValue));
                $allSidesSum = array_sum($itemDimensions);

                foreach ($itemDimensions as $itemDimension) {
                    if (!self::zasilkovnaDimensionsDeliveryRestriction($itemDimension, self::CHECK_TYPE['OneSide'])) {
                        return false;
                    }
                }
                if (self::zasilkovnaDimensionsDeliveryRestriction($allSidesSum, self::CHECK_TYPE['AllSides'])) {
                    $valid = true;
                } else {
                    return false;
                }
            }
        }

        return $valid;
    }

    private static function zasilkovnaDimensionsDeliveryRestriction($value, $checkType): bool {
        return match ($checkType) {
            self::CHECK_TYPE['OneSide'] => $value <= self::OPTIONS[self::CHECK_TYPE['OneSide']],
            self::CHECK_TYPE['AllSides'] => $value <= self::OPTIONS[self::CHECK_TYPE['AllSides']],
            default => false
        };
    }
}