<?php

namespace admin\logic\Order;

use Admin_Model_Order as OrderModel;
use Admin_Model_Vat;
use common\logic\Eshop\Eshop;
use common\logic\Helper\QrPayment;
use Admin_Model_Payment as Payment;

use Exception;

class InvoicePdf extends CreatePdf {

    const FILE_NAME = 'invoice';
    private $bankAccount;
    private $bankIban;
    const BANK_KS = "0308";
    const DUE_DAYS = '14';
    private $order;
    private $params;
    private $counter = 0;

    /**
     * @throws \Mpdf\MpdfException
     * @throws \PHPMailer\PHPMailer\Exception
     */
    public function __construct(int $order_ID, ?string $note = null) {
        if (!$this->order = OrderModel::getOrder($order_ID))
            throw new Exception('Order not found');

        if ( !$this->order->InvoiceNumber )
            $this->order->updateInvoiceNumber();

        $bankDetails = \Admin_Model_Payment::getPaymentByType(\Admin_Model_Payment::TYPE_BANK);

        $this->bankAccount = str_replace(' ', '', $bankDetails['BankAccount']);
        $this->bankIban = $bankDetails['IBAN'];

        parent::__construct([]);

        $this->setupHeader(translate('Faktura - DAŇOVÝ DOKLAD č.') . ' ' . $this->order->InvoiceNumber);

        $withoutVat = $this->order->InvoiceAddress_ID && $this->order->invoiceAddress->DIC;
        $dueDate = date('Y-m-d', strtotime('+' . self::DUE_DAYS . ' days'));
        $coupon = $this->order->coupon;

        if(isset($coupon->Type))
            $couponValue = $coupon->Type == 'percentage'?$this->order->PriceTotalWithVat - ($this->order->PriceTotalWithVat / (1-($coupon->Discount/100))): $coupon->Discount;
        else
            $couponValue = null;

        $this->params = [
            'eshopID'=> Eshop::getInstance()->getEshopID(),
            'invoiceDate' => date('Y-m-d'),
            'dueDate' => $dueDate,
            'contractor' => $this->getContractor(),
            'customer' => $this->getCustomer(),
            'currency' => $this->getCurrency()['Mark'],
            'isBankPayment' => $this->isBankPayment(),
            'bankDetails' => $bankDetails,
            'order' => $this->order,
            'withoutVat' => $withoutVat,
            'note' => $note,
            'title' => $this->title,
            'vatData'=> $this->calculateVat(),
            'coupon'=> $coupon,
            'couponValue' => $couponValue
        ];

        $this->WriteHTML($this->renderTemplate('/invoice/index', $this->params));
    }

    function AddPage($orientation = '', $condition = '', $resetpagenum = '', $pagenumstyle = '', $suppress = '', $mgl = '', $mgr = '', $mgt = '', $mgb = '', $mgh = '', $mgf = '', $ohname = '', $ehname = '', $ofname = '', $efname = '', $ohvalue = 0, $ehvalue = 0, $ofvalue = 0, $efvalue = 0, $pagesel = '', $newformat = '') {
        $this->counter = 0;
        return parent::AddPage($orientation, $condition, $resetpagenum, $pagenumstyle, $suppress, $mgl, $mgr, $mgt, $mgb, $mgh, $mgf, $ohname, $ehname, $ofname, $efname, $ohvalue, $ehvalue, $ofvalue, $efvalue, $pagesel, $newformat); // TODO: Change the autogenerated stub
    }

    public function Footer() {
        parent::Footer();
    }

    private function calculateVat(){
        $vatData = [];
        $data = [];
        foreach ($this->order->orderItems as &$item) {
            $data['VAT_Ratio'] = Admin_Model_Vat::getVatRatioByID($item['product']['productEshops'][0]['Vat_ID']);
            if(!isset($vatData[$data['VAT_Ratio']])) {
                $vatData[$data['VAT_Ratio']]['PriceTotalWithoutVat'] = floatval($item['PriceWithoutVat'] * $item['Quantity']);
                $vatData[$data['VAT_Ratio']]['PriceTotalWithVat'] = floatval($item['PriceWithVat'] * $item['Quantity']);
            } else {
                $vatData[$data['VAT_Ratio']]['PriceTotalWithoutVat'] += floatval($item['PriceWithoutVat'] * $item['Quantity']);
                $vatData[$data['VAT_Ratio']]['PriceTotalWithVat'] += floatval($item['PriceWithVat'] * $item['Quantity']);
            }

        }

        $shippingVatRatio = Admin_Model_Vat::getVatRatioByID($this->order->shipping->Vat_ID);

        if($shippingVatRatio) {
            if(!isset($vatData[$shippingVatRatio])) {
                $vatData[$shippingVatRatio]['PriceTotalWithoutVat'] = floatval($this->order->PriceShippingWithoutVat);
                $vatData[$shippingVatRatio]['PriceTotalWithVat'] = floatval($this->order->PriceShippingWithVat);
            } else {
                $vatData[$shippingVatRatio]['PriceTotalWithoutVat'] += floatval($this->order->PriceShippingWithoutVat);
                $vatData[$shippingVatRatio]['PriceTotalWithVat'] += floatval($this->order->PriceShippingWithVat);
            }
        }

        $paymentVatRatio = Admin_Model_Vat::getVatRatioByID($this->order->payment->Vat_ID);

        if($paymentVatRatio) {
            if(!isset($vatData[$paymentVatRatio])) {
                $vatData[$paymentVatRatio]['PriceTotalWithoutVat'] = floatval($this->order->PricePaymentWithoutVat);
                $vatData[$paymentVatRatio]['PriceTotalWithVat'] = floatval($this->order->PricePaymentWithVat);
            } else {
                $vatData[$paymentVatRatio]['PriceTotalWithoutVat'] += floatval($this->order->PricePaymentWithoutVat);
                $vatData[$paymentVatRatio]['PriceTotalWithVat'] += floatval($this->order->PricePaymentWithVat);
            }
        }

        return $vatData;
    }

    /**
     * Vrací info pro dodavatele
     * @return array
     */
    private function getContractor(): array {
        $eshop = Eshop::getInstance();
        return [
            'infoType' => translate('Dodavatel', $this->order->language->Code),
            'fullName' => $eshop->getSettings('ProjectName'),
            'street' => $eshop->getSettings('AddressStreet'),
            'zip' => $eshop->getSettings('AddressZipCode'),
            'city' => $eshop->getSettings('AddressCity'),
            'country' => 'CZ',
            'ic' => $eshop->getSettings('RegistrationNumber'),
            'dic' => $eshop->getSettings('VATNumber'),
            'bankAccount' => [
                'BankAccount' => $this->bankAccount,
//                'IBAN' => $this->bankIban,
//                'BIC' => self::BANK_BIC,
//                'paymentType' => translate('Příkazem', $this->order->language->Code),
                'paymentType' => translate($this->order->payment->Name, $this->order->language->Code),
                'VS' => $this->order->OrderNumber,
                'KS' => self::BANK_KS,
            ]
        ];
    }

    /**
     * Vrací info pro odběratele
     * @return array|null
     * @throws Exception
     */
    private function getCurrency(): \Admin_Model_Currency {
        return \Admin_Model_Currency::getCurrencyByID($this->order->Currency_ID);
    }

    /**
     * Vrací info pro odběratele
     * @return array|null
     * @throws Exception
     */
    private function getCustomer(): ?array {
        $customer = null;
        if ($this->order->InvoiceAddress_ID) {
            $inv = $this->order->invoiceAddress;
            $customer = [
                'infoType' => translate('Odběratel'),
                'fullName' => !empty($inv->CompanyName) ? $inv->CompanyName : $inv->getFullName(),
                'street' => $inv->getFullStreet(),
                'zip' => $inv->ZipCode,
                'city' => $inv->City,
                'country' => $inv->Country_ID ? $inv->country->getLang($this->order->Language_ID)->Name : null,
                'ic' => $inv->IC,
                'dic' => $inv->DIC,
                'phone' => $inv->Phone,
                'orderInfo' => [
                    'VS' => $this->order->OrderNumber,
                    'KS' => self::BANK_KS,
                    'OrderNumber' => $this->order->OrderNumber,
                    'OrderDate' => $this->order->Date
                ]
            ];
        }

        return $customer;
    }

    public function Output($name = '', $dest = '') {
        if (empty($name)) {
            $name = "invoice-{$this->order->OrderNumber}.pdf";
        }
        return parent::Output($name, $dest);
    }

    private function isBankPayment(): bool {
        return $this->order->payment->Type === Payment::TYPE_BANK;
    }
}