<?php

/**
 * Common_Model_Country
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Common_Model_Country extends Common_Model_Base_Country {

    const CZ_ID = 50;
    const SK_ID = 166;

    const ALLOWED_COUNTRIES = [self::CZ_ID, self::SK_ID];

    public static function getCountryByID(int $countryID) {
        $query = Doctrine_Query::create();
        $query->from('Common_Model_Country');
        $query->where('ID=?', $countryID);

        return $query->fetchOne();
    }

    public static function getCountryByCode(string $state) {
        $query = Doctrine_Query::create();
        $query->from('Common_Model_Country');
        $query->where('Code=?', $state);

        return $query->fetchOne();
    }

    public static function getCountries() {
        $query = Doctrine_Query::create();
        $query->from('Common_Model_Country object');
        $query->leftJoin('object.countryLangs countryLangs');
        return $query->fetchArray();
    }

    public static function getCountryIDByEkonomisCode($DeliveryCountry) {
        return match($DeliveryCountry) {
            'ČR' => self::getCountryByID(self::CZ_ID),
            'SR' => self::getCountryByID(self::SK_ID),
            default => false,
        };
    }
}