<?php

/**
 * Common_Model_CronLog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Common_Model_CronLog extends Common_Model_Base_CronLog {

    const STATUS_OK = 'OK';
    const STATUS_EXCEPTION = 'Exception';
    const STATUS_ERROR = 'Error';
    const STATUS_NOT_FOUND = 'Not Found';

    public static function getLogs($range = 1440, $step = 60): object {
        $con = \Doctrine_Manager::connection()->getDbh();
        $offset = new DateTime();
        $offset->sub(new DateInterval("PT{$range}M"));
        $offsetTime = $offset->format('Y-m-d H:i:s');

        $sql = <<<SQL
SELECT
  - TIMESTAMPDIFF (MINUTE, `l`.`datetimestart`, "$offsetTime") AS `left`,
  - TIMESTAMPDIFF (MINUTE,  IFNULL(`l`.`datetimestop`, `l`.`datetimestart`), "$offsetTime") AS `right`,
  `l`.`datetimestart` AS `start`,
  `l`.`datetimestop` AS `stop`,
  TIMESTAMPDIFF (SECOND, `l`.`datetimestart`, IFNULL(`l`.`datetimestop`, `l`.`datetimestart`)) AS `runtime`,
  `l`.`status`,
  `l`.`message`,
  IFNULL(`c`.`name`, `c`.`script`) AS `name`,
  `c`.`id` AS `id`
FROM `common__model__cron_log` `l`
    INNER JOIN `common__model__cron` `c` ON (`l`.`cron_id` = `c`.`id`)
WHERE `l`.`datetimestart` >  "$offsetTime"
ORDER BY 1, 2 DESC;
SQL;

        $arr = $con->query($sql)->fetchAll(\PDO::FETCH_OBJ);

        $final = array();
        $middle = array();

        if (is_array($arr) && count($arr) > 1) {
            $level = 0;
            do {
                $arr[0]->top = $level;
                $arr[0]->width = $arr[0]->right - $arr[0]->left + 4;
                $arr[0]->before = gmdate("H:i:s", $arr[0]->before ?? 0);
                $arr[0]->runtime = gmdate("H:i:s", $arr[0]->runtime ?? 0);
                $final[] = $arr[0];
                $maxRight = $arr[0]->right + 5;
                for ($i = 1; $i < count($arr) - 1; $i++) {
                    if ($arr[$i]->left > $maxRight) {
                        $arr[$i]->top = $level;
                        $arr[$i]->width = $arr[$i]->right - $arr[$i]->left + 4;
                        $arr[$i]->before = gmdate("H:i:s", $arr[$i]->before ?? 0);
                        $arr[$i]->runtime = gmdate("H:i:s", $arr[$i]->runtime ?? 0);
                        $final[] = $arr[$i];
                        $maxRight = $arr[$i]->right + 4;
                    } else {
                        $middle[] = $arr[$i];
                    }
                }
                if (count($middle)) {
                    $arr = $middle;
                    $middle = array();
                    $level++;
                } else {
                    $arr = array();
                }
            } while (count($arr));
        }

        return (object)[
            'offset' => $offset->sub(new DateInterval("PT{$step}M")),
            'items' => $final,
            'range' => $range,
            'step' => $step,
            'level' => $level ?? 0,
        ];

        /*
        $sql = <<<SQL
set @minus = '$offsetTime'
SQL;
        $con->exec($sql);

        $sql = <<<SQL
CREATE TEMPORARY TABLE `aaaruns`(
    `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
    `oldid` BIGINT(20) NOT NULL,
    `start` BIGINT DEFAULT NULL,
    `stop` BIGINT DEFAULT NULL,
    PRIMARY KEY USING BTREE(`id`)
);
SQL;
        $con->exec($sql);

        $sql = <<<SQL
INSERT INTO `aaaruns`(`oldid`, `start`, `stop`)
SELECT
  `id`,
  - TIMESTAMPDIFF (MINUTE, `datetimestart`, @`minus`),
  - TIMESTAMPDIFF (MINUTE, `datetimestop`, @`minus`) + 6
FROM `common__model__cron_log`
WHERE `datetimestart` > @`minus`
ORDER BY 2, 3 DESC;
SQL;
        $con->exec($sql);


        $sql = <<<SQL
WITH `cnt` AS (
SELECT `a2`.`id`, COUNT(*) AS `cnt`
FROM `aaaruns` AS `a1`
     INNER JOIN `aaaruns` AS `a2` ON (`a1`.`id` < `a2`.`id` AND `a2`.`start` BETWEEN `a1`.`start` AND `a1`.`stop`)
GROUP BY `a2`.`id`)
SELECT
  2 + IFNULL(`b`.`cnt`, 0) * 30 AS `top`,
  `a`.`start` AS `left`,
  `a`.`stop` - `a`.`start` AS `width`,
  `l`.`status`,
  IFNULL(`c`.`name`, `c`.`script`) AS `name`,
  `c`.`id` AS `id`
FROM `aaaruns` `a`
     LEFT JOIN `cnt` `b` ON (`a`.`id` = `b`.`id`)
     INNER JOIN `common__model__cron_log` `l` ON (`l`.`id` = `a`.`oldid`)
     INNER JOIN `common__model__cron` `c` ON (`l`.`cron_id` = `c`.`id`)
ORDER BY 1, 2;
SQL;

        $arr = $con->query($sql)->fetchAll(\PDO::FETCH_OBJ);

        return (object)array('offset' => $offset->sub(new DateInterval('PT60M')), 'items' => $arr);
        */
    }

    /**
     * @param int $cron_ID
     * @return array|false
     */
    public static function getCronLogs(int $cron_ID): array|false
    {
        $sql = <<<SQL
SELECT
  `l`.`datetimestart` AS `DateTimeStart`,
  `l`.`datetimestop` AS `DateTimeStop`,
  `l`.`status` AS `Status`,
  `l`.`message` AS `Message`
FROM
  `common__model__cron_log` `l`
WHERE
  `l`.`cron_id` = $cron_ID
ORDER BY
  `l`.`datetimestart` DESC
SQL;

        $sth = \Doctrine_Manager::connection()->getDbh()->prepare($sql);
        $sth->execute();
        $rows = $sth->fetchAll(\PDO::FETCH_OBJ);

        return $rows;
    }

    public function getRunsInDay(): int
    {
        $sql = <<<SQL
SELECT
 COUNT(*) AS `count`
FROM
  `common__model__cron_log` `l`
WHERE
  `l`.`cron_id` = $this->ID
  AND `l`.`status` = 'OK'
  AND DATE(`l`.`datetimestart`) = CURDATE()
SQL;

        return \Doctrine_Manager::connection()->getDbh()->query($sql)->fetchColumn();
    }

    public function getLastRunRunsInDay(): int
    {
        $sql = <<<SQL
SELECT
 	MAX(`l`.`datetimestop`) AS `lastRun`
FROM
  `common__model__cron_log` `l`
WHERE
  `l`.`cron_id` = $this->ID
  AND `l`.`status` LIKE '%OK%'
GROUP BY
  `l`.`cron_id`
SQL;
        $lastRun = \Doctrine_Manager::connection()->getDbh()->query($sql)->fetchColumn();
        if (!$lastRun) {
            $date = new \DateTime();

            return $date->getTimestamp() - 60;
        }

        return strtotime($lastRun);
    }

    public static function sendMemoryUsageReport(int $minUsage = 1000): bool
    {
        $sql = <<<SQL
SELECT `amc`.`id`, `amc`.`name`, `amc`.`active`, `amc`.`cronexpression`, MAX(CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`amcl`.`message`, 'RM: ', -1), 'MB', 1) AS DECIMAL(10,2))) AS `max_usage` 
FROM `common__model__cron_log` `amcl` 
INNER JOIN `common__model__cron` `amc` ON `amcl`.`cron_id` = `amc`.`id`
WHERE `amcl`.`message` LIKE '%[M:%' 
  AND CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(`amcl`.`message`, 'RM: ', -1), 'MB', 1) AS DECIMAL(10,2)) > ?
  AND `amcl`.`datetimestart` > DATE_SUB(NOW(), INTERVAL 1 WEEK)
GROUP BY `amcl`.`cron_id` 
ORDER BY `amcl`.`cron_id`;
SQL;

        $data = Doctrine_Manager::connection()->fetchAll($sql, [$minUsage]);

        if (!empty($data)) {
            \common\logic\Email\Email::sendCronMemoryUsageReport($data);
            return true;
        }

        return false;
    }
}