<?php
use common\logic\Configs;

/**
 * Common_Model_File
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Common_Model_File extends Common_Model_Base_File {
    const SIZE_MINI = '50';
    const SIZE_MIDI = '200';
    const SIZE_MEDIUM = '350';
    const SIZE_MAXI = '800';
    const SIZE_ORIGINAL = 'original';

    const TYPE_PRODUCT_PHOTO = 'product-photo';
    const TYPE_PRODUCT_DOCUMMENT = 'product-documment';
    const TYPE_MANUFACTURER = 'manufacturer';
    const TYPE_BANNER = 'banner';
    const TYPE_CATEGORY_PHOTO = 'category-photo';
    const TYPE_CATEGORY_PICTOGRAM = 'category-pictogram';
    const TYPE_NEWS = 'news';
    const TYPE_DAILY_PHOTO = 'daily-photo';
    const TYPE_LOGO = 'logo';
    const TYPE_FEEDBACK_ATTACHMENT = 'feedback-attachment';
    const TYPE_PRODUCT_SOFTWARE = 'product-software';

    const TYPE_PRODUCT_PHOTO_FOLDER = 'files/images/product/';
    const TYPE_PRODUCT_DOCUMMENT_FOLDER = 'files/documments/product/';
    const TYPE_CATEGORY_PHOTO_FOLDER = 'files/images/category/';
    const TYPE_CATEGORY_PICTOGRAM_FOLDER = 'files/images/category-pictogram/';
    const TYPE_MANUFACTURER_FOLDER = 'files/images/manufacturer/';
    const TYPE_BANNER_FOLDER = 'files/images/banner/';
    const TYPE_NEWS_FOLDER = 'files/images/news/';
    const TYPE_DAILY_PHOTO_FOLDER = 'files/images/daily-photos/';
    const TYPE_LOGO_FOLDER = 'files/images/logo/';
    const TYPE_FEEDBACK_ATTACHMENT_FOLDER = 'files/feedback/';
    const TYPE_PRODUCT_SOFTWARE_FOLDER = 'files/images/software/product';

    /**
     * @param Doctrine_Connection|null $conn
     * @return bool|void
     */
    public function delete(Doctrine_Connection $conn = null) {
        if ($this->Type == 'product-photo') {
            foreach (self::getSizes() as $folder) {
                deleteFile(self::TYPE_PRODUCT_PHOTO_FOLDER . $folder . '/' . $this->Name . '.' . $this->Extension);
            }
        }

        if ($this->Type == self::TYPE_FEEDBACK_ATTACHMENT) {
            deleteFile(self::TYPE_FEEDBACK_ATTACHMENT_FOLDER . $this->getFileName());
        }

       return parent::delete($conn);
    }

    /**
     * @return string[]
     */
    public static function getRSizes(): array {
        return [self::SIZE_MINI, self::SIZE_MIDI, self::SIZE_MEDIUM, self::SIZE_MAXI];
    }

    /**
     * @return string[]
     */
    public static function getSizes(): array {
        $sizes = self::getRSizes();
//        $sizes[] = self::SIZE_ORIGINAL;

        return $sizes;
    }

    /**
     * @param int $ID
     * @param int $size
     * @return string
     */
    public static function getFileUrlByID(int $ID, int $size): string {
        $file = self::getFile($ID);

        return _bu() . '/files/images/' . $size . '/' . $file->Name . '.' . $file->Extension;
    }

    /**
     * @param array|Admin_Model_ProductImage|Admin_Model_News $file
     * @param string $folder
     * @param string $fileKey
     * @return string
     */
    public static function getFileUrl(array|Admin_Model_ProductImage|Admin_Model_News $file, string $folder, string $fileKey): string {
        return  _bu() . '/files/images/' . $folder . '/' . $file[$fileKey]["Name"] . '.' . $file[$fileKey]["Extension"];
    }

    /**
     * @param string $type
     * @param string $fileName
     * @param string $extension
     * @return Common_Model_File
     */
    public static function createFile(string $type, string $fileName, string $extension): Common_Model_File {
        $file = new Common_Model_File();
        $file->Type = $type;
        $file->Name = $fileName;
        $file->Extension = $extension;
        $file->save();

        return $file;
    }

    /**
     * @param $ID
     * @return self
     */
    public static function getFile($ID): Common_Model_File {
        $query = Doctrine_Query::create();
        $query->from('Common_Model_File object');
        $query->where('object.ID = ?', $ID);

        /** @var  \Common_Model_File $file */
        return $query->fetchOne();
    }
}