<?php

/**
 * Common_Model_Language
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Common_Model_Language extends Common_Model_Base_Language {

    const LANGUAGE_CZ = 'cz';
    const LANGUAGE_SK = 'sk';

    const ID_LANGUAGE_CZ = 1;
    const ID_LANGUAGE_SK = 2;

    /**
     * @return array|Doctrine_Collection|Doctrine_Collection_OnDemand|int
     */
    public static function getActiveLanguages(): int|array|Doctrine_Collection_OnDemand|Doctrine_Collection {
        $query = Doctrine_Query::create();
        $query->from('Common_Model_Language object');

        return $query->execute();
    }

    /**
     * @param bool $onlyActive
     * @return array|null
     */
    public static function getLanguages(bool $onlyActive = false): ?array {
        $query = Doctrine_Query::create();
        $query->from('Common_Model_Language object');
        $query->select('object.*');

        if ($onlyActive)
            $query->where('object.Active = ?', true);

        return $query->execute([], Doctrine_Core::HYDRATE_ARRAY);
    }

    /**
     * @param int $ID
     * @return self|null|false
     */
    public static function getLanguage(int $ID): Common_Model_Language|bool|null {
        $query = Doctrine_Query::create();
        $query->from('Common_Model_Language object');
        $query->where('object.ID = ?');

        return $query->fetchOne([$ID]);
    }

    /**
     * @param string $code
     * @return Common_Model_Language|null|boolean
     */
    public static function getLanguageByCode(string $code): Common_Model_Language|bool|null {
        $query = Doctrine_Query::create();
        $query->from('Common_Model_Language object');
        $query->select('object.*');
        $query->where('object.Active = ?', true);
        $query->andWhere('object.Code = ?', $code);

        return $query->fetchOne([], Doctrine_Core::HYDRATE_ARRAY);
    }

    /**
     * Zkopíruje Jazyk
     * @param self $newLang
     * @param int $copyFrom_ID Kopírovat z
     */
    public static function copyTranslations(self $newLang, int $copyFrom_ID) {
        if (!$copyFrom_ID || !($copyFrom = self::getLanguage($copyFrom_ID)))
            throw new Exception('Jazyk nenalezen');

        if ($newLang->Code != 'CZ') {
            $translationsDir = '../data/translation/';
            if (file_exists($translationsDir . strtolower($copyFrom->Code) . '.po'))
                copy($translationsDir . strtolower($copyFrom->Code) . '.po', $translationsDir . strtolower($newLang->Code) . '.po');
            else
                file_put_contents($translationsDir . strtolower($newLang->Code) . '.po', '');
        }

        // Věci k zkopírování
        $toCopy = ['couponLangs', 'productLangs', 'categoryLangs', 'parameterLangs', 'orderStateTypeLangs', 'countryZoneLangs', 'countryLang'];
        foreach ($toCopy as $cpy) {
            foreach ($copyFrom->{$cpy} as $cpyEntity) {
                $tmp = $cpyEntity->copy(true);
                $tmp->Language_ID = $newLang->ID;
                if (!empty($cpyEntity->slug))
                    $tmp->slug = null;

                $tmp->save();
                unset($tmp);
            }
        }
    }
}