<?php

/**
 * Admin_Model_Base_Announcement
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ID
 * @property integer $Eshop_ID
 * @property string $Hash
 * @property string $Type
 * @property string $Content
 * @property boolean $Active
 * @property date $DateFrom
 * @property date $DateTo
 * @property boolean $InEmail
 * @property Common_Model_Eshop $eshop
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Admin_Model_Base_Announcement extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('admin__model__announcement');
        $this->hasColumn('ID', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('Eshop_ID', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('Hash', 'string', 32, array(
             'type' => 'string',
             'length' => '32',
             ));
        $this->hasColumn('Type', 'string', 16, array(
             'type' => 'string',
             'length' => '16',
             ));
        $this->hasColumn('Content', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('Active', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('DateFrom', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('DateTo', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('InEmail', 'boolean', null, array(
             'type' => 'boolean',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Common_Model_Eshop as eshop', array(
             'local' => 'Eshop_ID',
             'foreign' => 'ID'));
    }
}