<?php

/**
 * Admin_Model_Base_Attribute
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ID
 * @property string $Name
 * @property string $Description
 * @property Doctrine_Collection $productChildrenAttribute
 * @property Doctrine_Collection $values
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Admin_Model_Base_Attribute extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('admin__model__attribute');
        $this->hasColumn('ID', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('Name', 'string', 64, array(
             'type' => 'string',
             'length' => '64',
             ));
        $this->hasColumn('Description', 'string', null, array(
             'type' => 'string',
             ));
    }

    public function setUp()
    {
        parent::setUp();

        $this->hasMany('Admin_Model_AttributeValue as values', array(
             'local' => 'ID',
             'foreign' => 'Attribute_ID'));
    }
}