<?php

/**
 * Admin_Model_Base_BalikobotState
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ID
 * @property integer $BalikobotPackage_ID
 * @property date $Date
 * @property time $Time
 * @property string $State
 * @property string $Message
 * @property string $StatusID
 * @property Admin_Model_BalikobotPackage $balikobotPackage
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Admin_Model_Base_BalikobotState extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('admin__model__balikobot_state');
        $this->hasColumn('ID', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('BalikobotPackage_ID', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('Date', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('Time', 'time', null, array(
             'type' => 'time',
             ));
        $this->hasColumn('State', 'string', 128, array(
             'type' => 'string',
             'length' => '128',
             ));
        $this->hasColumn('Message', 'string', 512, array(
             'type' => 'string',
             'length' => '512',
             ));
        $this->hasColumn('StatusID', 'string', 16, array(
             'type' => 'string',
             'length' => '16',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Admin_Model_BalikobotPackage as balikobotPackage', array(
             'local' => 'BalikobotPackage_ID',
             'foreign' => 'ID'));
    }
}