<?php

/**
 * Admin_Model_Base_Banner
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ID
 * @property integer $Eshop_ID
 * @property integer $File_ID
 * @property boolean $Active
 * @property string $Headline
 * @property string $Description
 * @property string $Url
 * @property integer $Rank
 * @property string $Subline
 * @property string $LinkBtnText
 * @property string $Template
 * @property Common_Model_File $file
 * @property Common_Model_Eshop $eshop
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Admin_Model_Base_Banner extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('admin__model__banner');
        $this->hasColumn('ID', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('Eshop_ID', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('File_ID', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('Active', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('Headline', 'string', 256, array(
             'type' => 'string',
             'length' => '256',
             ));
        $this->hasColumn('Description', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('Url', 'string', 512, array(
             'type' => 'string',
             'length' => '512',
             ));
        $this->hasColumn('Rank', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('Subline', 'string', 256, array(
             'type' => 'string',
             'length' => '256',
             ));
        $this->hasColumn('LinkBtnText', 'string', 128, array(
             'type' => 'string',
             'length' => '128',
             ));
        $this->hasColumn('Template', 'string', 128, array(
             'type' => 'string',
             'length' => '128',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Common_Model_File as file', array(
             'local' => 'File_ID',
             'foreign' => 'ID'));

        $this->hasOne('Common_Model_Eshop as eshop', array(
             'local' => 'Eshop_ID',
             'foreign' => 'ID'));
    }
}