<?php

/**
 * Admin_Model_Base_CartLog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ID
 * @property integer $Product_ID
 * @property integer $User_ID
 * @property integer $Quantity
 * @property date $Date
 * @property time $Time
 * @property string $IPAddress
 * @property Admin_Model_Product $product
 * @property User_Model_User $user
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Admin_Model_Base_CartLog extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('admin__model__cart_log');
        $this->hasColumn('ID', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('Product_ID', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('User_ID', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('Quantity', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('Date', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('Time', 'time', null, array(
             'type' => 'time',
             ));
        $this->hasColumn('IPAddress', 'string', 64, array(
             'type' => 'string',
             'length' => '64',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Admin_Model_Product as product', array(
             'local' => 'Product_ID',
             'foreign' => 'ID'));

        $this->hasOne('User_Model_User as user', array(
             'local' => 'User_ID',
             'foreign' => 'ID'));
    }
}