<?php

/**
 * Admin_Model_Base_Category
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ID
 * @property integer $File_ID
 * @property integer $Category_ID
 * @property integer $API_ID
 * @property string $Code
 * @property boolean $IsAvailable
 * @property timestamp $DateTimeUpdated
 * @property timestamp $DateTimeCreated
 * @property boolean $Archived
 * @property Admin_Model_Category $category
 * @property Common_Model_File $file
 * @property Doctrine_Collection $categoryLangs
 * @property Doctrine_Collection $categoryEshops
 * @property Doctrine_Collection $products
 * @property Doctrine_Collection $categories
 * @property Doctrine_Collection $categoryMetas
 * @property Doctrine_Collection $categoryAttachments
 * @property Doctrine_Collection $categorySlugHistories
 * @property Doctrine_Collection $shippingCategories
 * @property Doctrine_Collection $shippingCategoryBlacklists
 * @property Doctrine_Collection $shippingCategoryWhitelists
 * @property Doctrine_Collection $groupDiscounts
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Admin_Model_Base_Category extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('admin__model__category');
        $this->hasColumn('ID', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('File_ID', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('Category_ID', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('API_ID', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('Code', 'string', 64, array(
             'type' => 'string',
             'length' => '64',
             ));
        $this->hasColumn('IsAvailable', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('DateTimeUpdated', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('DateTimeCreated', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('Archived', 'boolean', null, array(
             'type' => 'boolean',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Admin_Model_Category as category', array(
             'local' => 'Category_ID',
             'foreign' => 'ID'));

        $this->hasOne('Common_Model_File as file', array(
             'local' => 'File_ID',
             'foreign' => 'ID'));

        $this->hasMany('Admin_Model_CategoryLang as categoryLangs', array(
             'local' => 'ID',
             'foreign' => 'Category_ID',
             'cascade' => array(
             0 => 'delete',
             )));

        $this->hasMany('Admin_Model_CategoryEshop as categoryEshops', array(
             'local' => 'ID',
             'foreign' => 'Category_ID',
             'cascade' => array(
             0 => 'delete',
             )));

        $this->hasMany('Admin_Model_ProductInCategory as products', array(
             'local' => 'ID',
             'foreign' => 'Category_ID'));

        $this->hasMany('Admin_Model_Category as categories', array(
             'local' => 'ID',
             'foreign' => 'Category_ID'));

        $this->hasMany('Admin_Model_CategoryMeta as categoryMetas', array(
             'local' => 'ID',
             'foreign' => 'Category_ID'));

        $this->hasMany('Admin_Model_CategoryAttachment as categoryAttachments', array(
             'local' => 'ID',
             'foreign' => 'Category_ID'));

        $this->hasMany('Admin_Model_CategorySlugHistory as categorySlugHistories', array(
             'local' => 'ID',
             'foreign' => 'Category_ID'));

        $this->hasMany('Admin_Model_ShippingCategory as shippingCategories', array(
             'local' => 'ID',
             'foreign' => 'Category_ID'));

        $this->hasMany('Admin_Model_ShippingCategoryBlacklist as shippingCategoryBlacklists', array(
             'local' => 'ID',
             'foreign' => 'Category_ID'));

        $this->hasMany('Admin_Model_ShippingCategoryWhitelist as shippingCategoryWhitelists', array(
             'local' => 'ID',
             'foreign' => 'Category_ID'));

        $this->hasMany('User_Model_GroupDiscount as groupDiscounts', array(
             'local' => 'ID',
             'foreign' => 'Category_ID'));

        $clevis_behavior_hierarchy0 = new Clevis_Behavior_Hierarchy(array(
             'ColumnChildren' => 'CategoryIDs',
             'ColumnParent' => 'Category_ID',
             ));
        $this->actAs($clevis_behavior_hierarchy0);
    }
}