<?php

/**
 * Admin_Model_Base_CategoryEshop
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ID
 * @property integer $Category_ID
 * @property integer $Eshop_ID
 * @property integer $Rank
 * @property boolean $Active
 * @property Admin_Model_Category $category
 * @property Common_Model_Eshop $eshop
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Admin_Model_Base_CategoryEshop extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('admin__model__category_eshop');
        $this->hasColumn('ID', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('Category_ID', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('Eshop_ID', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('Rank', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('Active', 'boolean', null, array(
             'type' => 'boolean',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Admin_Model_Category as category', array(
             'local' => 'Category_ID',
             'foreign' => 'ID'));

        $this->hasOne('Common_Model_Eshop as eshop', array(
             'local' => 'Eshop_ID',
             'foreign' => 'ID'));
    }
}