<?php

/**
 * Admin_Model_Base_Complaint
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ID
 * @property integer $DeliveryCountry_ID
 * @property integer $InvoiceCountry_ID
 * @property string $Name
 * @property string $Email
 * @property string $Phone
 * @property string $IC
 * @property string $DIC
 * @property string $CompanyName
 * @property string $InvoiceStreet
 * @property string $InvoiceCity
 * @property string $InvoiceZipCode
 * @property string $DeliveryName
 * @property string $DeliveryStreet
 * @property string $DeliveryZipCode
 * @property string $Package
 * @property string $DeliveryCity
 * @property timestamp $DateCreated
 * @property Common_Model_Country $invoiceCountry
 * @property Common_Model_Country $deliveryCountry
 * @property Doctrine_Collection $complaintItems
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Admin_Model_Base_Complaint extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('admin__model__complaint');
        $this->hasColumn('ID', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('DeliveryCountry_ID', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('InvoiceCountry_ID', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('Name', 'string', 128, array(
             'type' => 'string',
             'length' => '128',
             ));
        $this->hasColumn('Email', 'string', 128, array(
             'type' => 'string',
             'length' => '128',
             ));
        $this->hasColumn('Phone', 'string', 128, array(
             'type' => 'string',
             'length' => '128',
             ));
        $this->hasColumn('IC', 'string', 32, array(
             'type' => 'string',
             'length' => '32',
             ));
        $this->hasColumn('DIC', 'string', 32, array(
             'type' => 'string',
             'length' => '32',
             ));
        $this->hasColumn('CompanyName', 'string', 256, array(
             'type' => 'string',
             'length' => '256',
             ));
        $this->hasColumn('InvoiceStreet', 'string', 128, array(
             'type' => 'string',
             'length' => '128',
             ));
        $this->hasColumn('InvoiceCity', 'string', 128, array(
             'type' => 'string',
             'length' => '128',
             ));
        $this->hasColumn('InvoiceZipCode', 'string', 16, array(
             'type' => 'string',
             'length' => '16',
             ));
        $this->hasColumn('DeliveryName', 'string', 128, array(
             'type' => 'string',
             'length' => '128',
             ));
        $this->hasColumn('DeliveryStreet', 'string', 128, array(
             'type' => 'string',
             'length' => '128',
             ));
        $this->hasColumn('DeliveryZipCode', 'string', 16, array(
             'type' => 'string',
             'length' => '16',
             ));
        $this->hasColumn('Package', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('DeliveryCity', 'string', 128, array(
             'type' => 'string',
             'length' => '128',
             ));
        $this->hasColumn('DateCreated', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Common_Model_Country as invoiceCountry', array(
             'local' => 'InvoiceCountry_ID',
             'foreign' => 'ID'));

        $this->hasOne('Common_Model_Country as deliveryCountry', array(
             'local' => 'DeliveryCountry_ID',
             'foreign' => 'ID'));

        $this->hasMany('Admin_Model_ComplaintItem as complaintItems', array(
             'local' => 'ID',
             'foreign' => 'Complaint_ID'));
    }
}