<?php

/**
 * Admin_Model_Base_ComplaintItem
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ID
 * @property integer $Complaint_ID
 * @property string $InvoiceNumber
 * @property string $ProductNumber
 * @property integer $Amount
 * @property string $Description
 * @property Admin_Model_Complaint $complaint
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Admin_Model_Base_ComplaintItem extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('admin__model__complaint_item');
        $this->hasColumn('ID', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('Complaint_ID', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('InvoiceNumber', 'string', 64, array(
             'type' => 'string',
             'length' => '64',
             ));
        $this->hasColumn('ProductNumber', 'string', 64, array(
             'type' => 'string',
             'length' => '64',
             ));
        $this->hasColumn('Amount', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('Description', 'string', null, array(
             'type' => 'string',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Admin_Model_Complaint as complaint', array(
             'local' => 'Complaint_ID',
             'foreign' => 'ID'));
    }
}