<?php

/**
 * Admin_Model_Base_CsobPaymentState
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ID
 * @property integer $CsobPayment_ID
 * @property integer $OrderStateType_ID
 * @property date $Date
 * @property time $Time
 * @property Admin_Model_CsobPayment $csobPayment
 * @property Admin_Model_OrderStateType $orderStateType
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Admin_Model_Base_CsobPaymentState extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('admin__model__csob_payment_state');
        $this->hasColumn('ID', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('CsobPayment_ID', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('OrderStateType_ID', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('Date', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('Time', 'time', null, array(
             'type' => 'time',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Admin_Model_CsobPayment as csobPayment', array(
             'local' => 'CsobPayment_ID',
             'foreign' => 'ID'));

        $this->hasOne('Admin_Model_OrderStateType as orderStateType', array(
             'local' => 'OrderStateType_ID',
             'foreign' => 'ID'));
    }
}