<?php

/**
 * Admin_Model_Base_CsobPayment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ID
 * @property integer $Order_ID
 * @property date $Date
 * @property time $Time
 * @property string $CsobID
 * @property string $CsobURL
 * @property Admin_Model_Order $order
 * @property Doctrine_Collection $csobPaymentStates
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Admin_Model_Base_CsobPayment extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('admin__model__csob_payment');
        $this->hasColumn('ID', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('Order_ID', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('Date', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('Time', 'time', null, array(
             'type' => 'time',
             ));
        $this->hasColumn('CsobID', 'string', 256, array(
             'type' => 'string',
             'length' => '256',
             ));
        $this->hasColumn('CsobURL', 'string', null, array(
             'type' => 'string',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Admin_Model_Order as order', array(
             'local' => 'Order_ID',
             'foreign' => 'ID'));

        $this->hasMany('Admin_Model_CsobPaymentState as csobPaymentStates', array(
             'local' => 'ID',
             'foreign' => 'CsobPayment_ID'));
    }
}