<?php

/**
 * Admin_Model_Base_Currency
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ID
 * @property string $Name
 * @property float $Ratio
 * @property string $Label
 * @property string $Mark
 * @property Doctrine_Collection $productEshops
 * @property Doctrine_Collection $orders
 * @property Doctrine_Collection $userSettings
 * @property Doctrine_Collection $eshops
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Admin_Model_Base_Currency extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('admin__model__currency');
        $this->hasColumn('ID', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('Name', 'string', 64, array(
             'type' => 'string',
             'length' => '64',
             ));
        $this->hasColumn('Ratio', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('Label', 'string', 16, array(
             'type' => 'string',
             'length' => '16',
             ));
        $this->hasColumn('Mark', 'string', 16, array(
             'type' => 'string',
             'length' => '16',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Admin_Model_ProductEshop as productEshops', array(
             'local' => 'ID',
             'foreign' => 'Currency_ID'));

        $this->hasMany('Admin_Model_Order as orders', array(
             'local' => 'ID',
             'foreign' => 'Currency_ID'));

        $this->hasMany('User_Model_UserSettings as userSettings', array(
             'local' => 'ID',
             'foreign' => 'Currency_ID'));

        $this->hasMany('Common_Model_Eshop as eshops', array(
             'local' => 'ID',
             'foreign' => 'Currency_ID'));
    }
}