<?php

/**
 * Admin_Model_Base_CustomMeal
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ID
 * @property string $Name
 * @property string $Type
 * @property integer $Fat
 * @property integer $Carbs
 * @property integer $Protein
 * @property integer $Sugar
 * @property integer $Kcal
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Admin_Model_Base_CustomMeal extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('admin__model__custom_meal');
        $this->hasColumn('ID', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('Name', 'string', 256, array(
             'type' => 'string',
             'length' => '256',
             ));
        $this->hasColumn('Type', 'string', 64, array(
             'type' => 'string',
             'length' => '64',
             ));
        $this->hasColumn('Fat', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('Carbs', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('Protein', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('Sugar', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('Kcal', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}