<?php

/**
 * Admin_Model_Base_DaySleep
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ID
 * @property integer $Day_ID
 * @property integer $User_ID
 * @property integer $Hours
 * @property time $StartTime
 * @property time $FinishTime
 * @property Admin_Model_Day $day
 * @property User_Model_User $user
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Admin_Model_Base_DaySleep extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('admin__model__day_sleep');
        $this->hasColumn('ID', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('Day_ID', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('User_ID', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('Hours', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('StartTime', 'time', null, array(
             'type' => 'time',
             ));
        $this->hasColumn('FinishTime', 'time', null, array(
             'type' => 'time',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Admin_Model_Day as day', array(
             'local' => 'Day_ID',
             'foreign' => 'ID'));

        $this->hasOne('User_Model_User as user', array(
             'local' => 'User_ID',
             'foreign' => 'ID'));
    }
}