<?php

/**
 * Admin_Model_Base_Feedback
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ID
 * @property integer $CreatorUser_ID
 * @property integer $SolverUser_ID
 * @property integer $Eshop_ID
 * @property integer $Project_ID
 * @property string $Header
 * @property timestamp $DateTime
 * @property string $Content
 * @property string $Priority
 * @property date $DateExpectedSolving
 * @property date $DateSolved
 * @property string $tmpState
 * @property string $FeedbackNumber
 * @property string $Hash
 * @property boolean $ErrorReporting
 * @property date $DateStartSolving
 * @property decimal $WorkedTimePrivate
 * @property decimal $WorkedTimePublic
 * @property string $ScriptCodeContent
 * @property User_Model_User $creatorUser
 * @property User_Model_User $solverUser
 * @property Common_Model_Eshop $eshop
 * @property Admin_Model_Project $project
 * @property Doctrine_Collection $feedbackStates
 * @property Doctrine_Collection $feedbackFiles
 * @property Doctrine_Collection $feedbackReadLastStates
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Admin_Model_Base_Feedback extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('admin__model__feedback');
        $this->hasColumn('ID', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('CreatorUser_ID', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('SolverUser_ID', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('Eshop_ID', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('Project_ID', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('Header', 'string', 256, array(
             'type' => 'string',
             'length' => '256',
             ));
        $this->hasColumn('DateTime', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('Content', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('Priority', 'string', 32, array(
             'type' => 'string',
             'length' => '32',
             ));
        $this->hasColumn('DateExpectedSolving', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('DateSolved', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('tmpState', 'string', 32, array(
             'type' => 'string',
             'length' => '32',
             ));
        $this->hasColumn('FeedbackNumber', 'string', 32, array(
             'type' => 'string',
             'length' => '32',
             ));
        $this->hasColumn('Hash', 'string', 32, array(
             'type' => 'string',
             'length' => '32',
             ));
        $this->hasColumn('ErrorReporting', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('DateStartSolving', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('WorkedTimePrivate', 'decimal', null, array(
             'type' => 'decimal',
             ));
        $this->hasColumn('WorkedTimePublic', 'decimal', null, array(
             'type' => 'decimal',
             ));
        $this->hasColumn('ScriptCodeContent', 'string', null, array(
             'type' => 'string',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('User_Model_User as creatorUser', array(
             'local' => 'CreatorUser_ID',
             'foreign' => 'ID'));

        $this->hasOne('User_Model_User as solverUser', array(
             'local' => 'SolverUser_ID',
             'foreign' => 'ID'));

        $this->hasOne('Common_Model_Eshop as eshop', array(
             'local' => 'Eshop_ID',
             'foreign' => 'ID'));

        $this->hasOne('Admin_Model_Project as project', array(
             'local' => 'Project_ID',
             'foreign' => 'ID'));

        $this->hasMany('Admin_Model_FeedbackState as feedbackStates', array(
             'local' => 'ID',
             'foreign' => 'Feedback_ID'));

        $this->hasMany('Admin_Model_FeedbackFile as feedbackFiles', array(
             'local' => 'ID',
             'foreign' => 'Feedback_ID'));

        $this->hasMany('Admin_Model_FeedbackReadLastState as feedbackReadLastStates', array(
             'local' => 'ID',
             'foreign' => 'Feedback_ID'));
    }
}