<?php

/**
 * Admin_Model_Base_GopayPayment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ID
 * @property integer $Order_ID
 * @property date $Date
 * @property time $Time
 * @property integer $GopayID
 * @property string $GopayURL
 * @property Admin_Model_Order $order
 * @property Doctrine_Collection $gopayPaymentStates
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Admin_Model_Base_GopayPayment extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('admin__model__gopay_payment');
        $this->hasColumn('ID', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('Order_ID', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('Date', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('Time', 'time', null, array(
             'type' => 'time',
             ));
        $this->hasColumn('GopayID', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('GopayURL', 'string', 512, array(
             'type' => 'string',
             'length' => '512',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Admin_Model_Order as order', array(
             'local' => 'Order_ID',
             'foreign' => 'ID'));

        $this->hasMany('Admin_Model_GopayPaymentState as gopayPaymentStates', array(
             'local' => 'ID',
             'foreign' => 'GopayPayment_ID',
             'cascade' => array(
             0 => 'delete',
             )));
    }
}