<?php

/**
 * Admin_Model_Base_Instagram
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ID
 * @property string $Name
 * @property string $AccessToken
 * @property Doctrine_Collection $instagramMedia
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Admin_Model_Base_Instagram extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('admin__model__instagram');
        $this->hasColumn('ID', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('Name', 'string', 128, array(
             'type' => 'string',
             'length' => '128',
             ));
        $this->hasColumn('AccessToken', 'string', null, array(
             'type' => 'string',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Admin_Model_InstagramMedia as instagramMedia', array(
             'local' => 'ID',
             'foreign' => 'Instagram_ID'));
    }
}