<?php

/**
 * Admin_Model_Base_NewsletterSubscriber
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ID
 * @property integer $Eshop_ID
 * @property date $Date
 * @property time $Time
 * @property string $Subscriber
 * @property boolean $Active
 * @property Common_Model_Eshop $eshop
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Admin_Model_Base_NewsletterSubscriber extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('admin__model__newsletter_subscriber');
        $this->hasColumn('ID', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('Eshop_ID', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('Date', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('Time', 'time', null, array(
             'type' => 'time',
             ));
        $this->hasColumn('Subscriber', 'string', 128, array(
             'type' => 'string',
             'length' => '128',
             ));
        $this->hasColumn('Active', 'boolean', null, array(
             'type' => 'boolean',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Common_Model_Eshop as eshop', array(
             'local' => 'Eshop_ID',
             'foreign' => 'ID'));
    }
}