<?php

/**
 * Admin_Model_Base_News
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ID
 * @property integer $NewsCategory_ID
 * @property integer $Eshop_ID
 * @property integer $File_ID
 * @property date $Date
 * @property boolean $Active
 * @property string $Perex
 * @property string $Content
 * @property string $Headline
 * @property integer $ReadingTime
 * @property Common_Model_File $file
 * @property Common_Model_Eshop $eshop
 * @property Admin_Model_NewsCategory $newsCategory
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Admin_Model_Base_News extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('admin__model__news');
        $this->hasColumn('ID', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('NewsCategory_ID', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('Eshop_ID', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('File_ID', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('Date', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('Active', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('Perex', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('Content', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('Headline', 'string', 256, array(
             'type' => 'string',
             'length' => '256',
             ));
        $this->hasColumn('ReadingTime', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Common_Model_File as file', array(
             'local' => 'File_ID',
             'foreign' => 'ID'));

        $this->hasOne('Common_Model_Eshop as eshop', array(
             'local' => 'Eshop_ID',
             'foreign' => 'ID'));

        $this->hasOne('Admin_Model_NewsCategory as newsCategory', array(
             'local' => 'NewsCategory_ID',
             'foreign' => 'ID'));

        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'unique' => true,
             'fields' => 
             array(
              0 => 'Headline',
             ),
             'canUpdate' => false,
             ));
        $this->actAs($sluggable0);
    }
}