<?php

/**
 * Admin_Model_Base_OrderStateType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ID
 * @property boolean $SendEmail
 * @property string $Color
 * @property Doctrine_Collection $orders
 * @property Doctrine_Collection $orderStates
 * @property Doctrine_Collection $orderStateTypeLangs
 * @property Doctrine_Collection $gopayPaymentState
 * @property Doctrine_Collection $csobPaymentStates
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Admin_Model_Base_OrderStateType extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('admin__model__order_state_type');
        $this->hasColumn('ID', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('SendEmail', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('Color', 'string', 32, array(
             'type' => 'string',
             'length' => '32',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Admin_Model_Order as orders', array(
             'local' => 'ID',
             'foreign' => 'OrderStateType_ID'));

        $this->hasMany('Admin_Model_OrderState as orderStates', array(
             'local' => 'ID',
             'foreign' => 'OrderStateType_ID'));

        $this->hasMany('Admin_Model_OrderStateTypeLang as orderStateTypeLangs', array(
             'local' => 'ID',
             'foreign' => 'OrderStateType_ID'));

        $this->hasMany('Admin_Model_GopayPaymentState as gopayPaymentState', array(
             'local' => 'ID',
             'foreign' => 'OrderStateType_ID'));

        $this->hasMany('Admin_Model_CsobPaymentState as csobPaymentStates', array(
             'local' => 'ID',
             'foreign' => 'OrderStateType_ID'));
    }
}