<?php

/**
 * Admin_Model_Base_Page
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ID
 * @property integer $Page_ID
 * @property Admin_Model_Page $page
 * @property Doctrine_Collection $pageLangs
 * @property Doctrine_Collection $pageEshops
 * @property Doctrine_Collection $pages
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Admin_Model_Base_Page extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('admin__model__page');
        $this->hasColumn('ID', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('Page_ID', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Admin_Model_Page as page', array(
             'local' => 'Page_ID',
             'foreign' => 'ID'));

        $this->hasMany('Admin_Model_PageLang as pageLangs', array(
             'local' => 'ID',
             'foreign' => 'Page_ID',
             'cascade' => array(
             0 => 'delete',
             )));

        $this->hasMany('Admin_Model_PageEshop as pageEshops', array(
             'local' => 'ID',
             'foreign' => 'Page_ID',
             'cascade' => array(
             0 => 'delete',
             )));

        $this->hasMany('Admin_Model_Page as pages', array(
             'local' => 'ID',
             'foreign' => 'Page_ID'));
    }
}