<?php

/**
 * Admin_Model_Base_PageLang
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ID
 * @property integer $Language_ID
 * @property integer $Page_ID
 * @property string $Name
 * @property string $Content
 * @property string $Title
 * @property string $MetaDescription
 * @property string $MetaKeywords
 * @property Admin_Model_Page $page
 * @property Common_Model_Language $language
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Admin_Model_Base_PageLang extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('admin__model__page_lang');
        $this->hasColumn('ID', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('Language_ID', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('Page_ID', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('Name', 'string', 64, array(
             'type' => 'string',
             'length' => '64',
             ));
        $this->hasColumn('Content', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('Title', 'string', 256, array(
             'type' => 'string',
             'length' => '256',
             ));
        $this->hasColumn('MetaDescription', 'string', 512, array(
             'type' => 'string',
             'length' => '512',
             ));
        $this->hasColumn('MetaKeywords', 'string', 256, array(
             'type' => 'string',
             'length' => '256',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Admin_Model_Page as page', array(
             'local' => 'Page_ID',
             'foreign' => 'ID'));

        $this->hasOne('Common_Model_Language as language', array(
             'local' => 'Language_ID',
             'foreign' => 'ID'));

        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'canUpdate' => false,
             'fields' => 
             array(
              0 => 'Name',
             ),
             'unique' => true,
             ));
        $this->actAs($sluggable0);
    }
}