<?php

/**
 * Admin_Model_Base_ParameterLang
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ID
 * @property integer $Language_ID
 * @property integer $Parameter_ID
 * @property string $Name
 * @property Admin_Model_Parameter $parameter
 * @property Common_Model_Language $language
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Admin_Model_Base_ParameterLang extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('admin__model__parameter_lang');
        $this->hasColumn('ID', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('Language_ID', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('Parameter_ID', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('Name', 'string', 128, array(
             'type' => 'string',
             'length' => '128',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Admin_Model_Parameter as parameter', array(
             'local' => 'Parameter_ID',
             'foreign' => 'ID'));

        $this->hasOne('Common_Model_Language as language', array(
             'local' => 'Language_ID',
             'foreign' => 'ID'));
    }
}