<?php

/**
 * Admin_Model_Base_ParameterValue
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ID
 * @property integer $Parameter_ID
 * @property string $Value
 * @property string $Additional
 * @property Admin_Model_Parameter $parameter
 * @property Doctrine_Collection $productParameters
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Admin_Model_Base_ParameterValue extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('admin__model__parameter_value');
        $this->hasColumn('ID', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('Parameter_ID', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('Value', 'string', 128, array(
             'type' => 'string',
             'length' => '128',
             ));
        $this->hasColumn('Additional', 'string', 128, array(
             'type' => 'string',
             'length' => '128',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Admin_Model_Parameter as parameter', array(
             'local' => 'Parameter_ID',
             'foreign' => 'ID'));

        $this->hasMany('Admin_Model_ProductParameter as productParameters', array(
             'local' => 'ID',
             'foreign' => 'ParameterValue_ID'));
    }
}