<?php

/**
 * Admin_Model_Base_PopupLang
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ID
 * @property integer $Popup_ID
 * @property string $Header
 * @property string $Content
 * @property Admin_Model_Popup $popup
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Admin_Model_Base_PopupLang extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('admin__model__popup_lang');
        $this->hasColumn('ID', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('Popup_ID', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('Header', 'string', 128, array(
             'type' => 'string',
             'length' => '128',
             ));
        $this->hasColumn('Content', 'string', null, array(
             'type' => 'string',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Admin_Model_Popup as popup', array(
             'local' => 'Popup_ID',
             'foreign' => 'ID'));
    }
}