<?php

/**
 * Admin_Model_Base_ProductLang
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ID
 * @property integer $Product_ID
 * @property integer $Language_ID
 * @property string $Name
 * @property string $Description
 * @property string $ShortDescription
 * @property string $SearchName
 * @property string $Title
 * @property string $MetaDescription
 * @property string $MetaKeywords
 * @property string $InfoText
 * @property string $CustomAvailabilityInfo
 * @property string $Perex
 * @property Admin_Model_Product $product
 * @property Common_Model_Language $language
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Admin_Model_Base_ProductLang extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('admin__model__product_lang');
        $this->hasColumn('ID', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('Product_ID', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('Language_ID', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('Name', 'string', 128, array(
             'type' => 'string',
             'length' => '128',
             ));
        $this->hasColumn('Description', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('ShortDescription', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('SearchName', 'string', 256, array(
             'type' => 'string',
             'length' => '256',
             ));
        $this->hasColumn('Title', 'string', 256, array(
             'type' => 'string',
             'length' => '256',
             ));
        $this->hasColumn('MetaDescription', 'string', 256, array(
             'type' => 'string',
             'length' => '256',
             ));
        $this->hasColumn('MetaKeywords', 'string', 256, array(
             'type' => 'string',
             'length' => '256',
             ));
        $this->hasColumn('InfoText', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('CustomAvailabilityInfo', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('Perex', 'string', null, array(
             'type' => 'string',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Admin_Model_Product as product', array(
             'local' => 'Product_ID',
             'foreign' => 'ID'));

        $this->hasOne('Common_Model_Language as language', array(
             'local' => 'Language_ID',
             'foreign' => 'ID'));

        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'canUpdate' => true,
             'unique' => true,
             'fields' => 
             array(
              0 => 'Name',
             ),
             ));
        $this->actAs($sluggable0);
    }
}