<?php

/**
 * Admin_Model_Base_ProductRelated
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ID
 * @property integer $Product_ID
 * @property integer $ProductRelated_ID
 * @property string $LinkType
 * @property Admin_Model_Product $product
 * @property Admin_Model_Product $productRelated
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Admin_Model_Base_ProductRelated extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('admin__model__product_related');
        $this->hasColumn('ID', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('Product_ID', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('ProductRelated_ID', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('LinkType', 'string', 64, array(
             'type' => 'string',
             'length' => '64',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Admin_Model_Product as product', array(
             'local' => 'Product_ID',
             'foreign' => 'ID'));

        $this->hasOne('Admin_Model_Product as productRelated', array(
             'local' => 'ProductRelated_ID',
             'foreign' => 'ID'));
    }
}