<?php

/**
 * Admin_Model_Base_ProductPrice
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ID
 * @property integer $Product_ID
 * @property decimal $Price
 * @property integer $QuantityFrom
 * @property integer $QuantityTo
 * @property Admin_Model_Product $product
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Admin_Model_Base_ProductPrice extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('admin__model__product_price');
        $this->hasColumn('ID', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('Product_ID', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('Price', 'decimal', null, array(
             'type' => 'decimal',
             ));
        $this->hasColumn('QuantityFrom', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('QuantityTo', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Admin_Model_Product as product', array(
             'local' => 'Product_ID',
             'foreign' => 'ID'));
    }
}