<?php

/**
 * Admin_Model_Base_ProductAttachment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ID
 * @property integer $Product_ID
 * @property integer $File_ID
 * @property string $UrlPath
 * @property string $Hash
 * @property string $Alt
 * @property timestamp $DateTimeCreated
 * @property timestamp $DateTimeUpdated
 * @property string $AttachmentType
 * @property timestamp $DateTimeLastSynchronized
 * @property Admin_Model_Product $product
 * @property Common_Model_File $file
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Admin_Model_Base_ProductAttachment extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('admin__model__product_attachment');
        $this->hasColumn('ID', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('Product_ID', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('File_ID', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('UrlPath', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('Hash', 'string', 64, array(
             'type' => 'string',
             'length' => '64',
             ));
        $this->hasColumn('Alt', 'string', 256, array(
             'type' => 'string',
             'length' => '256',
             ));
        $this->hasColumn('DateTimeCreated', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('DateTimeUpdated', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('AttachmentType', 'string', 64, array(
             'type' => 'string',
             'length' => '64',
             ));
        $this->hasColumn('DateTimeLastSynchronized', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Admin_Model_Product as product', array(
             'local' => 'Product_ID',
             'foreign' => 'ID'));

        $this->hasOne('Common_Model_File as file', array(
             'local' => 'File_ID',
             'foreign' => 'ID'));
    }
}