<?php

/**
 * Admin_Model_Base_Product
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ID
 * @property integer $Manufacturer_ID
 * @property string $Video
 * @property integer $OnStock
 * @property string $Code
 * @property integer $Viewed
 * @property date $CreatedDate
 * @property string $EAN
 * @property boolean $FlagNews
 * @property boolean $FlagClearanceSale
 * @property decimal $Weight
 * @property string $PohodaStock
 * @property integer $API_ID
 * @property timestamp $UpdateDateTime
 * @property integer $OnExternalStock
 * @property boolean $IsAvailable
 * @property boolean $Archived
 * @property Admin_Model_Manufacturer $manufacturer
 * @property Doctrine_Collection $productSimiliars
 * @property Doctrine_Collection $Admin_Model_ProductSimiliar
 * @property Doctrine_Collection $parameters
 * @property Doctrine_Collection $productImages
 * @property Doctrine_Collection $categories
 * @property Doctrine_Collection $productLangs
 * @property Doctrine_Collection $productEshops
 * @property Doctrine_Collection $productRelateds
 * @property Doctrine_Collection $Admin_Model_ProductRelated
 * @property Doctrine_Collection $productDocumments
 * @property Doctrine_Collection $productDescriptionAccordions
 * @property Doctrine_Collection $wishLists
 * @property Doctrine_Collection $productsOnHomepage
 * @property Doctrine_Collection $productMetas
 * @property Doctrine_Collection $productStocks
 * @property Doctrine_Collection $productAttachments
 * @property Doctrine_Collection $productWatchDogs
 * @property Doctrine_Collection $productSlugHistories
 * @property Doctrine_Collection $questions
 * @property Doctrine_Collection $cart
 * @property Doctrine_Collection $orderItem
 * @property Doctrine_Collection $coupons
 * @property Doctrine_Collection $cartLogs
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Admin_Model_Base_Product extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('admin__model__product');
        $this->hasColumn('ID', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('Manufacturer_ID', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('Video', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('OnStock', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('Code', 'string', 128, array(
             'type' => 'string',
             'length' => '128',
             ));
        $this->hasColumn('Viewed', 'integer', null, array(
             'default' => 0,
             'type' => 'integer',
             ));
        $this->hasColumn('CreatedDate', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('EAN', 'string', 64, array(
             'type' => 'string',
             'length' => '64',
             ));
        $this->hasColumn('FlagNews', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('FlagClearanceSale', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('Weight', 'decimal', null, array(
             'type' => 'decimal',
             ));
        $this->hasColumn('PohodaStock', 'string', 16, array(
             'type' => 'string',
             'length' => '16',
             ));
        $this->hasColumn('API_ID', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('UpdateDateTime', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('OnExternalStock', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('IsAvailable', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('Archived', 'boolean', null, array(
             'type' => 'boolean',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Admin_Model_Manufacturer as manufacturer', array(
             'local' => 'Manufacturer_ID',
             'foreign' => 'ID'));

        $this->hasMany('Admin_Model_ProductSimiliar as productSimiliars', array(
             'local' => 'ID',
             'foreign' => 'Product_ID',
             'cascade' => array(
             0 => 'delete',
             )));

        $this->hasMany('Admin_Model_ProductSimiliar', array(
             'local' => 'ID',
             'foreign' => 'ProductSimiliar_ID',
             'cascade' => array(
             0 => 'delete',
             )));

        $this->hasMany('Admin_Model_ProductParameter as parameters', array(
             'local' => 'ID',
             'foreign' => 'Product_ID',
             'cascade' => array(
             0 => 'delete',
             )));

        $this->hasMany('Admin_Model_ProductImage as productImages', array(
             'local' => 'ID',
             'foreign' => 'Product_ID',
             'cascade' => array(
             0 => 'delete',
             )));

        $this->hasMany('Admin_Model_ProductInCategory as categories', array(
             'local' => 'ID',
             'foreign' => 'Product_ID',
             'cascade' => array(
             0 => 'delete',
             )));

        $this->hasMany('Admin_Model_ProductLang as productLangs', array(
             'local' => 'ID',
             'foreign' => 'Product_ID',
             'cascade' => array(
             0 => 'delete',
             )));

        $this->hasMany('Admin_Model_ProductEshop as productEshops', array(
             'local' => 'ID',
             'foreign' => 'Product_ID',
             'cascade' => array(
             0 => 'delete',
             )));

        $this->hasMany('Admin_Model_ProductRelated as productRelateds', array(
             'local' => 'ID',
             'foreign' => 'Product_ID'));

        $this->hasMany('Admin_Model_ProductRelated', array(
             'local' => 'ID',
             'foreign' => 'ProductRelated_ID'));

        $this->hasMany('Admin_Model_ProductDocumment as productDocumments', array(
             'local' => 'ID',
             'foreign' => 'Product_ID'));

        $this->hasMany('Admin_Model_ProductDescriptionAccordion as productDescriptionAccordions', array(
             'local' => 'ID',
             'foreign' => 'Product_ID'));

        $this->hasMany('Admin_Model_WishList as wishLists', array(
             'local' => 'ID',
             'foreign' => 'Product_ID'));

        $this->hasMany('Admin_Model_ProductOnHomepage as productsOnHomepage', array(
             'local' => 'ID',
             'foreign' => 'Product_ID'));

        $this->hasMany('Admin_Model_ProductMeta as productMetas', array(
             'local' => 'ID',
             'foreign' => 'Product_ID'));

        $this->hasMany('Admin_Model_ProductStock as productStocks', array(
             'local' => 'ID',
             'foreign' => 'Product_ID'));

        $this->hasMany('Admin_Model_ProductAttachment as productAttachments', array(
             'local' => 'ID',
             'foreign' => 'Product_ID'));

        $this->hasMany('Admin_Model_ProductWatchDog as productWatchDogs', array(
             'local' => 'ID',
             'foreign' => 'Product_ID'));

        $this->hasMany('Admin_Model_ProductSlugHistory as productSlugHistories', array(
             'local' => 'ID',
             'foreign' => 'Product_ID'));

        $this->hasMany('Admin_Model_Question as questions', array(
             'local' => 'ID',
             'foreign' => 'Product_ID'));

        $this->hasMany('Admin_Model_Cart as cart', array(
             'local' => 'ID',
             'foreign' => 'Product_ID'));

        $this->hasMany('Admin_Model_OrderItem as orderItem', array(
             'local' => 'ID',
             'foreign' => 'Product_ID'));

        $this->hasMany('Admin_Model_Coupon as coupons', array(
             'local' => 'ID',
             'foreign' => 'Product_ID'));

        $this->hasMany('Admin_Model_CartLog as cartLogs', array(
             'local' => 'ID',
             'foreign' => 'Product_ID'));
    }
}