<?php

/**
 * Admin_Model_Base_ProductStock
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ID
 * @property integer $Product_ID
 * @property integer $Stock_ID
 * @property string $Code
 * @property integer $Quantity
 * @property string $Note
 * @property Admin_Model_Product $product
 * @property Admin_Model_Stock $stock
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Admin_Model_Base_ProductStock extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('admin__model__product_stock');
        $this->hasColumn('ID', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('Product_ID', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('Stock_ID', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('Code', 'string', 256, array(
             'type' => 'string',
             'length' => '256',
             ));
        $this->hasColumn('Quantity', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('Note', 'string', 128, array(
             'type' => 'string',
             'length' => '128',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Admin_Model_Product as product', array(
             'local' => 'Product_ID',
             'foreign' => 'ID'));

        $this->hasOne('Admin_Model_Stock as stock', array(
             'local' => 'Stock_ID',
             'foreign' => 'ID'));
    }
}