<?php

/**
 * Admin_Model_Base_ProductImage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ID
 * @property integer $Product_ID
 * @property integer $File_ID
 * @property string $Description
 * @property boolean $Main
 * @property integer $Rank
 * @property Common_Model_File $file
 * @property Admin_Model_Product $product
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Admin_Model_Base_ProductImage extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('admin__model__product_image');
        $this->hasColumn('ID', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('Product_ID', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('File_ID', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('Description', 'string', 256, array(
             'type' => 'string',
             'length' => '256',
             ));
        $this->hasColumn('Main', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('Rank', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Common_Model_File as file', array(
             'local' => 'File_ID',
             'foreign' => 'ID'));

        $this->hasOne('Admin_Model_Product as product', array(
             'local' => 'Product_ID',
             'foreign' => 'ID'));
    }
}