<?php

/**
 * Admin_Model_Base_Project
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ID
 * @property integer $DefaultSolver_ID
 * @property string $Name
 * @property string $Www
 * @property string $Description
 * @property User_Model_User $defaultSolver
 * @property Doctrine_Collection $feedbacks
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Admin_Model_Base_Project extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('admin__model__project');
        $this->hasColumn('ID', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('DefaultSolver_ID', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('Name', 'string', 64, array(
             'type' => 'string',
             'length' => '64',
             ));
        $this->hasColumn('Www', 'string', 64, array(
             'type' => 'string',
             'length' => '64',
             ));
        $this->hasColumn('Description', 'string', null, array(
             'type' => 'string',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('User_Model_User as defaultSolver', array(
             'local' => 'DefaultSolver_ID',
             'foreign' => 'ID'));

        $this->hasMany('Admin_Model_Feedback as feedbacks', array(
             'local' => 'ID',
             'foreign' => 'Project_ID'));
    }
}