<?php

/**
 * Admin_Model_Base_SearchLog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ID
 * @property integer $Eshop_ID
 * @property integer $User_ID
 * @property date $Date
 * @property time $Time
 * @property string $SearchTerm
 * @property User_Model_User $user
 * @property Common_Model_Eshop $eshop
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Admin_Model_Base_SearchLog extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('admin__model__search_log');
        $this->hasColumn('ID', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('Eshop_ID', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('User_ID', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('Date', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('Time', 'time', null, array(
             'type' => 'time',
             ));
        $this->hasColumn('SearchTerm', 'string', 128, array(
             'type' => 'string',
             'length' => '128',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('User_Model_User as user', array(
             'local' => 'User_ID',
             'foreign' => 'ID'));

        $this->hasOne('Common_Model_Eshop as eshop', array(
             'local' => 'Eshop_ID',
             'foreign' => 'ID'));
    }
}