<?php

/**
 * Admin_Model_Base_Shipping
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ID
 * @property integer $Eshop_ID
 * @property integer $File_ID
 * @property integer $Vat_ID
 * @property boolean $Active
 * @property decimal $Price
 * @property string $VatType
 * @property decimal $FreeShipping
 * @property string $Type
 * @property string $Name
 * @property string $Description
 * @property string $PohodaCode
 * @property integer $ExternalID
 * @property string $Code
 * @property integer $Rank
 * @property Admin_Model_Vat $vat
 * @property Common_Model_Eshop $eshop
 * @property Common_Model_File $file
 * @property Doctrine_Collection $order
 * @property Doctrine_Collection $shippingPayments
 * @property Doctrine_Collection $shippingCategories
 * @property Doctrine_Collection $shippingCategoryBlacklists
 * @property Doctrine_Collection $shippingCategoryWhitelists
 * @property Doctrine_Collection $shippingPrices
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Admin_Model_Base_Shipping extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('admin__model__shipping');
        $this->hasColumn('ID', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('Eshop_ID', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('File_ID', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('Vat_ID', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('Active', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('Price', 'decimal', null, array(
             'type' => 'decimal',
             ));
        $this->hasColumn('VatType', 'string', 32, array(
             'type' => 'string',
             'length' => '32',
             ));
        $this->hasColumn('FreeShipping', 'decimal', null, array(
             'type' => 'decimal',
             ));
        $this->hasColumn('Type', 'string', 16, array(
             'type' => 'string',
             'length' => '16',
             ));
        $this->hasColumn('Name', 'string', 128, array(
             'type' => 'string',
             'length' => '128',
             ));
        $this->hasColumn('Description', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('PohodaCode', 'string', 128, array(
             'type' => 'string',
             'length' => '128',
             ));
        $this->hasColumn('ExternalID', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('Code', 'string', 128, array(
             'type' => 'string',
             'length' => '128',
             ));
        $this->hasColumn('Rank', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Admin_Model_Vat as vat', array(
             'local' => 'Vat_ID',
             'foreign' => 'ID'));

        $this->hasOne('Common_Model_Eshop as eshop', array(
             'local' => 'Eshop_ID',
             'foreign' => 'ID'));

        $this->hasOne('Common_Model_File as file', array(
             'local' => 'File_ID',
             'foreign' => 'ID'));

        $this->hasMany('Admin_Model_Order as order', array(
             'local' => 'ID',
             'foreign' => 'Shipping_ID'));

        $this->hasMany('Admin_Model_ShippingPayment as shippingPayments', array(
             'local' => 'ID',
             'foreign' => 'Shipping_ID'));

        $this->hasMany('Admin_Model_ShippingCategory as shippingCategories', array(
             'local' => 'ID',
             'foreign' => 'Shipping_ID'));

        $this->hasMany('Admin_Model_ShippingCategoryBlacklist as shippingCategoryBlacklists', array(
             'local' => 'ID',
             'foreign' => 'Shipping_ID'));

        $this->hasMany('Admin_Model_ShippingCategoryWhitelist as shippingCategoryWhitelists', array(
             'local' => 'ID',
             'foreign' => 'Shipping_ID'));

        $this->hasMany('Admin_Model_ShippingPrice as shippingPrices', array(
             'local' => 'ID',
             'foreign' => 'Shipping_ID'));
    }
}