<?php

/**
 * Admin_Model_Base_ShippingPayment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ID
 * @property integer $Shipping_ID
 * @property integer $Payment_ID
 * @property Admin_Model_Shipping $shipping
 * @property Admin_Model_Payment $payment
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Admin_Model_Base_ShippingPayment extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('admin__model__shipping_payment');
        $this->hasColumn('ID', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('Shipping_ID', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('Payment_ID', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Admin_Model_Shipping as shipping', array(
             'local' => 'Shipping_ID',
             'foreign' => 'ID'));

        $this->hasOne('Admin_Model_Payment as payment', array(
             'local' => 'Payment_ID',
             'foreign' => 'ID'));
    }
}