<?php

/**
 * Admin_Model_Base_ShippingPrice
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ID
 * @property integer $Shipping_ID
 * @property float $MaxWeight
 * @property float $MaxWidth
 * @property float $MaxDepth
 * @property float $MaxHeight
 * @property decimal $PriceWithoutVat
 * @property string $Note
 * @property Admin_Model_Shipping $shipping
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Admin_Model_Base_ShippingPrice extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('admin__model__shipping_price');
        $this->hasColumn('ID', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('Shipping_ID', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('MaxWeight', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('MaxWidth', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('MaxDepth', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('MaxHeight', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('PriceWithoutVat', 'decimal', null, array(
             'type' => 'decimal',
             ));
        $this->hasColumn('Note', 'string', null, array(
             'type' => 'string',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Admin_Model_Shipping as shipping', array(
             'local' => 'Shipping_ID',
             'foreign' => 'ID'));
    }
}