<?php

/**
 * Admin_Model_Base_ShippingCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ID
 * @property integer $Category_ID
 * @property integer $Shipping_ID
 * @property integer $Vat_ID
 * @property decimal $Price
 * @property string $VatType
 * @property boolean $PricePerPiece
 * @property boolean $PriceAlways
 * @property Admin_Model_Shipping $shipping
 * @property Admin_Model_Category $category
 * @property Admin_Model_Vat $vat
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Admin_Model_Base_ShippingCategory extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('admin__model__shipping_category');
        $this->hasColumn('ID', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('Category_ID', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('Shipping_ID', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('Vat_ID', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('Price', 'decimal', null, array(
             'type' => 'decimal',
             ));
        $this->hasColumn('VatType', 'string', 32, array(
             'type' => 'string',
             'length' => '32',
             ));
        $this->hasColumn('PricePerPiece', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('PriceAlways', 'boolean', null, array(
             'type' => 'boolean',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Admin_Model_Shipping as shipping', array(
             'local' => 'Shipping_ID',
             'foreign' => 'ID'));

        $this->hasOne('Admin_Model_Category as category', array(
             'local' => 'Category_ID',
             'foreign' => 'ID'));

        $this->hasOne('Admin_Model_Vat as vat', array(
             'local' => 'Vat_ID',
             'foreign' => 'ID'));
    }
}