<?php

/**
 * Admin_Model_Base_ShippingCategoryBlacklist
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ID
 * @property integer $Shipping_ID
 * @property integer $Category_ID
 * @property Admin_Model_Shipping $shipping
 * @property Admin_Model_Category $category
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Admin_Model_Base_ShippingCategoryBlacklist extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('admin__model__shipping_category_blacklist');
        $this->hasColumn('ID', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('Shipping_ID', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('Category_ID', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Admin_Model_Shipping as shipping', array(
             'local' => 'Shipping_ID',
             'foreign' => 'ID'));

        $this->hasOne('Admin_Model_Category as category', array(
             'local' => 'Category_ID',
             'foreign' => 'ID'));
    }
}