<?php

/**
 * Admin_Model_Base_Zasilkovna
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ID
 * @property integer $PickupPlace_ID
 * @property string $PickupPlaceName
 * @property string $PickupPlaceAddress
 * @property Doctrine_Collection $orders
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Admin_Model_Base_Zasilkovna extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('admin__model__zasilkovna');
        $this->hasColumn('ID', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('PickupPlace_ID', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('PickupPlaceName', 'string', 256, array(
             'type' => 'string',
             'length' => '256',
             ));
        $this->hasColumn('PickupPlaceAddress', 'string', null, array(
             'type' => 'string',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Admin_Model_Order as orders', array(
             'local' => 'ID',
             'foreign' => 'Zasilkovna_ID'));
    }
}