<?php

/**
 * User_Model_Base_Group
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ID
 * @property string $Name
 * @property Doctrine_Collection $groupDiscounts
 * @property Doctrine_Collection $userSettings
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class User_Model_Base_Group extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('user__model__group');
        $this->hasColumn('ID', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('Name', 'string', 128, array(
             'type' => 'string',
             'length' => '128',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('User_Model_GroupDiscount as groupDiscounts', array(
             'local' => 'ID',
             'foreign' => 'Group_ID',
             'cascade' => array(
             0 => 'delete',
             )));

        $this->hasMany('User_Model_UserSettings as userSettings', array(
             'local' => 'ID',
             'foreign' => 'Group_ID'));
    }
}