<?php

/**
 * User_Model_Base_OldUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ID
 * @property string $Code
 * @property blob $IsAdmin
 * @property string $LoginName
 * @property string $Password
 * @property boolean $Transfered
 * @property string $ContactPerson
 * @property string $ContactPhone
 * @property string $ContactEmail
 * @property string $CompanyName
 * @property string $CompanyStreet
 * @property string $CompanyCity
 * @property string $CompanyZipCode
 * @property string $CompanyCountry
 * @property string $CompanyID
 * @property string $CompanyVatID
 * @property string $DeliveryName
 * @property string $DeliveryStreet
 * @property string $DeliveryCity
 * @property string $DeliveryZipCode
 * @property string $DeliveryCountry
 * @property string $Currency
 * @property string $Lang
 * @property string $PaymentAvailability
 * @property string $PriceType
 * @property decimal $Discount
 * @property boolean $State
 * @property boolean $Newsletter
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class User_Model_Base_OldUser extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('user__model__old_user');
        $this->hasColumn('ID', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('Code', 'string', 64, array(
             'type' => 'string',
             'length' => '64',
             ));
        $this->hasColumn('IsAdmin', 'blob', null, array(
             'type' => 'blob',
             ));
        $this->hasColumn('LoginName', 'string', 256, array(
             'type' => 'string',
             'length' => '256',
             ));
        $this->hasColumn('Password', 'string', 2056, array(
             'type' => 'string',
             'length' => '2056',
             ));
        $this->hasColumn('Transfered', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('ContactPerson', 'string', 128, array(
             'type' => 'string',
             'length' => '128',
             ));
        $this->hasColumn('ContactPhone', 'string', 64, array(
             'type' => 'string',
             'length' => '64',
             ));
        $this->hasColumn('ContactEmail', 'string', 256, array(
             'type' => 'string',
             'length' => '256',
             ));
        $this->hasColumn('CompanyName', 'string', 256, array(
             'type' => 'string',
             'length' => '256',
             ));
        $this->hasColumn('CompanyStreet', 'string', 256, array(
             'type' => 'string',
             'length' => '256',
             ));
        $this->hasColumn('CompanyCity', 'string', 256, array(
             'type' => 'string',
             'length' => '256',
             ));
        $this->hasColumn('CompanyZipCode', 'string', 16, array(
             'type' => 'string',
             'length' => '16',
             ));
        $this->hasColumn('CompanyCountry', 'string', 64, array(
             'type' => 'string',
             'length' => '64',
             ));
        $this->hasColumn('CompanyID', 'string', 32, array(
             'type' => 'string',
             'length' => '32',
             ));
        $this->hasColumn('CompanyVatID', 'string', 32, array(
             'type' => 'string',
             'length' => '32',
             ));
        $this->hasColumn('DeliveryName', 'string', 256, array(
             'type' => 'string',
             'length' => '256',
             ));
        $this->hasColumn('DeliveryStreet', 'string', 256, array(
             'type' => 'string',
             'length' => '256',
             ));
        $this->hasColumn('DeliveryCity', 'string', 128, array(
             'type' => 'string',
             'length' => '128',
             ));
        $this->hasColumn('DeliveryZipCode', 'string', 16, array(
             'type' => 'string',
             'length' => '16',
             ));
        $this->hasColumn('DeliveryCountry', 'string', 64, array(
             'type' => 'string',
             'length' => '64',
             ));
        $this->hasColumn('Currency', 'string', 64, array(
             'type' => 'string',
             'length' => '64',
             ));
        $this->hasColumn('Lang', 'string', 16, array(
             'type' => 'string',
             'length' => '16',
             ));
        $this->hasColumn('PaymentAvailability', 'string', 32, array(
             'type' => 'string',
             'length' => '32',
             ));
        $this->hasColumn('PriceType', 'string', 16, array(
             'type' => 'string',
             'length' => '16',
             ));
        $this->hasColumn('Discount', 'decimal', null, array(
             'type' => 'decimal',
             ));
        $this->hasColumn('State', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('Newsletter', 'boolean', null, array(
             'type' => 'boolean',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}