<?php

/**
 * User_Model_Base_UserHasPermission
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ID
 * @property integer $Permission_ID
 * @property integer $User_ID
 * @property User_Model_User $user
 * @property User_Model_Permission $permission
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class User_Model_Base_UserHasPermission extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('user__model__user_has_permission');
        $this->hasColumn('ID', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('Permission_ID', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('User_ID', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('User_Model_User as user', array(
             'local' => 'User_ID',
             'foreign' => 'ID'));

        $this->hasOne('User_Model_Permission as permission', array(
             'local' => 'Permission_ID',
             'foreign' => 'ID'));
    }
}