<?php

/**
 * User_Model_GroupDiscount
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class User_Model_GroupDiscount extends User_Model_Base_GroupDiscount {

    /**
     * @param int $groupID
     * @return array
     */
    public static function getGroupDiscounts(int $groupID): array {
        $query = Doctrine_Query::create();
        $query->from('User_Model_GroupDiscount object');
        $query->where('object.Group_ID = ?', $groupID);

        $groupDiscounts = [];
        foreach ( $query->execute()->toArray() as $gd )
            $groupDiscounts[$gd['Category_ID']] = $gd['Discount'];

        return $groupDiscounts;
    }
}