<?php

/**
 * User_Model_OldUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class User_Model_OldUser extends User_Model_Base_OldUser
{

    public static function oldUserExists(string $login, string $externalID): bool {
        $query = Doctrine_Query::create();
        $query->from("User_Model_OldUser object");
        $query->where("object.LoginName = ?", $login);
        $query->addWhere("object.Code = ?", $externalID);

        return $query->count() > 0;
    }

    public static function getOldUserByLogin(string $login): User_Model_OldUser|bool {
        $query = Doctrine_Query::create();
        $query->from("User_Model_OldUser object");
        $query->where("object.LoginName = ?", $login);
        $query->addWhere("object.Transfered IS NOT TRUE");

        return $query->fetchOne();
    }

    public static function getOldUserByID(int $oldUserID) {
        $query = Doctrine_Query::create();
        $query->from("User_Model_OldUser object");
        $query->where("object.ID = ?", $oldUserID);

        return $query->fetchOne();
    }
}