<?php
use Admin_Model_Address as Address;
use common\logic\Eshop\Eshop;
use common\logic\Tokenizer;
use Common_Model_Eshop as EshopModel;
use user\logic\UserClientSession;
use User_Model_Permission as PermissionModel;

/**
 * User_Model_User
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class User_Model_User extends User_Model_Base_User {

    const TYPE_SUPERADMIN = 'superadmin';
    const TYPE_ADMIN = 'admin';
    const TYPE_API_USER = 'api-user';
    const TYPE_CUSTOMER = 'customer';

    /**
     * @param Doctrine_Connection|null $conn
     */
    public function save(Doctrine_Connection $conn = null) {
        if($this->ID === null) {
            $this->Active = true;
            $this->DateTimeCreated = date('Y-m-d H:i:s');
            $this->RegistrationDate = date('Y-m-d');
        }
        $this->DateTimeUpdated = date('Y-m-d H:i:s');
        parent::save($conn);

    }

    /**
     * Get user by Email
     *
     * @param string|null $email
     * @param int|null $userID
     * @return array
     */
    public static function getUserByEmail(?string $email = null, int $userID = null): array {

        $query = Doctrine_Query::create();
        $query->from("User_Model_User object");
        $query->where("object.Name = ?", $email);

        if ( $userID )
            $query->addWhere("object.ID != ?", $userID);

        return $query->execute()->toArray();
    }

    /**
     * Get user by Email
     *
     * @param string|null $email
     * @return array
     */
    public static function getUserByEmailForLogin(?string $email = null): self|bool {
        $eshop = Eshop::getInstance()->getEshop();

        $query = Doctrine_Query::create();
        $query->from("User_Model_User object");
        $query->where("object.Name = ?", $email);
        $query->andWhere('object.Active = ?', true);

        if ( $eshop )
            $query->addWhere("object.Eshop_ID = ?", $eshop->ID);

        return $query->fetchOne();
    }

    /**
     * @return string
     */
    public static function generateSalt(): string {
        return substr( str_pad( dechex( mt_rand() ), 8, '0', STR_PAD_LEFT ), -8);
    }

    /**
     * @param string $password
     * @return string
     */
    public static function buildHash(string $password): string {
        return password_hash($password, PASSWORD_BCRYPT);
    }

    /**
     * @param string $email
     * @param string $password
     * @param string $type
     * @param Address|null $invoiceAddress
     * @param Address|null $deliveryAddress
     * @param int|null $eshopID
     * @return self
     */
    public static function createUser(string $email, string $password, string $type, int $eshopID = null, string $externalID = null, array $options=[]): self {
        $userSettings = new User_Model_UserSettings();
        $userSettings->save();

        $user = new User_Model_User();
        $user->UserSettings_ID = $userSettings->ID;
        $user->Name = $email;
        $user->Salt = self::generateSalt();
        $user->Hash = self::buildHash($password);
        $user->Type = $type;
        $user->RegistrationDate = date("Y-m-d");
        if ($externalID)
            $user->ExternalID = $externalID;
        if ( $eshopID )
            $user->Eshop_ID = $eshopID;
        $user->save();
        
        return $user;
    }

    /**
     * @param array $user
     * @param string $password
     * @param string $salt
     */
    public static function changePassword(array $user, string $password, string $salt) {
        $query = Doctrine_Query::create();
        $query->update('User_Model_User');
        $query->set('Salt', '?', $salt);
        $query->set('Hash', '?', self::buildHash($password));
        $query->where("ID = ?", $user[0]["ID"]);
        $query->execute();
    }

    /**
     * @return User_Model_User|null
     */
    public static function getCurrentUser() : ?User_Model_User {
        $query = Doctrine_Query::create();
        $query->from('User_Model_User object');
        $query->where('object.ID = ?', UserClientSession::getCurrentUserID());

        $user = $query->fetchOne();

        return $user ?: null;
    }

    /**
     * Get user by value (Name, ID, ...)
     *
     * @param mixed $value
     * @param string $column
     * @return bool|self
     */
    public static function getUser(mixed $value, string $column = 'ID'): bool|self {
        $query = Doctrine_Query::create();
        $query->from('User_Model_User object');
        $query->where('object.' . $column . ' = ?', $value);

        return $query->fetchOne();
    }

    /**
     * Get all types
     *
     * @param bool $showAll
     * @return string[]
     */
    public static function getUserTypes(bool $showAll = false): array {
        $types = [];
        $types[self::TYPE_SUPERADMIN] = 'Super administrátor';
        $types[self::TYPE_ADMIN] = 'Administrátor';
        $types[self::TYPE_API_USER] = 'Api uživatel';

        return array_merge($types,[
            self::TYPE_CUSTOMER => 'zákazník',
        ]);
    }

    /**
     * Get admin types
     *
     * @param bool $onlyKeys
     * @return string[]
     */
    public static function getAdminTypes(bool $onlyKeys = false): array {
        $types = [
            self::TYPE_SUPERADMIN => 'superadmin',
            self::TYPE_ADMIN => 'admin',
        ];

        return $onlyKeys?array_keys($types):$types;
    }

    /**
     * Get admin types
     *
     * @param bool $onlyKeys
     * @return string[]
     */
    public static function getApiUserTypes(bool $onlyKeys = false): array {
        $types = [
            self::TYPE_API_USER => 'api-user'
        ];

        return $onlyKeys?array_keys($types):$types;
    }

    /**
     * @param string|null $userType
     * @return int
     */
    public static function getUsersCount(?string $userType = null): int {
        $query = Doctrine_Query::create();
        $query->from('User_Model_User object');
        $query->andWhere('object.Active = ?', true);
        if ( $userType )
            $query->andWhere('object.Type = ?', $userType);

        return $query->count();
    }

    /**
     * @param null $searchTerm
     * @param null $limit
     * @return array
     */
    public static function getSearchUsers($searchTerm = null, $limit = null): array {
        $query = Doctrine_Query::create();
        $query->from('User_Model_User object');
        $query->leftJoin('object.invoiceAddress invoiceAddress');
        $query->orWhere('invoiceAddress.FirstName LIKE ?', '%' . $searchTerm . '%');
        $query->orWhere('invoiceAddress.LastName LIKE ?', '%' . $searchTerm . '%');
        $query->orWhere('invoiceAddress.CompanyName LIKE ?', '%' . $searchTerm . '%');
        $query->orWhere('object.Name LIKE ?', '%' . $searchTerm . '%');

        if ( $limit != null )
            $query->limit($limit);

        return $query->execute()->toArray();
    }

    /**
     * @param string $searchTerm
     * @return int
     */
    public static function getSearchUsersCount(string $searchTerm): int {
        $query = Doctrine_Query::create();
        $query->from('User_Model_User object');
        $query->leftJoin('object.invoiceAddress invoiceAddress');
        $query->orWhere('invoiceAddress.FirstName LIKE ?', '%' . $searchTerm . '%');
        $query->orWhere('invoiceAddress.LastName LIKE ?', '%' . $searchTerm . '%');
        $query->orWhere('invoiceAddress.CompanyName LIKE ?', '%' . $searchTerm . '%');
        $query->orWhere('object.Name LIKE ?', '%' . $searchTerm . '%');

        return $query->count();
    }

    /**
     * @param string $userName
     * @return array|bool
     */
    public static function getUserForAdminLogin(string $userName): array|bool {
        $query = Doctrine_Query::create();
        $query->from('User_Model_User user');
        $query->where('user.Name = ?', $userName);
        $query->addWhere('user.Active = ?', true);
        $query->addWhere('user.Type IN ("' . implode('","', self::getAdminTypes()) . '")');
        $query->having('COUNT(user.userEshops.ID) OR user.Type = ?', self::TYPE_SUPERADMIN);

        return $query->fetchOne([], Doctrine_Core::HYDRATE_ARRAY);
    }


    /**
     * @param string $userName
     * @return array|bool
     */
    public static function getUserForApiLogin(string $userName): self|bool {
        $query = Doctrine_Query::create();
        $query->from('User_Model_User user');
        $query->where('user.Name = ?', $userName);
        $query->addWhere('user.Active = ?', true);
        $query->addWhere('user.Type IN ("' . implode('","', self::getApiUserTypes()) . '")');
        $query->having('COUNT(user.userEshops.ID) OR user.Type = ?', self::TYPE_API_USER);

        return $query->fetchOne();
    }

    public static function getAllUserEmails(int $EshopID): array {
        $query = Doctrine_Query::create();
        $query->from('User_Model_User user');
        $query->leftJoin('user.invoiceAddress invoiceAddress');
        $query->addWhere('user.Active = ?', true);
        $query->addWhere('user.Eshop_ID = ?', $EshopID);
        $query->addGroupBy('user.ID');
        $customerData = $query->execute([], Doctrine_Core::HYDRATE_ARRAY);
        $result = [];
        $index = 0;

        foreach ($customerData as &$data) {
            $result[$index] = $data['invoiceAddress']['Email'] ?? '';
            $index++;
        }
        return $result;
    }

    /**
     * Has permission?
     *
     * @param string $Code
     * @return bool
     */
    public function hasPermission(string $Code): bool {
        $perms = $this->userHasPermissions;
        $permission = PermissionModel::getPermissionByCode($Code, true);

        if ($this->Type === self::TYPE_SUPERADMIN)
            return true;

        foreach ($perms as $perm) {
            if ($perm->Permission_ID == $permission->ID)
                return true;
        }

        return false;
    }

    /**
     * @param int $userID
     * @param string $code
     * @return bool
     */
    public static function userHasPermission(int $userID, string $code): bool {
        $user = self::getUser($userID);
        if (!$user)
            return false;

        return $user->hasPermission($code);
    }

    public static function getUsersByFilter(?int $customerID, mixed $filter, mixed $changedSince): array|int|Doctrine_Collection_OnDemand|Doctrine_Collection {
        $query = Doctrine_Query::create();
        $query->from('User_Model_User object');
        if($customerID) {
            $query->addWhere('object.ID = ?', $customerID);
        }
        if($filter) {
            //ToDO: nevím, jestli vůbec se tady bude využivat
        }

        if($changedSince) {
            $query->addWhere('object.DateTimeUpdated >= ?', $changedSince);
        }

        return $query->execute();
    }

    public static function getUserByExternalID(string $externalId) {
        $query = Doctrine_Query::create();
        $query->from('User_Model_User object');
        $query->where('object.ExternalID = ?', $externalId);

        return $query->fetchOne();
    }

    public static function getUserByCode(string $customerCode) {
        $query = Doctrine_Query::create();
        $query->from('User_Model_User object');
        $query->where('object.Code = ?', $customerCode);

        return $query->fetchOne();
    }

        /**
         * @throws Doctrine_Query_Exception
         * @throws Exception
         */
        public static function confirmUserRegistration(string $token): self | bool
        {
            try {
                $parsedTokenData = Tokenizer::parseToken($token);
                $user = self::getUser($parsedTokenData['ID']);
                if (!$user || $user->Name !== $parsedTokenData['Name']) {
                    throw new Exception('Invalid token data');
                }
                $user->Active = true;
                $user->save();
                return $user;
            } catch (Exception $e) {
                throw new Exception($e->getMessage());
            }
        }


    /**
     * @return bool
     */
    public function isSuperadmin(): bool {
        return $this->Type === self::TYPE_SUPERADMIN;
    }
}