<?php
use \user\logic\UserAdminSession;

/**
 * User_Model_UserHasPermission
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class User_Model_UserHasPermission extends User_Model_Base_UserHasPermission {

    /**
     * @param Doctrine_Connection|null $conn
     */
    public function save(Doctrine_Connection $conn = null) {
        parent::save($conn);

        UserAdminSession::refreshPermissions();
    }

    /**
     * @param Doctrine_Connection|null $conn
     * @return bool
     */
    public function delete(Doctrine_Connection $conn = null): bool {
        $deleted = parent::delete($conn);

        UserAdminSession::refreshPermissions();

        return $deleted;
    }

    /**
     * @param string|int $userID
     * @return self[]|Doctrine_Collection
     */
    public static function getUserHasPermissions($userID): array|Doctrine_Collection {
        $query = Doctrine_Query::create();
        $query->from('User_Model_UserHasPermission object');
        $query->where('object.User_ID = ?', $userID);

        return $query->execute();
    }

    public static function deleteUserHasPermissions($userID): void {
        self::getUserHasPermissions($userID)->delete();
    }
}