<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version63 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('admin__model__banner', 'admin__model__banner_eshop_id_common__model__eshop_id', array(
             'name' => 'admin__model__banner_eshop_id_common__model__eshop_id',
             'local' => 'eshop_id',
             'foreign' => 'id',
             'foreignTable' => 'common__model__eshop',
             ));
        $this->createForeignKey('admin__model__parameter_lang', 'alci_3', array(
             'name' => 'alci_3',
             'local' => 'language_id',
             'foreign' => 'id',
             'foreignTable' => 'common__model__language',
             ));
        $this->addIndex('admin__model__banner', 'admin__model__banner_eshop_id', array(
             'fields' => 
             array(
              0 => 'eshop_id',
             ),
             ));
        $this->addIndex('admin__model__parameter_lang', 'admin__model__parameter_lang_language_id', array(
             'fields' => 
             array(
              0 => 'language_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('admin__model__banner', 'admin__model__banner_eshop_id_common__model__eshop_id');
        $this->dropForeignKey('admin__model__parameter_lang', 'alci_3');
        $this->removeIndex('admin__model__banner', 'admin__model__banner_eshop_id', array(
             'fields' => 
             array(
              0 => 'eshop_id',
             ),
             ));
        $this->removeIndex('admin__model__parameter_lang', 'admin__model__parameter_lang_language_id', array(
             'fields' => 
             array(
              0 => 'language_id',
             ),
             ));
    }
}