<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddadminModelEmailtext extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('admin__model__email_text', array(
             'id' => 
             array(
              'primary' => true,
              'type' => 'integer',
              'autoincrement' => true,
              'length' => 8,
             ),
             'type' => 
             array(
              'type' => 'string',
              'length' => 64,
             ),
             'header' => 
             array(
              'type' => 'string',
              'length' => 128,
             ),
             'content' => 
             array(
              'type' => 'string',
              'length' => NULL,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('admin__model__email_text');
    }
}