<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdduserModelLoginlog extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('user__model__login_log', array(
             'id' => 
             array(
              'primary' => true,
              'type' => 'integer',
              'autoincrement' => true,
              'length' => 8,
             ),
             'user_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'date' => 
             array(
              'type' => 'date',
              'length' => 25,
             ),
             'time' => 
             array(
              'type' => 'time',
              'length' => 25,
             ),
             'type' => 
             array(
              'type' => 'string',
              'length' => 32,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('user__model__login_log');
    }
}