<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddadminModelBanner extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('admin__model__banner', array(
             'id' => 
             array(
              'primary' => true,
              'type' => 'integer',
              'autoincrement' => true,
              'length' => 8,
             ),
             'file_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'active' => 
             array(
              'type' => 'boolean',
              'length' => 25,
             ),
             'headline' => 
             array(
              'type' => 'string',
              'length' => 256,
             ),
             'description' => 
             array(
              'type' => 'string',
              'length' => NULL,
             ),
             'url' => 
             array(
              'type' => 'string',
              'length' => 512,
             ),
             'rank' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'subline' => 
             array(
              'type' => 'string',
              'length' => 256,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('admin__model__banner');
    }
}