<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddadminModelOrderitem extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('admin__model__order_item', array(
             'id' => 
             array(
              'primary' => true,
              'type' => 'integer',
              'autoincrement' => true,
              'length' => 8,
             ),
             'product_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'order_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'quantity' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'pricewithoutvat' => 
             array(
              'type' => 'decimal',
              'length' => 18,
             ),
             'pricewithvat' => 
             array(
              'type' => 'decimal',
              'length' => 18,
             ),
             'discount' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'vat' => 
             array(
              'type' => 'decimal',
              'length' => 18,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('admin__model__order_item');
    }
}