<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddcommonModelFile extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('common__model__file', array(
             'id' => 
             array(
              'primary' => true,
              'type' => 'integer',
              'autoincrement' => true,
              'length' => 8,
             ),
             'data' => 
             array(
              'type' => 'blob',
              'length' => NULL,
             ),
             'type' => 
             array(
              'type' => 'string',
              'length' => 32,
             ),
             'name' => 
             array(
              'type' => 'string',
              'length' => 256,
             ),
             'extension' => 
             array(
              'type' => 'string',
              'length' => 16,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('common__model__file');
    }
}