<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddadminModelParameter extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('admin__model__parameter', array(
             'id' => 
             array(
              'primary' => true,
              'type' => 'integer',
              'autoincrement' => true,
              'length' => 8,
             ),
             'unit' => 
             array(
              'type' => 'string',
              'length' => 32,
             ),
             'tofilter' => 
             array(
              'type' => 'boolean',
              'length' => 25,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('admin__model__parameter');
    }
}