<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdduserModelUser extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('user__model__user', array(
             'id' => 
             array(
              'primary' => true,
              'type' => 'integer',
              'autoincrement' => true,
              'length' => 8,
             ),
             'invoiceaddress_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'deliveryaddress_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'eshop_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'user_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'usersettings_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'name' => 
             array(
              'type' => 'string',
              'length' => 64,
             ),
             'hash' => 
             array(
              'type' => 'string',
              'length' => 256,
             ),
             'salt' => 
             array(
              'type' => 'string',
              'length' => 256,
             ),
             'type' => 
             array(
              'type' => 'string',
              'length' => 64,
             ),
             'active' => 
             array(
              'type' => 'boolean',
              'length' => 25,
             ),
             'usernumber' => 
             array(
              'type' => 'string',
              'length' => 32,
             ),
             'contactphone' => 
             array(
              'type' => 'string',
              'length' => 32,
             ),
             'contactname' => 
             array(
              'type' => 'string',
              'length' => 64,
             ),
             'contactdescription' => 
             array(
              'type' => 'string',
              'length' => 128,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('user__model__user');
    }
}