<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddadminModelOrder extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('admin__model__order', array(
             'id' => 
             array(
              'primary' => true,
              'type' => 'integer',
              'autoincrement' => true,
              'length' => 8,
             ),
             'currency_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'user_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'invoiceaddress_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'deliveryaddress_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'orderstatetype_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'payment_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'shipping_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'eshop_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'language_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'date' => 
             array(
              'type' => 'date',
              'length' => 25,
             ),
             'time' => 
             array(
              'type' => 'time',
              'length' => 25,
             ),
             'datefinished' => 
             array(
              'type' => 'date',
              'length' => 25,
             ),
             'priceproductwithoutvat' => 
             array(
              'type' => 'decimal',
              'length' => 18,
             ),
             'priceproductwithvat' => 
             array(
              'type' => 'decimal',
              'length' => 18,
             ),
             'pricetotalwithoutvat' => 
             array(
              'type' => 'decimal',
              'length' => 18,
             ),
             'pricetotalwithvat' => 
             array(
              'type' => 'decimal',
              'length' => 18,
             ),
             'ordernumber' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'description' => 
             array(
              'type' => 'string',
              'length' => NULL,
             ),
             'folder' => 
             array(
              'type' => 'string',
              'length' => 32,
             ),
             'priceshippingwithoutvat' => 
             array(
              'type' => 'decimal',
              'length' => 18,
             ),
             'priceshippingwithvat' => 
             array(
              'type' => 'decimal',
              'length' => 18,
             ),
             'pricepaymentwithoutvat' => 
             array(
              'type' => 'decimal',
              'length' => 18,
             ),
             'pricepaymentwithvat' => 
             array(
              'type' => 'decimal',
              'length' => 18,
             ),
             'currencyratio' => 
             array(
              'type' => 'decimal',
              'length' => 18,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('admin__model__order');
    }
}