<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version64 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('admin__model__product', 'discount');
        $this->addColumn('admin__model__product_eshop', 'discount', 'integer', '8', array(
             ));
    }

    public function down()
    {
        $this->addColumn('admin__model__product', 'discount', 'integer', '8', array(
             ));
        $this->removeColumn('admin__model__product_eshop', 'discount');
    }
}