<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddadminModelProduct extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('admin__model__product', array(
             'id' => 
             array(
              'primary' => true,
              'type' => 'integer',
              'autoincrement' => true,
              'length' => 8,
             ),
             'manufacturer_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'video' => 
             array(
              'type' => 'string',
              'length' => NULL,
             ),
             'onstock' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'code' => 
             array(
              'type' => 'string',
              'length' => 128,
             ),
             'discount' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'viewed' => 
             array(
              'default' => 0,
              'type' => 'integer',
              'length' => 8,
             ),
             'createddate' => 
             array(
              'type' => 'date',
              'length' => 25,
             ),
             'ean' => 
             array(
              'type' => 'string',
              'length' => 64,
             ),
             'flagnews' => 
             array(
              'type' => 'boolean',
              'length' => 25,
             ),
             'flagclearancesale' => 
             array(
              'type' => 'boolean',
              'length' => 25,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('admin__model__product');
    }
}