<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddadminModelAttributevalue extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('admin__model__attribute_value', array(
             'id' => 
             array(
              'primary' => true,
              'type' => 'integer',
              'autoincrement' => true,
              'length' => 8,
             ),
             'attribute_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'value' => 
             array(
              'type' => 'string',
              'length' => 256,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('admin__model__attribute_value');
    }
}