<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddcommonModelEshop extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('common__model__eshop', array(
             'id' => 
             array(
              'primary' => true,
              'type' => 'integer',
              'autoincrement' => true,
              'length' => 8,
             ),
             'currency_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'language_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'settings_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'vat_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'filelogo_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'name' => 
             array(
              'type' => 'string',
              'length' => 64,
             ),
             'url' => 
             array(
              'type' => 'string',
              'length' => 64,
             ),
             'active' => 
             array(
              'type' => 'boolean',
              'length' => 25,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('common__model__eshop');
    }
}