<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddadminModelPagelang extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('admin__model__page_lang', array(
             'id' => 
             array(
              'primary' => true,
              'type' => 'integer',
              'autoincrement' => true,
              'length' => 8,
             ),
             'page_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'name' => 
             array(
              'type' => 'string',
              'length' => 64,
             ),
             'content' => 
             array(
              'type' => 'string',
              'length' => NULL,
             ),
             'title' => 
             array(
              'type' => 'string',
              'length' => 256,
             ),
             'metadescription' => 
             array(
              'type' => 'string',
              'length' => 512,
             ),
             'metakeywords' => 
             array(
              'type' => 'string',
              'length' => 256,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('admin__model__page_lang');
    }
}