<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddadminModelProductsimiliar extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('admin__model__product_similiar', array(
             'id' => 
             array(
              'primary' => true,
              'type' => 'integer',
              'autoincrement' => true,
              'length' => 8,
             ),
             'product_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'productsimiliar_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('admin__model__product_similiar');
    }
}