<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddcommonModelCountry extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('common__model__country', array(
             'id' => 
             array(
              'primary' => true,
              'type' => 'integer',
              'autoincrement' => true,
              'length' => 8,
             ),
             'code' => 
             array(
              'type' => 'string',
              'length' => 8,
             ),
             'code2' => 
             array(
              'type' => 'string',
              'length' => 8,
             ),
             'code3' => 
             array(
              'type' => 'string',
              'length' => 8,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('common__model__country');
    }
}