<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddcommonModelLanguage extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('common__model__language', array(
             'id' => 
             array(
              'primary' => true,
              'type' => 'integer',
              'autoincrement' => true,
              'length' => 8,
             ),
             'name' => 
             array(
              'type' => 'string',
              'length' => 64,
             ),
             'code' => 
             array(
              'type' => 'string',
              'length' => 32,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('common__model__language');
    }
}