<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddcommonModelSettings extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('common__model__settings', array(
             'id' => 
             array(
              'primary' => true,
              'type' => 'integer',
              'autoincrement' => true,
              'length' => 8,
             ),
             'contactfax' => 
             array(
              'type' => 'string',
              'length' => 64,
             ),
             'contactemail' => 
             array(
              'type' => 'string',
              'length' => 64,
             ),
             'contactname' => 
             array(
              'type' => 'string',
              'length' => 64,
             ),
             'contactphone' => 
             array(
              'type' => 'string',
              'length' => 64,
             ),
             'contactperson' => 
             array(
              'type' => 'string',
              'length' => 128,
             ),
             'projecturl' => 
             array(
              'type' => 'string',
              'length' => 64,
             ),
             'analyticscode' => 
             array(
              'type' => 'string',
              'length' => 64,
             ),
             'facebookurl' => 
             array(
              'type' => 'string',
              'length' => 128,
             ),
             'facebookname' => 
             array(
              'type' => 'string',
              'length' => 128,
             ),
             'projectname' => 
             array(
              'type' => 'string',
              'length' => 128,
             ),
             'addresscity' => 
             array(
              'type' => 'string',
              'length' => 64,
             ),
             'addresszipcode' => 
             array(
              'type' => 'string',
              'length' => 8,
             ),
             'addressstreet' => 
             array(
              'type' => 'string',
              'length' => 64,
             ),
             'addressdescriptionnumber' => 
             array(
              'type' => 'string',
              'length' => 16,
             ),
             'registrationnumber' => 
             array(
              'type' => 'string',
              'length' => 16,
             ),
             'vatnumber' => 
             array(
              'type' => 'string',
              'length' => 16,
             ),
             'openinghours' => 
             array(
              'type' => 'string',
              'length' => 128,
             ),
             'projectshorturl' => 
             array(
              'type' => 'string',
              'length' => 64,
             ),
             'pricedecimalplaces' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'enableregistration' => 
             array(
              'type' => 'boolean',
              'length' => 25,
             ),
             'pricevisibleonlyforlogged' => 
             array(
              'type' => 'boolean',
              'length' => 25,
             ),
             'sendername' => 
             array(
              'type' => 'string',
              'length' => 64,
             ),
             'senderemail' => 
             array(
              'type' => 'string',
              'length' => 64,
             ),
             'notifyemail' => 
             array(
              'type' => 'string',
              'length' => 64,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('common__model__settings');
    }
}