<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version62 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('admin__model__category', 'rank');
        $this->removeColumn('admin__model__category', 'visible');
        $this->addColumn('admin__model__banner', 'eshop_id', 'integer', '8', array(
             ));
        $this->addColumn('admin__model__parameter_lang', 'language_id', 'integer', '8', array(
             ));
    }

    public function down()
    {
        $this->addColumn('admin__model__category', 'rank', 'integer', '8', array(
             ));
        $this->addColumn('admin__model__category', 'visible', 'boolean', '25', array(
             'default' => '1',
             ));
        $this->removeColumn('admin__model__banner', 'eshop_id');
        $this->removeColumn('admin__model__parameter_lang', 'language_id');
    }
}