<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddadminModelCategorylang extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('admin__model__category_lang', array(
             'id' => 
             array(
              'primary' => true,
              'type' => 'integer',
              'autoincrement' => true,
              'length' => 8,
             ),
             'category_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'language_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'name' => 
             array(
              'type' => 'string',
              'length' => 128,
             ),
             'description' => 
             array(
              'type' => 'string',
              'length' => NULL,
             ),
             'shortdescription' => 
             array(
              'type' => 'string',
              'length' => NULL,
             ),
             'slug' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             ), array(
             'indexes' => 
             array(
              'admin__model__category_lang_sluggable' => 
              array(
              'fields' => 
              array(
               0 => 'slug',
              ),
              'type' => 'unique',
              ),
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('admin__model__category_lang');
    }
}