<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddadminModelPageeshop extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('admin__model__page_eshop', array(
             'id' => 
             array(
              'primary' => true,
              'type' => 'integer',
              'autoincrement' => true,
              'length' => 8,
             ),
             'page_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'eshop_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'active' => 
             array(
              'type' => 'boolean',
              'length' => 25,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('admin__model__page_eshop');
    }
}