<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddadminModelNews extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('admin__model__news', array(
             'id' => 
             array(
              'primary' => true,
              'type' => 'integer',
              'autoincrement' => true,
              'length' => 8,
             ),
             'file_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'date' => 
             array(
              'type' => 'date',
              'length' => 25,
             ),
             'active' => 
             array(
              'type' => 'boolean',
              'length' => 25,
             ),
             'perex' => 
             array(
              'type' => 'string',
              'length' => NULL,
             ),
             'content' => 
             array(
              'type' => 'string',
              'length' => NULL,
             ),
             'headline' => 
             array(
              'type' => 'string',
              'length' => 256,
             ),
             'slug' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             ), array(
             'indexes' => 
             array(
              'admin__model__news_sluggable' => 
              array(
              'fields' => 
              array(
               0 => 'slug',
              ),
              'type' => 'unique',
              ),
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('admin__model__news');
    }
}