<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddadminModelAddress extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('admin__model__address', array(
             'id' => 
             array(
              'primary' => true,
              'type' => 'integer',
              'autoincrement' => true,
              'length' => 8,
             ),
             'country_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'type' => 
             array(
              'type' => 'string',
              'length' => 32,
             ),
             'customertype' => 
             array(
              'type' => 'string',
              'length' => 32,
             ),
             'companyname' => 
             array(
              'type' => 'string',
              'length' => 256,
             ),
             'firstname' => 
             array(
              'type' => 'string',
              'length' => 64,
             ),
             'lastname' => 
             array(
              'type' => 'string',
              'length' => 64,
             ),
             'email' => 
             array(
              'type' => 'string',
              'length' => 64,
             ),
             'emailalternative' => 
             array(
              'type' => 'string',
              'length' => 64,
             ),
             'phone' => 
             array(
              'type' => 'string',
              'length' => 64,
             ),
             'street' => 
             array(
              'type' => 'string',
              'length' => 128,
             ),
             'city' => 
             array(
              'type' => 'string',
              'length' => 128,
             ),
             'descriptionnumber' => 
             array(
              'type' => 'string',
              'length' => 32,
             ),
             'zipcode' => 
             array(
              'type' => 'string',
              'length' => 16,
             ),
             'ic' => 
             array(
              'type' => 'string',
              'length' => 32,
             ),
             'dic' => 
             array(
              'type' => 'string',
              'length' => 32,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('admin__model__address');
    }
}