<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AddadminModelQuestion extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('admin__model__question', array(
             'id' => 
             array(
              'primary' => true,
              'type' => 'integer',
              'autoincrement' => true,
              'length' => 8,
             ),
             'eshop_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'product_id' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'description' => 
             array(
              'type' => 'string',
              'length' => NULL,
             ),
             'name' => 
             array(
              'type' => 'string',
              'length' => 128,
             ),
             'email' => 
             array(
              'type' => 'string',
              'length' => 128,
             ),
             'phone' => 
             array(
              'type' => 'string',
              'length' => 128,
             ),
             'date' => 
             array(
              'type' => 'date',
              'length' => 25,
             ),
             'time' => 
             array(
              'type' => 'time',
              'length' => 25,
             ),
             'state' => 
             array(
              'type' => 'string',
              'length' => 32,
             ),
             'solved' => 
             array(
              'type' => 'boolean',
              'length' => 25,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('admin__model__question');
    }
}