<?php
use Admin_Model_Page as Page;
use Admin_Model_PageLang as PageLang;

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class InitData3 extends Doctrine_Migration_AbstractCallback {

    public function perform(Doctrine_Connection $connection) {
        $this->initPages($connection);
    }

    /**
     * @param Doctrine_Connection $connection
     */
    private function initPages(Doctrine_Connection $connection) : void {
        $page = new Page();
        $page->ID = Page::ID_HOMEPAGE;
        $page->save($connection);

        $pageLang = new PageLang();
        $pageLang->Page_ID = $page->ID;
        $pageLang->Language_ID = 1;
        $pageLang->Name = 'Úvodní stránka';
        $pageLang->save();

        $pageLang = new PageLang();
        $pageLang->Page_ID = $page->ID;
        $pageLang->Language_ID = 2;
        $pageLang->Name = 'Úvodní stránka';
        $pageLang->save();
    }

    /**
     * @param Doctrine_Connection $connection
     */
    private function initEshops(Doctrine_Connection $connection) : void {
        $settings = new Settings();
        $settings->ID = 1;
        $settings->ContactPhone = '+420 773 565 051';
        $settings->ContactEmail = 'info@vamot.cz';
        $settings->OpeningHours = 'PO-PA: 08:00 - 16:00';
        $settings->ProjectName = 'Vamot s.r.o.';
        $settings->ProjectURL = 'https://www.tazne-zarizeni-vamot.cz/';
        $settings->ProjectShortURL = 'www.tazne-zarizeni-vamot.cz';
        $settings->AddressStreet = 'Budišovská';
        $settings->AddressDescriptionNumber = '908';
        $settings->AddressZipCode = '749 01';
        $settings->AddressCity = 'Vítkov';
        $settings->RegistrationNumber = '27838757';
        $settings->VATNumber = 'CZ27838757';
        $settings->SenderName = 'Vamot s.r.o.';
        $settings->SenderEmail = 'info@vamot.cz';
        $settings->NotifyEmail = 'info@vamot.cz';
        $settings->save($connection);

        $eshop = new Eshop();
        $eshop->ID = Eshop::VAMOT_CZ_ID;
        $eshop->Language_ID = Language::ID_LANGUAGE_CZ;
        $eshop->Currency_ID = Currency::CURRENCY_CZK_ID;
        $eshop->Vat_ID = Vat::VAT_21_ID;
        $eshop->Settings_ID = $settings->ID;
        $eshop->Name = 'Vamot CZ';
        $eshop->Active = 1;
        $eshop->URL = 'vamot.cz';
        $eshop->save($connection);

        $settings = new Settings();
        $settings->ID = 2;
        $settings->ContactPhone = '+421 910 402 002';
        $settings->ContactEmail = 'info@vamot.sk';
        $settings->OpeningHours = 'PO-PA: 08:00 - 16:00';
        $settings->ProjectName = 'VAMOT SK, spol. s r.o.';
        $settings->ProjectURL = 'https://www.tazne-zariadenia-vamot.sk/';
        $settings->ProjectShortURL = 'www.tazne-zariadenia-vamot.sk';
        $settings->AddressStreet = 'Slovanská cesta';
        $settings->AddressDescriptionNumber = '5047';
        $settings->AddressZipCode = '022 01';
        $settings->AddressCity = 'Čadca';
        $settings->RegistrationNumber = '52183319';
        $settings->VATNumber = 'SK2120966375';
        $settings->SenderName = 'VAMOT SK, spol. s r.o.';
        $settings->SenderEmail = 'info@vamot.sk';
        $settings->NotifyEmail = 'info@vamot.sk';
        $settings->save($connection);

        $eshop = new Eshop();
        $eshop->ID = Eshop::VAMOT_SK_ID;
        $eshop->Language_ID = Language::ID_LANGUAGE_CZ;
        $eshop->Currency_ID = Currency::CURRENCY_CZK_ID;
        $eshop->Vat_ID = Vat::VAT_20_ID;
        $eshop->Settings_ID = $settings->ID;
        $eshop->Name = 'Vamot SK';
        $eshop->Active = 1;
        $eshop->URL = 'vamot.sk';
        $eshop->save($connection);
    }

    /**
     * @param Doctrine_Connection $connection
     */
    private function initMenu(Doctrine_Connection $connection) : void {
        // header menu
        $menu = new Menu();
        $menu->ID = Menu::ID_HEADER_MENU;
        $menu->Name = 'Horní menu';
        $menu->Type = Menu::TYPE_HEADER_MENU;
        $menu->menuItems[] = $this->createMenuItem(Eshop::VAMOT_CZ_ID, 'Montujeme tažné zařízení', '/page/montujeme-tazne/');
        $menu->menuItems[] = $this->createMenuItem(Eshop::VAMOT_CZ_ID, 'Informace zákazníkům', '/page/informace-zakaznikum/');
        $menu->menuItems[] = $this->createMenuItem(Eshop::VAMOT_CZ_ID, 'Rady a tipy', '/page/montujeme-tazne/');
        $menu->menuItems[] = $this->createMenuItem(Eshop::VAMOT_CZ_ID, 'Kontakt', '/page/kontakt/');

        $menu->menuItems[] = $this->createMenuItem(Eshop::VAMOT_SK_ID, 'Montujeme tažné zariadenie', '/page/montujeme-tazne/');
        $menu->menuItems[] = $this->createMenuItem(Eshop::VAMOT_SK_ID, 'informacie-zakaznikom', '/page/informacie-zakaznikom/');
        $menu->menuItems[] = $this->createMenuItem(Eshop::VAMOT_SK_ID, 'Rady a tipy', '/page/montujeme-tazne/');
        $menu->menuItems[] = $this->createMenuItem(Eshop::VAMOT_SK_ID, 'Kontakt', '/page/kontakt/');
        $menu->save($connection);

        // footer menu #1
        $menu = new Menu();
        $menu->ID = Menu::ID_FOOTER_MENU_1;
        $menu->Name = 'Menu v patičce #1';
        $menu->Type = Menu::TYPE_FOOTER_MENU_1;
        $menu->menuItems[] = $this->createMenuItem(Eshop::VAMOT_CZ_ID, 'O nás', '/page/montujeme-tazne/');
        $menu->menuItems[] = $this->createMenuItem(Eshop::VAMOT_CZ_ID, 'Informace zákazníkům', '/page/informace-zakaznikum/');
        $menu->menuItems[] = $this->createMenuItem(Eshop::VAMOT_CZ_ID, 'Rady a tipy', '/page/montujeme-tazne/');
        $menu->menuItems[] = $this->createMenuItem(Eshop::VAMOT_CZ_ID, 'Obchodní podmínky', '/page/kontakt/');

        $menu->menuItems[] = $this->createMenuItem(Eshop::VAMOT_SK_ID, 'O nás', '/page/montujeme-tazne/');
        $menu->menuItems[] = $this->createMenuItem(Eshop::VAMOT_SK_ID, 'Informacie-zakaznikom', '/page/informacie-zakaznikom/');
        $menu->menuItems[] = $this->createMenuItem(Eshop::VAMOT_SK_ID, 'Rady a tipy', '/page/montujeme-tazne/');
        $menu->menuItems[] = $this->createMenuItem(Eshop::VAMOT_SK_ID, 'Obchodní podmínky', '/page/kontakt/');
        $menu->save($connection);

        // footer menu #2
        $menu = new Menu();
        $menu->ID = Menu::ID_FOOTER_MENU_2;
        $menu->Name = 'Menu v patičce #2';
        $menu->Type = Menu::TYPE_FOOTER_MENU_2;
        $menu->menuItems[] = $this->createMenuItem(Eshop::VAMOT_CZ_ID, 'Reklamační řád', '/page/montujeme-tazne/');
        $menu->menuItems[] = $this->createMenuItem(Eshop::VAMOT_CZ_ID, 'Ochrana osobních údajů', '/page/informace-zakaznikum/');
        $menu->menuItems[] = $this->createMenuItem(Eshop::VAMOT_CZ_ID, 'Montujeme tažné zařízení', '/page/montujeme-tazne/');
        $menu->menuItems[] = $this->createMenuItem(Eshop::VAMOT_CZ_ID, 'Kontakt', '/page/kontakt/');

        $menu->menuItems[] = $this->createMenuItem(Eshop::VAMOT_SK_ID, 'O nás', '/page/montujeme-tazne/');
        $menu->menuItems[] = $this->createMenuItem(Eshop::VAMOT_SK_ID, 'Ochrana osobních údajů', '/page/informacie-zakaznikom/');
        $menu->menuItems[] = $this->createMenuItem(Eshop::VAMOT_SK_ID, 'Montujeme tažné zařízení', '/page/montujeme-tazne/');
        $menu->menuItems[] = $this->createMenuItem(Eshop::VAMOT_SK_ID, 'Kontakt', '/page/kontakt/');
        $menu->save($connection);
    }

    /**
     * @param int $eshopID
     * @param string $name
     * @param string $url
     * @return MenuItem
     */
    private function createMenuItem(int $eshopID, string $name, string $url) : MenuItem {
        $menuItem = new MenuItem();
        $menuItem->Eshop_ID = $eshopID;
        $menuItem->Active = true;
        $menuItem->Name = $name;
        $menuItem->Url = $url;

        return $menuItem;
    }

    private function initOrderStateTypes($connection) {
        $this->createOrderStateType(
            $connection,
            OrderStateType::ID_STATE_NEW,
            'nová',
            '[[eshop_name]] - Objednávka [number] byla vytvořena',
            '<span>Dobrý den,</span><div><br /></div><div>děkujeme za Vaši objednávku na [eshop_url].</div>',
            '[[eshop_name]] - Objednávka [number] bola vytvorena',
            '<span>Dobrý den,</span><div><br /></div><div>děkujeme za Vaši objednávku na [eshop_url].</div>'
        );

        $this->createOrderStateType(
            $connection,
            OrderStateType::ID_STATE_TAKEN,
            'přijata',
            '[[eshop_name]] - Objednávka [number] se zpracovává',
            '<span>Dobrý den,</span><div><br /></div><div>Vaše objednávka na serveru [eshop_url] se právě zpracovává.</div>',
            '[[eshop_name]] - Objednávka [number] se zpracovává',
            '<span>Dobrý den,</span><div><br /></div><div>Vaše objednávka na serveru [eshop_url] se právě zpracovává.</div>'
        );

        $this->createOrderStateType(
            $connection,
            OrderStateType::ID_STATE_DISTRIBUTED,
            'odesláno',
            '[[eshop_name]] - Objednávka [number] byla odeslána',
            '<span>Dobrý den,</span><div><br /></div><div>Vaše objednávka na serveru [eshop_url] byla právě odeslána.</div>',
            '[[eshop_name]] - Objednávka [number] byla odeslána',
            '<span>Dobrý den,</span><div><br /></div><div>Vaše objednávka na serveru [eshop_url] byla právě odeslána.</div>'
        );

        $this->createOrderStateType(
            $connection,
            OrderStateType::ID_STATE_FINISH,
            'dokončeno',
            '[[eshop_name]] - Objednávka [number] byla dokončena',
            '<span>Dobrý den,</span><div><br /></div><div>Vaše objednávka na serveru [eshop_url] byla právě dokončena.</div>',
            '[[eshop_name]] - Objednávka [number] byla dokončena',
            '<span>Dobrý den,</span><div><br /></div><div>Vaše objednávka na serveru [eshop_url] byla právě dokončena.</div>'
        );

        $this->createOrderStateType(
            $connection,
            OrderStateType::ID_STATE_CANCEL,
            'zrušeno',
            '[[eshop_name]] - Objednávka [number] byla zrušena',
            '<span>Dobrý den,</span><div><br /></div><div>Vaše objednávka na serveru [eshop_url] byla právě zrušena.</div>',
            '[[eshop_name]] - Objednávka [number] byla zrušena',
            '<span>Dobrý den,</span><div><br /></div><div>Vaše objednávka na serveru [eshop_url] byla právě zrušena.</div>'
        );
    }

    /**
     * @param Doctrine_Connection $connection
     * @param int $ID
     * @param string $name
     * @param string $emailHeaderCZ
     * @param string $emailContentCZ
     * @param string $emailHeaderSK
     * @param string $emailContentSK
     */
    private function createOrderStateType(Doctrine_Connection $connection, int $ID, string $name, string $emailHeaderCZ, string $emailContentCZ, string $emailHeaderSK, string $emailContentSK) {
        $ost = new Admin_Model_OrderStateType();
        $ost->ID = $ID;
        $ost->Name = $name;
        $ost->SendEmail = 1;
        $ost->orderStateTypeLangs[] = $this->createOrderStateTypeLang(Language::ID_LANGUAGE_CZ, $emailHeaderCZ, $emailContentCZ);
        $ost->orderStateTypeLangs[] = $this->createOrderStateTypeLang(Language::ID_LANGUAGE_SK, $emailHeaderSK, $emailContentSK);
        $ost->save($connection);
    }

    /**
     * @param int $languageID
     * @param string $emailHeader
     * @param string $emailContent
     * @return Admin_Model_OrderStateTypeLang
     */
    private function createOrderStateTypeLang(int $languageID, string $emailHeader, string $emailContent) {
        $ostl = new Admin_Model_OrderStateTypeLang();
        $ostl->Language_ID = $languageID;
        $ostl->EmailHeader = $emailHeader;
        $ostl->EmailContent = $emailContent;

        return $ostl;
    }

    /**
     * @param Doctrine_Connection $connection
     */
    private function initUser(Doctrine_Connection $connection) {
        $user = new User_Model_User();
        $user->Name = 'admin';
        $user->Hash = 'da39a3ee5e6b4b0d3255bfef95601890afd80709';
        $user->Type = 'admin';
        $user->save($connection);
    }

    /**
     * @param $connection
     */
    private function initVats(Doctrine_Connection $connection) {
        $this->createVat($connection, Vat::VAT_21_ID, 'Základní daň 21%', 21);
        $this->createVat($connection, Vat::VAT_20_ID, 'Základní daň 20%', 20);
        $this->createVat($connection, Vat::VAT_15_ID, 'Základní daň 15%', 15);
        $this->createVat($connection, Vat::VAT_10_ID, 'Základní daň 10%', 10);
        $this->createVat($connection, Vat::VAT_0_ID, 'Nulová daň', 0);
    }

    /**
     * @param Doctrine_Connection $connection
     * @param int $ID
     * @param string $name
     * @param int $value
     */
    private function createVat(Doctrine_Connection $connection, int $ID, string $name, int $value) {
        $vat = new Vat();
        $vat->ID = $ID;
        $vat->Name = $name;
        $vat->Value = $value;
        $vat->save($connection);
    }

    /**
     * @param Doctrine_Connection $connection
     */
    public function initShippings(Doctrine_Connection $connection) {
        $shipping = new Shipping();
        $shipping->Vat_ID = Vat::VAT_21_ID;
        $shipping->Eshop_ID = Eshop::VAMOT_CZ_ID;
        $shipping->Name = 'Základní doprava';
        $shipping->Active = 1;
        $shipping->Price = 200;
        $shipping->VatType = Price::VAT_TYPE_WITHOUT;
        $shipping->save($connection);

        $payment = new Payment();
        $payment->Name = 'Základní platba';
        $payment->Vat_ID = Vat::VAT_21_ID;
        $payment->Eshop_ID = Eshop::VAMOT_CZ_ID;
        $payment->Active = 1;
        $payment->Price = 39;
        $payment->VatType = Price::VAT_TYPE_WITHOUT;
        $payment->save($connection);

        $shippingPayment = new ShippingPayment();
        $shippingPayment->Payment_ID = $payment->ID;
        $shippingPayment->Shipping_ID = $shipping->ID;
        $shippingPayment->save($connection);


        $shipping = new Shipping();
        $shipping->Vat_ID = Vat::VAT_20_ID;
        $shipping->Eshop_ID = Eshop::VAMOT_SK_ID;
        $shipping->Name = 'Základní doprava';
        $shipping->Active = 1;
        $shipping->Price = 9;
        $shipping->VatType = Price::VAT_TYPE_WITHOUT;
        $shipping->save($connection);

        $payment = new Payment();
        $payment->Vat_ID = Vat::VAT_20_ID;
        $payment->Eshop_ID = Eshop::VAMOT_SK_ID;
        $payment->Name = 'Základní platba';
        $payment->Active = 1;
        $payment->Price = 4;
        $payment->VatType = Price::VAT_TYPE_WITHOUT;
        $payment->save($connection);

        $shippingPayment = new ShippingPayment();
        $shippingPayment->Payment_ID = $payment->ID;
        $shippingPayment->Shipping_ID = $shipping->ID;
        $shippingPayment->save($connection);
    }

    /**
     * @param Doctrine_Connection $connection
     */
    public function initCurrencies(Doctrine_Connection $connection) {
        $this->createCurrency($connection, Currency::CURRENCY_CZK_ID, 'Česká koruna', 1, 'Kč', 'CZK');
        $this->createCurrency($connection, Currency::CURRENCY_EUR_ID, 'Euro', 0.037, '€', 'EUR');
    }

    /**
     * @param Doctrine_Connection $connection
     * @param int $id
     * @param string $name
     * @param float $ratio
     * @param string $label
     * @param string $mark
     */
    private function createCurrency(Doctrine_Connection $connection, int $id, string $name, float $ratio, string $label, string $mark) {
        $currency = new Currency();
        $currency->ID = $id;
        $currency->Name = $name;
        $currency->Ratio = $ratio;
        $currency->Label = $label;
        $currency->Mark = $mark;
        $currency->save($connection);
    }
}