<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version86 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('admin__model__order_state_type', 'color', 'string', '32', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('admin__model__order_state_type', 'color');
    }
}