<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version85 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('admin__model__order_state_type', 'name');
        $this->addColumn('admin__model__order_state_type_lang', 'name', 'string', '64', array(
             ));
    }

    public function down()
    {
        $this->addColumn('admin__model__order_state_type', 'name', 'string', '64', array(
             ));
        $this->removeColumn('admin__model__order_state_type_lang', 'name');
    }
}