<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version84 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('common__model__language', 'isdefault', 'boolean', '25', array(
             ));
        $this->addColumn('common__model__language', 'active', 'boolean', '25', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('common__model__language', 'isdefault');
        $this->removeColumn('common__model__language', 'active');
    }
}