<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version87 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('admin__model__order', 'datepayed', 'date', '25', array(
             ));
        $this->addColumn('admin__model__order', 'dateshipped', 'date', '25', array(
             ));
        $this->addColumn('admin__model__order', 'dateshipmenttransit', 'date', '25', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('admin__model__order', 'datepayed');
        $this->removeColumn('admin__model__order', 'dateshipped');
        $this->removeColumn('admin__model__order', 'dateshipmenttransit');
    }
}