<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version92 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('admin__model__order_state', 'user_id', 'integer', '8', array(
             ));
        $this->addColumn('admin__model__order_state', 'username', 'string', '128', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('admin__model__order_state', 'user_id');
        $this->removeColumn('admin__model__order_state', 'username');
    }
}