<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version97 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('admin__model__balikobot_state', 'abai', array(
             'name' => 'abai',
             'local' => 'balikobotpackage_id',
             'foreign' => 'id',
             'foreignTable' => 'admin__model__balikobot_package',
             ));
        $this->addIndex('admin__model__balikobot_state', 'admin__model__balikobot_state_balikobotpackage_id', array(
             'fields' => 
             array(
              0 => 'balikobotpackage_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('admin__model__balikobot_state', 'abai');
        $this->removeIndex('admin__model__balikobot_state', 'admin__model__balikobot_state_balikobotpackage_id', array(
             'fields' => 
             array(
              0 => 'balikobotpackage_id',
             ),
             ));
    }
}