<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version98 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('user__model__group', array(
             'id' => 
             array(
              'primary' => '1',
              'type' => 'integer',
              'autoincrement' => '1',
              'length' => '8',
             ),
             'name' => 
             array(
              'type' => 'string',
              'length' => '128',
             ),
             'discount' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'utf8',
             ));
        $this->addColumn('user__model__user', 'group_id', 'integer', '8', array(
             ));
    }

    public function down()
    {
        $this->dropTable('user__model__group');
        $this->removeColumn('user__model__user', 'group_id');
    }
}