<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version89 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('user__model__user_eshop', 'user__model__user_eshop_user_id_user__model__user_id', array(
             'name' => 'user__model__user_eshop_user_id_user__model__user_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'user__model__user',
             ));
        $this->createForeignKey('user__model__user_eshop', 'user__model__user_eshop_eshop_id_common__model__eshop_id', array(
             'name' => 'user__model__user_eshop_eshop_id_common__model__eshop_id',
             'local' => 'eshop_id',
             'foreign' => 'id',
             'foreignTable' => 'common__model__eshop',
             ));
        $this->createForeignKey('user__model__user_has_permission', 'user__model__user_has_permission_user_id_user__model__user_id', array(
             'name' => 'user__model__user_has_permission_user_id_user__model__user_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'user__model__user',
             ));
        $this->createForeignKey('user__model__user_has_permission', 'upui', array(
             'name' => 'upui',
             'local' => 'permission_id',
             'foreign' => 'id',
             'foreignTable' => 'user__model__permission',
             ));
        $this->addIndex('user__model__user_eshop', 'user__model__user_eshop_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->addIndex('user__model__user_eshop', 'user__model__user_eshop_eshop_id', array(
             'fields' => 
             array(
              0 => 'eshop_id',
             ),
             ));
        $this->addIndex('user__model__user_has_permission', 'user__model__user_has_permission_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->addIndex('user__model__user_has_permission', 'user__model__user_has_permission_permission_id', array(
             'fields' => 
             array(
              0 => 'permission_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('user__model__user_eshop', 'user__model__user_eshop_user_id_user__model__user_id');
        $this->dropForeignKey('user__model__user_eshop', 'user__model__user_eshop_eshop_id_common__model__eshop_id');
        $this->dropForeignKey('user__model__user_has_permission', 'user__model__user_has_permission_user_id_user__model__user_id');
        $this->dropForeignKey('user__model__user_has_permission', 'upui');
        $this->removeIndex('user__model__user_eshop', 'user__model__user_eshop_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->removeIndex('user__model__user_eshop', 'user__model__user_eshop_eshop_id', array(
             'fields' => 
             array(
              0 => 'eshop_id',
             ),
             ));
        $this->removeIndex('user__model__user_has_permission', 'user__model__user_has_permission_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->removeIndex('user__model__user_has_permission', 'user__model__user_has_permission_permission_id', array(
             'fields' => 
             array(
              0 => 'permission_id',
             ),
             ));
    }
}