<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version100 extends Doctrine_Migration_Base
{
    public function up()
    {

    }

    public function down()
    {
        $this->addColumn('user__model__user', 'group_id', 'integer', '8', array(
             ));
    }
}