<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version94 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('admin__model__balikobot_package', array(
             'id' => 
             array(
              'primary' => '1',
              'type' => 'integer',
              'autoincrement' => '1',
              'length' => '8',
             ),
             'order_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'packageid' => 
             array(
              'type' => 'string',
              'length' => '32',
             ),
             'trackingurl' => 
             array(
              'type' => 'string',
              'length' => '512',
             ),
             'labelurl' => 
             array(
              'type' => 'string',
              'length' => '',
             ),
             'carrierid' => 
             array(
              'type' => 'string',
              'length' => '32',
             ),
             'balikobotorderid' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'state' => 
             array(
              'type' => 'string',
              'length' => '64',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'utf8',
             ));
        $this->createTable('admin__model__balikobot_state', array(
             'id' => 
             array(
              'primary' => '1',
              'type' => 'integer',
              'autoincrement' => '1',
              'length' => '8',
             ),
             'date' => 
             array(
              'type' => 'date',
              'length' => '25',
             ),
             'time' => 
             array(
              'type' => 'time',
              'length' => '25',
             ),
             'state' => 
             array(
              'type' => 'string',
              'length' => '128',
             ),
             'message' => 
             array(
              'type' => 'string',
              'length' => '512',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'utf8',
             ));
        $this->addColumn('admin__model__order', 'balikobotid', 'string', '32', array(
             ));
        $this->addColumn('admin__model__order', 'balikobotpackageid', 'string', '32', array(
             ));
        $this->addColumn('admin__model__order', 'balikobottrackingurl', 'string', '512', array(
             ));
        $this->addColumn('admin__model__order', 'balikobotlabeliurl', 'string', '', array(
             ));
        $this->addColumn('admin__model__order', 'balikobotcarrierid', 'string', '32', array(
             ));
    }

    public function down()
    {
        $this->dropTable('admin__model__balikobot_package');
        $this->dropTable('admin__model__balikobot_state');
        $this->removeColumn('admin__model__order', 'balikobotid');
        $this->removeColumn('admin__model__order', 'balikobotpackageid');
        $this->removeColumn('admin__model__order', 'balikobottrackingurl');
        $this->removeColumn('admin__model__order', 'balikobotlabeliurl');
        $this->removeColumn('admin__model__order', 'balikobotcarrierid');
    }
}