<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version90 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('admin__model__gopay_payment', array(
             'id' => 
             array(
              'primary' => '1',
              'type' => 'integer',
              'autoincrement' => '1',
              'length' => '8',
             ),
             'order_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'date' => 
             array(
              'type' => 'date',
              'length' => '25',
             ),
             'time' => 
             array(
              'type' => 'time',
              'length' => '25',
             ),
             'gopayid' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'gopayurl' => 
             array(
              'type' => 'string',
              'length' => '512',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'utf8',
             ));
        $this->createTable('admin__model__gopay_payment_state', array(
             'id' => 
             array(
              'primary' => '1',
              'type' => 'integer',
              'autoincrement' => '1',
              'length' => '8',
             ),
             'gopaypayment_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'orderstatetype_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'date' => 
             array(
              'type' => 'date',
              'length' => '25',
             ),
             'time' => 
             array(
              'type' => 'time',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('admin__model__gopay_payment');
        $this->dropTable('admin__model__gopay_payment_state');
    }
}