<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version108 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('admin__model__test', array(
             'id' => 
             array(
              'primary' => '1',
              'type' => 'integer',
              'autoincrement' => '1',
              'length' => '8',
             ),
             'name' => 
             array(
              'type' => 'string',
              'length' => '128',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('admin__model__test');
    }
}