<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version107 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('admin__model__cart', 'montage', 'boolean', '25', array(
             ));
        $this->addColumn('admin__model__order_item', 'montage', 'boolean', '25', array(
             ));
        $this->addColumn('admin__model__product', 'montage', 'boolean', '25', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('admin__model__cart', 'montage');
        $this->removeColumn('admin__model__order_item', 'montage');
        $this->removeColumn('admin__model__product', 'montage');
    }
}