<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version111 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('admin__model__test_item', 'admin__model__test_item_test_id_admin__model__test_id', array(
             'name' => 'admin__model__test_item_test_id_admin__model__test_id',
             'local' => 'test_id',
             'foreign' => 'id',
             'foreignTable' => 'admin__model__test',
             ));
        $this->addIndex('admin__model__test_item', 'admin__model__test_item_test_id', array(
             'fields' => 
             array(
              0 => 'test_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('admin__model__test_item', 'admin__model__test_item_test_id_admin__model__test_id');
        $this->removeIndex('admin__model__test_item', 'admin__model__test_item_test_id', array(
             'fields' => 
             array(
              0 => 'test_id',
             ),
             ));
    }
}