<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version114 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropTable('admin__model__test');
        $this->dropTable('admin__model__test_item');
    }

    public function down()
    {
        $this->createTable('admin__model__test', array(
             'id' => 
             array(
              'primary' => '1',
              'type' => 'integer',
              'autoincrement' => '1',
              'length' => '8',
             ),
             'name' => 
             array(
              'type' => 'string',
              'length' => '128',
             ),
             'test2' => 
             array(
              'type' => 'string',
              'length' => '64',
             ),
             ), array(
             'type' => '',
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => '',
             'charset' => 'utf8',
             ));
        $this->createTable('admin__model__test_item', array(
             'id' => 
             array(
              'primary' => '1',
              'type' => 'integer',
              'autoincrement' => '1',
              'length' => '8',
             ),
             'sue' => 
             array(
              'type' => 'string',
              'length' => '128',
             ),
             ), array(
             'type' => '',
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => '',
             'charset' => 'utf8',
             ));
    }
}