<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version112 extends Doctrine_Migration_Base
{
    public function up()
    {

    }

    public function down()
    {
        $this->addColumn('admin__model__test_item', 'test_id', 'integer', '8', array(
             'notnull' => '1',
             ));
    }
}