<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version115 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('admin__model__shipping_category', array(
             'id' => 
             array(
              'primary' => '1',
              'type' => 'integer',
              'autoincrement' => '1',
              'length' => '8',
             ),
             'category_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'shipping_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'vat_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'price' => 
             array(
              'type' => 'decimal',
              'length' => '18',
             ),
             'vattype' => 
             array(
              'type' => 'string',
              'length' => '32',
             ),
             'priceperpiece' => 
             array(
              'type' => 'boolean',
              'length' => '25',
             ),
             'pricealways' => 
             array(
              'type' => 'boolean',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('admin__model__shipping_category');
    }
}