<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version116 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('admin__model__shipping_category', 'asai_1', array(
             'name' => 'asai_1',
             'local' => 'shipping_id',
             'foreign' => 'id',
             'foreignTable' => 'admin__model__shipping',
             ));
        $this->createForeignKey('admin__model__shipping_category', 'acai_4', array(
             'name' => 'acai_4',
             'local' => 'category_id',
             'foreign' => 'id',
             'foreignTable' => 'admin__model__category',
             ));
        $this->createForeignKey('admin__model__shipping_category', 'admin__model__shipping_category_vat_id_admin__model__vat_id', array(
             'name' => 'admin__model__shipping_category_vat_id_admin__model__vat_id',
             'local' => 'vat_id',
             'foreign' => 'id',
             'foreignTable' => 'admin__model__vat',
             ));
        $this->addIndex('admin__model__shipping_category', 'admin__model__shipping_category_shipping_id', array(
             'fields' => 
             array(
              0 => 'shipping_id',
             ),
             ));
        $this->addIndex('admin__model__shipping_category', 'admin__model__shipping_category_category_id', array(
             'fields' => 
             array(
              0 => 'category_id',
             ),
             ));
        $this->addIndex('admin__model__shipping_category', 'admin__model__shipping_category_vat_id', array(
             'fields' => 
             array(
              0 => 'vat_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('admin__model__shipping_category', 'asai_1');
        $this->dropForeignKey('admin__model__shipping_category', 'acai_4');
        $this->dropForeignKey('admin__model__shipping_category', 'admin__model__shipping_category_vat_id_admin__model__vat_id');
        $this->removeIndex('admin__model__shipping_category', 'admin__model__shipping_category_shipping_id', array(
             'fields' => 
             array(
              0 => 'shipping_id',
             ),
             ));
        $this->removeIndex('admin__model__shipping_category', 'admin__model__shipping_category_category_id', array(
             'fields' => 
             array(
              0 => 'category_id',
             ),
             ));
        $this->removeIndex('admin__model__shipping_category', 'admin__model__shipping_category_vat_id', array(
             'fields' => 
             array(
              0 => 'vat_id',
             ),
             ));
    }
}