<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version117 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('user__model__user_settings', 'showonmap', 'boolean', '25', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('user__model__user_settings', 'showonmap');
    }
}