<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version126 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('admin__model__payment', 'pohodacode', 'string', '128', array(
             ));
        $this->addColumn('admin__model__shipping', 'pohodacode', 'string', '128', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('admin__model__payment', 'pohodacode');
        $this->removeColumn('admin__model__shipping', 'pohodacode');
    }
}