<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version127 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('user__model__group_discount', array(
             'id' => 
             array(
              'primary' => '1',
              'type' => 'integer',
              'autoincrement' => '1',
              'length' => '8',
             ),
             'group_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'discount' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('user__model__group_discount');
    }
}