<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version130 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('user__model__group_discount', 'category_id', 'integer', '8', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('user__model__group_discount', 'category_id');
    }
}