<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version132 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('admin__model__payment', 'iban', 'string', '128', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('admin__model__payment', 'iban');
    }
}