<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version135 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('admin__model__feedback', array(
             'id' => 
             array(
              'primary' => '1',
              'type' => 'integer',
              'autoincrement' => '1',
              'length' => '8',
             ),
             'creatoruser_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'solveruser_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'eshop_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'project_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'header' => 
             array(
              'type' => 'string',
              'length' => '256',
             ),
             'datetime' => 
             array(
              'type' => 'timestamp',
              'length' => '25',
             ),
             'content' => 
             array(
              'type' => 'string',
              'length' => '',
             ),
             'priority' => 
             array(
              'type' => 'string',
              'length' => '32',
             ),
             'dateexpectedsolving' => 
             array(
              'type' => 'date',
              'length' => '25',
             ),
             'datesolved' => 
             array(
              'type' => 'date',
              'length' => '25',
             ),
             'tmpstate' => 
             array(
              'type' => 'string',
              'length' => '32',
             ),
             'feedbacknumber' => 
             array(
              'type' => 'string',
              'length' => '32',
             ),
             'hash' => 
             array(
              'type' => 'string',
              'length' => '32',
             ),
             'errorreporting' => 
             array(
              'type' => 'boolean',
              'length' => '25',
             ),
             'datestartsolving' => 
             array(
              'type' => 'date',
              'length' => '25',
             ),
             'workedtimeprivate' => 
             array(
              'type' => 'decimal',
              'length' => '18',
             ),
             'workedtimepublic' => 
             array(
              'type' => 'decimal',
              'length' => '18',
             ),
             'scriptcodecontent' => 
             array(
              'type' => 'string',
              'length' => '',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'utf8',
             ));
        $this->createTable('admin__model__feedback_file', array(
             'id' => 
             array(
              'primary' => '1',
              'type' => 'integer',
              'autoincrement' => '1',
              'length' => '8',
             ),
             'feedback_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'file_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'utf8',
             ));
        $this->createTable('admin__model__feedback_read_last_state', array(
             'id' => 
             array(
              'primary' => '1',
              'type' => 'integer',
              'autoincrement' => '1',
              'length' => '8',
             ),
             'feedback_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'user_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'readstate' => 
             array(
              'type' => 'boolean',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'utf8',
             ));
        $this->createTable('admin__model__feedback_state', array(
             'id' => 
             array(
              'primary' => '1',
              'type' => 'integer',
              'autoincrement' => '1',
              'length' => '8',
             ),
             'feedback_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'user_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'datetime' => 
             array(
              'type' => 'timestamp',
              'length' => '25',
             ),
             'state' => 
             array(
              'type' => 'string',
              'length' => '32',
             ),
             'description' => 
             array(
              'type' => 'string',
              'length' => '',
             ),
             'sendemail' => 
             array(
              'type' => 'boolean',
              'length' => '25',
             ),
             'scriptcodecontent' => 
             array(
              'type' => 'string',
              'length' => '',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'utf8',
             ));
        $this->createTable('admin__model__project', array(
             'id' => 
             array(
              'primary' => '1',
              'type' => 'integer',
              'autoincrement' => '1',
              'length' => '8',
             ),
             'defaultsolver_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'name' => 
             array(
              'type' => 'string',
              'length' => '64',
             ),
             'www' => 
             array(
              'type' => 'string',
              'length' => '64',
             ),
             'description' => 
             array(
              'type' => 'string',
              'length' => '',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('admin__model__feedback');
        $this->dropTable('admin__model__feedback_file');
        $this->dropTable('admin__model__feedback_read_last_state');
        $this->dropTable('admin__model__feedback_state');
        $this->dropTable('admin__model__project');
    }
}