<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version136 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('admin__model__feedback', 'admin__model__feedback_creatoruser_id_user__model__user_id', array(
             'name' => 'admin__model__feedback_creatoruser_id_user__model__user_id',
             'local' => 'creatoruser_id',
             'foreign' => 'id',
             'foreignTable' => 'user__model__user',
             ));
        $this->createForeignKey('admin__model__feedback', 'admin__model__feedback_solveruser_id_user__model__user_id', array(
             'name' => 'admin__model__feedback_solveruser_id_user__model__user_id',
             'local' => 'solveruser_id',
             'foreign' => 'id',
             'foreignTable' => 'user__model__user',
             ));
        $this->createForeignKey('admin__model__feedback', 'admin__model__feedback_eshop_id_common__model__eshop_id', array(
             'name' => 'admin__model__feedback_eshop_id_common__model__eshop_id',
             'local' => 'eshop_id',
             'foreign' => 'id',
             'foreignTable' => 'common__model__eshop',
             ));
        $this->createForeignKey('admin__model__feedback', 'admin__model__feedback_project_id_admin__model__project_id', array(
             'name' => 'admin__model__feedback_project_id_admin__model__project_id',
             'local' => 'project_id',
             'foreign' => 'id',
             'foreignTable' => 'admin__model__project',
             ));
        $this->createForeignKey('admin__model__feedback_file', 'afai', array(
             'name' => 'afai',
             'local' => 'feedback_id',
             'foreign' => 'id',
             'foreignTable' => 'admin__model__feedback',
             ));
        $this->createForeignKey('admin__model__feedback_file', 'admin__model__feedback_file_file_id_common__model__file_id', array(
             'name' => 'admin__model__feedback_file_file_id_common__model__file_id',
             'local' => 'file_id',
             'foreign' => 'id',
             'foreignTable' => 'common__model__file',
             ));
        $this->createForeignKey('admin__model__feedback_read_last_state', 'afai_1', array(
             'name' => 'afai_1',
             'local' => 'feedback_id',
             'foreign' => 'id',
             'foreignTable' => 'admin__model__feedback',
             ));
        $this->createForeignKey('admin__model__feedback_read_last_state', 'auui', array(
             'name' => 'auui',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'user__model__user',
             ));
        $this->createForeignKey('admin__model__feedback_state', 'afai_2', array(
             'name' => 'afai_2',
             'local' => 'feedback_id',
             'foreign' => 'id',
             'foreignTable' => 'admin__model__feedback',
             ));
        $this->createForeignKey('admin__model__feedback_state', 'admin__model__feedback_state_user_id_user__model__user_id', array(
             'name' => 'admin__model__feedback_state_user_id_user__model__user_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'user__model__user',
             ));
        $this->createForeignKey('admin__model__project', 'admin__model__project_defaultsolver_id_user__model__user_id', array(
             'name' => 'admin__model__project_defaultsolver_id_user__model__user_id',
             'local' => 'defaultsolver_id',
             'foreign' => 'id',
             'foreignTable' => 'user__model__user',
             ));
        $this->addIndex('admin__model__feedback', 'admin__model__feedback_creatoruser_id', array(
             'fields' => 
             array(
              0 => 'creatoruser_id',
             ),
             ));
        $this->addIndex('admin__model__feedback', 'admin__model__feedback_solveruser_id', array(
             'fields' => 
             array(
              0 => 'solveruser_id',
             ),
             ));
        $this->addIndex('admin__model__feedback', 'admin__model__feedback_eshop_id', array(
             'fields' => 
             array(
              0 => 'eshop_id',
             ),
             ));
        $this->addIndex('admin__model__feedback', 'admin__model__feedback_project_id', array(
             'fields' => 
             array(
              0 => 'project_id',
             ),
             ));
        $this->addIndex('admin__model__feedback_file', 'admin__model__feedback_file_feedback_id', array(
             'fields' => 
             array(
              0 => 'feedback_id',
             ),
             ));
        $this->addIndex('admin__model__feedback_file', 'admin__model__feedback_file_file_id', array(
             'fields' => 
             array(
              0 => 'file_id',
             ),
             ));
        $this->addIndex('admin__model__feedback_read_last_state', 'admin__model__feedback_read_last_state_feedback_id', array(
             'fields' => 
             array(
              0 => 'feedback_id',
             ),
             ));
        $this->addIndex('admin__model__feedback_read_last_state', 'admin__model__feedback_read_last_state_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->addIndex('admin__model__feedback_state', 'admin__model__feedback_state_feedback_id', array(
             'fields' => 
             array(
              0 => 'feedback_id',
             ),
             ));
        $this->addIndex('admin__model__feedback_state', 'admin__model__feedback_state_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->addIndex('admin__model__project', 'admin__model__project_defaultsolver_id', array(
             'fields' => 
             array(
              0 => 'defaultsolver_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('admin__model__feedback', 'admin__model__feedback_creatoruser_id_user__model__user_id');
        $this->dropForeignKey('admin__model__feedback', 'admin__model__feedback_solveruser_id_user__model__user_id');
        $this->dropForeignKey('admin__model__feedback', 'admin__model__feedback_eshop_id_common__model__eshop_id');
        $this->dropForeignKey('admin__model__feedback', 'admin__model__feedback_project_id_admin__model__project_id');
        $this->dropForeignKey('admin__model__feedback_file', 'afai');
        $this->dropForeignKey('admin__model__feedback_file', 'admin__model__feedback_file_file_id_common__model__file_id');
        $this->dropForeignKey('admin__model__feedback_read_last_state', 'afai_1');
        $this->dropForeignKey('admin__model__feedback_read_last_state', 'auui');
        $this->dropForeignKey('admin__model__feedback_state', 'afai_2');
        $this->dropForeignKey('admin__model__feedback_state', 'admin__model__feedback_state_user_id_user__model__user_id');
        $this->dropForeignKey('admin__model__project', 'admin__model__project_defaultsolver_id_user__model__user_id');
        $this->removeIndex('admin__model__feedback', 'admin__model__feedback_creatoruser_id', array(
             'fields' => 
             array(
              0 => 'creatoruser_id',
             ),
             ));
        $this->removeIndex('admin__model__feedback', 'admin__model__feedback_solveruser_id', array(
             'fields' => 
             array(
              0 => 'solveruser_id',
             ),
             ));
        $this->removeIndex('admin__model__feedback', 'admin__model__feedback_eshop_id', array(
             'fields' => 
             array(
              0 => 'eshop_id',
             ),
             ));
        $this->removeIndex('admin__model__feedback', 'admin__model__feedback_project_id', array(
             'fields' => 
             array(
              0 => 'project_id',
             ),
             ));
        $this->removeIndex('admin__model__feedback_file', 'admin__model__feedback_file_feedback_id', array(
             'fields' => 
             array(
              0 => 'feedback_id',
             ),
             ));
        $this->removeIndex('admin__model__feedback_file', 'admin__model__feedback_file_file_id', array(
             'fields' => 
             array(
              0 => 'file_id',
             ),
             ));
        $this->removeIndex('admin__model__feedback_read_last_state', 'admin__model__feedback_read_last_state_feedback_id', array(
             'fields' => 
             array(
              0 => 'feedback_id',
             ),
             ));
        $this->removeIndex('admin__model__feedback_read_last_state', 'admin__model__feedback_read_last_state_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->removeIndex('admin__model__feedback_state', 'admin__model__feedback_state_feedback_id', array(
             'fields' => 
             array(
              0 => 'feedback_id',
             ),
             ));
        $this->removeIndex('admin__model__feedback_state', 'admin__model__feedback_state_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->removeIndex('admin__model__project', 'admin__model__project_defaultsolver_id', array(
             'fields' => 
             array(
              0 => 'defaultsolver_id',
             ),
             ));
    }
}