<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version144 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('admin__model__api_log', array(
             'id' => 
             array(
              'primary' => '1',
              'type' => 'integer',
              'autoincrement' => '1',
              'length' => '8',
             ),
             'user' => 
             array(
              'type' => 'string',
              'length' => '256',
             ),
             'datetime' => 
             array(
              'type' => 'timestamp',
              'length' => '25',
             ),
             'url' => 
             array(
              'type' => 'string',
              'length' => '',
             ),
             'statuscode' => 
             array(
              'type' => 'string',
              'length' => '32',
             ),
             'message' => 
             array(
              'type' => 'string',
              'length' => '32',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('admin__model__api_log');
    }
}