<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version143 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('admin__model__car_brand', 'api_id', 'integer', '8', array(
             ));
        $this->addColumn('admin__model__manufacturer', 'api_id', 'integer', '8', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('admin__model__car_brand', 'api_id');
        $this->removeColumn('admin__model__manufacturer', 'api_id');
    }
}