<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version151 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('admin__model__announcement', 'admin__model__announcement_eshop_id_common__model__eshop_id', array(
             'name' => 'admin__model__announcement_eshop_id_common__model__eshop_id',
             'local' => 'eshop_id',
             'foreign' => 'id',
             'foreignTable' => 'common__model__eshop',
             ));
        $this->addIndex('admin__model__announcement', 'admin__model__announcement_eshop_id', array(
             'fields' => 
             array(
              0 => 'eshop_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('admin__model__announcement', 'admin__model__announcement_eshop_id_common__model__eshop_id');
        $this->removeIndex('admin__model__announcement', 'admin__model__announcement_eshop_id', array(
             'fields' => 
             array(
              0 => 'eshop_id',
             ),
             ));
    }
}