<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version146 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('admin__model__coupon', array(
             'id' => 
             array(
              'primary' => '1',
              'type' => 'integer',
              'autoincrement' => '1',
              'length' => '8',
             ),
             'product_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'user_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'code' => 
             array(
              'type' => 'string',
              'length' => '64',
             ),
             'type' => 
             array(
              'type' => 'string',
              'length' => '16',
             ),
             'quantity' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'discount' => 
             array(
              'type' => 'float',
              'length' => '',
             ),
             'totalcount' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'usedcount' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'expirydate' => 
             array(
              'type' => 'date',
              'length' => '25',
             ),
             'createddate' => 
             array(
              'type' => 'date',
              'length' => '25',
             ),
             'minorder' => 
             array(
              'type' => 'float',
              'length' => '',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'utf8',
             ));
        $this->createTable('admin__model__coupon_lang', array(
             'id' => 
             array(
              'primary' => '1',
              'type' => 'integer',
              'autoincrement' => '1',
              'length' => '8',
             ),
             'coupon_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'language_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'name' => 
             array(
              'type' => 'string',
              'length' => '128',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'utf8',
             ));
        $this->addColumn('admin__model__cart', 'coupon_id', 'integer', '8', array(
             ));
        $this->addColumn('admin__model__order', 'coupon_id', 'integer', '8', array(
             ));
    }

    public function down()
    {
        $this->dropTable('admin__model__coupon');
        $this->dropTable('admin__model__coupon_lang');
        $this->removeColumn('admin__model__cart', 'coupon_id');
        $this->removeColumn('admin__model__order', 'coupon_id');
    }
}