<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version152 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('user__model__user_credit', array(
             'id' => 
             array(
              'primary' => '1',
              'type' => 'integer',
              'autoincrement' => '1',
              'length' => '8',
             ),
             'user_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'order_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'credit' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'datetime' => 
             array(
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('user__model__user_credit');
    }
}