<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version155 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('admin__model__user_credit_transaction', 'auui_2', array(
             'name' => 'auui_2',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'user__model__user',
             ));
        $this->createForeignKey('admin__model__user_credit_transaction', 'aeci_2', array(
             'name' => 'aeci_2',
             'local' => 'eshop_id',
             'foreign' => 'id',
             'foreignTable' => 'common__model__eshop',
             ));
        $this->createForeignKey('admin__model__user_credit_transaction', 'aoai_4', array(
             'name' => 'aoai_4',
             'local' => 'order_id',
             'foreign' => 'id',
             'foreignTable' => 'admin__model__order',
             ));
        $this->addIndex('admin__model__user_credit_transaction', 'admin__model__user_credit_transaction_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->addIndex('admin__model__user_credit_transaction', 'admin__model__user_credit_transaction_eshop_id', array(
             'fields' => 
             array(
              0 => 'eshop_id',
             ),
             ));
        $this->addIndex('admin__model__user_credit_transaction', 'admin__model__user_credit_transaction_order_id', array(
             'fields' => 
             array(
              0 => 'order_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('admin__model__user_credit_transaction', 'auui_2');
        $this->dropForeignKey('admin__model__user_credit_transaction', 'aeci_2');
        $this->dropForeignKey('admin__model__user_credit_transaction', 'aoai_4');
        $this->removeIndex('admin__model__user_credit_transaction', 'admin__model__user_credit_transaction_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
        $this->removeIndex('admin__model__user_credit_transaction', 'admin__model__user_credit_transaction_eshop_id', array(
             'fields' => 
             array(
              0 => 'eshop_id',
             ),
             ));
        $this->removeIndex('admin__model__user_credit_transaction', 'admin__model__user_credit_transaction_order_id', array(
             'fields' => 
             array(
              0 => 'order_id',
             ),
             ));
    }
}