<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version154 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('admin__model__user_credit_transaction', array(
             'id' => 
             array(
              'primary' => '1',
              'type' => 'integer',
              'autoincrement' => '1',
              'length' => '8',
             ),
             'user_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'eshop_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'order_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'creditspent' => 
             array(
              'type' => 'decimal',
              'length' => '18',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('admin__model__user_credit_transaction');
    }
}