<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version161 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('user__model__user_utm_params', array(
             'id' => 
             array(
              'primary' => '1',
              'type' => 'integer',
              'autoincrement' => '1',
              'length' => '8',
             ),
             'datetime' => 
             array(
              'type' => 'timestamp',
              'length' => '25',
             ),
             'source' => 
             array(
              'type' => 'string',
              'length' => '64',
             ),
             'medium' => 
             array(
              'type' => 'string',
              'length' => '128',
             ),
             'name' => 
             array(
              'type' => 'string',
              'length' => '128',
             ),
             'content' => 
             array(
              'type' => 'string',
              'length' => '',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'utf8',
             ));
        $this->addColumn('admin__model__order', 'userutmparams_id', 'integer', '8', array(
             ));
    }

    public function down()
    {
        $this->dropTable('user__model__user_utm_params');
        $this->removeColumn('admin__model__order', 'userutmparams_id');
    }
}