<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version165 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('admin__model__category_featured_on_homepage', 'acai_8', array(
             'name' => 'acai_8',
             'local' => 'category_id',
             'foreign' => 'id',
             'foreignTable' => 'admin__model__category',
             ));
        $this->addIndex('admin__model__category_featured_on_homepage', 'admin__model__category_featured_on_homepage_category_id', array(
             'fields' => 
             array(
              0 => 'category_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('admin__model__category_featured_on_homepage', 'acai_8');
        $this->removeIndex('admin__model__category_featured_on_homepage', 'admin__model__category_featured_on_homepage_category_id', array(
             'fields' => 
             array(
              0 => 'category_id',
             ),
             ));
    }
}