<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version164 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('admin__model__category_featured_on_homepage', array(
             'id' => 
             array(
              'primary' => '1',
              'type' => 'integer',
              'autoincrement' => '1',
              'length' => '8',
             ),
             'category_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'position' => 
             array(
              'type' => 'string',
              'length' => '128',
             ),
             'moreinfobtntext' => 
             array(
              'type' => 'string',
              'length' => '64',
             ),
             'headline' => 
             array(
              'type' => 'string',
              'length' => '256',
             ),
             'subline' => 
             array(
              'type' => 'string',
              'length' => '256',
             ),
             'active' => 
             array(
              'type' => 'boolean',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('admin__model__category_featured_on_homepage');
    }
}