<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version174 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('admin__model__product_description_accordion', array(
             'id' => 
             array(
              'primary' => '1',
              'type' => 'integer',
              'autoincrement' => '1',
              'length' => '8',
             ),
             'product_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'language_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'headline' => 
             array(
              'type' => 'string',
              'length' => '256',
             ),
             'content' => 
             array(
              'type' => 'string',
              'length' => '',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('admin__model__product_description_accordion');
    }
}