<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version170 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('admin__model__shipping', 'file_id', 'integer', '8', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('admin__model__shipping', 'file_id');
    }
}