<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version175 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('admin__model__product_description_accordion', 'apai_13', array(
             'name' => 'apai_13',
             'local' => 'product_id',
             'foreign' => 'id',
             'foreignTable' => 'admin__model__product',
             ));
        $this->createForeignKey('admin__model__product_description_accordion', 'alci_4', array(
             'name' => 'alci_4',
             'local' => 'language_id',
             'foreign' => 'id',
             'foreignTable' => 'common__model__language',
             ));
        $this->addIndex('admin__model__product_description_accordion', 'admin__model__product_description_accordion_product_id', array(
             'fields' => 
             array(
              0 => 'product_id',
             ),
             ));
        $this->addIndex('admin__model__product_description_accordion', 'admin__model__product_description_accordion_language_id', array(
             'fields' => 
             array(
              0 => 'language_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('admin__model__product_description_accordion', 'apai_13');
        $this->dropForeignKey('admin__model__product_description_accordion', 'alci_4');
        $this->removeIndex('admin__model__product_description_accordion', 'admin__model__product_description_accordion_product_id', array(
             'fields' => 
             array(
              0 => 'product_id',
             ),
             ));
        $this->removeIndex('admin__model__product_description_accordion', 'admin__model__product_description_accordion_language_id', array(
             'fields' => 
             array(
              0 => 'language_id',
             ),
             ));
    }
}