<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version179 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropForeignKey('admin__model__order', 'aaai999');
        $this->removeColumn('admin__model__order', 'admin_model_zasilkovna_id');
    }

    public function down()
    {
        $this->createForeignKey('admin__model__order', 'aaai', array(
             'name' => 'aaai',
             'local' => 'admin_model_zasilkovna_id',
             'foreign' => 'id',
             'foreignTable' => 'admin__model__zasilkovna',
             ));
    }
}