<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version178 extends Doctrine_Migration_Base
{
    public function up()
    {

    }

    public function down()
    {
        $this->addColumn('admin__model__order', 'admin_model_zasilkovna_id', 'integer', '8', array(
             ));
    }
}