<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version181 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('admin__model__order', 'admin__model__order_zasilkovna_id_admin__model__zasilkovna_id', array(
             'name' => 'admin__model__order_zasilkovna_id_admin__model__zasilkovna_id',
             'local' => 'zasilkovna_id',
             'foreign' => 'id',
             'foreignTable' => 'admin__model__zasilkovna',
             ));
        $this->addIndex('admin__model__order', 'admin__model__order_zasilkovna_id', array(
             'fields' => 
             array(
              0 => 'zasilkovna_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('admin__model__order', 'admin__model__order_zasilkovna_id_admin__model__zasilkovna_id');
        $this->removeIndex('admin__model__order', 'admin__model__order_zasilkovna_id', array(
             'fields' => 
             array(
              0 => 'zasilkovna_id',
             ),
             ));
    }
}