<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version185 extends Doctrine_Migration_Base
{
    public function up()
    {

    }

    public function down()
    {
        $this->addColumn('admin__model__news_category', 'category_id', 'integer', '8', array(
             ));
    }
}