<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version190 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('admin__model__custom_link_featured_on_homepage', 'afci', array(
             'name' => 'afci',
             'local' => 'file_id',
             'foreign' => 'id',
             'foreignTable' => 'common__model__file',
             ));
        $this->addIndex('admin__model__custom_link_featured_on_homepage', 'admin__model__custom_link_featured_on_homepage_file_id', array(
             'fields' => 
             array(
              0 => 'file_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('admin__model__custom_link_featured_on_homepage', 'afci');
        $this->removeIndex('admin__model__custom_link_featured_on_homepage', 'admin__model__custom_link_featured_on_homepage_file_id', array(
             'fields' => 
             array(
              0 => 'file_id',
             ),
             ));
    }
}