<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version197 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('admin__model__p_p_l', 'pickupplace_id', 'integer', '8', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('admin__model__p_p_l', 'pickupplace_id');
    }
}