<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version191 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('admin__model__p_p_l', array(
             'id' => 
             array(
              'primary' => '1',
              'type' => 'integer',
              'autoincrement' => '1',
              'length' => '8',
             ),
             'pickupplacename' => 
             array(
              'type' => 'string',
              'length' => '',
             ),
             'pickupplaceaddress' => 
             array(
              'type' => 'string',
              'length' => '',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'utf8',
             ));
        $this->addColumn('admin__model__order', 'admin_model_ppl_id', 'integer', '8', array(
             ));
    }

    public function down()
    {
        $this->dropTable('admin__model__p_p_l');
        $this->removeColumn('admin__model__order', 'admin_model_ppl_id');
    }
}