<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version196 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('admin__model__order', 'admin__model__order_ppl_id_admin__model__p_p_l_id', array(
             'name' => 'admin__model__order_ppl_id_admin__model__p_p_l_id',
             'local' => 'ppl_id',
             'foreign' => 'id',
             'foreignTable' => 'admin__model__p_p_l',
             ));
        $this->addIndex('admin__model__order', 'admin__model__order_ppl_id', array(
             'fields' => 
             array(
              0 => 'ppl_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('admin__model__order', 'admin__model__order_ppl_id_admin__model__p_p_l_id');
        $this->removeIndex('admin__model__order', 'admin__model__order_ppl_id', array(
             'fields' => 
             array(
              0 => 'ppl_id',
             ),
             ));
    }
}