<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version210 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('common__model__settings', 'instagramurl', 'string', '128', array(
             ));
        $this->addColumn('common__model__settings', 'instagramname', 'string', '128', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('common__model__settings', 'instagramurl');
        $this->removeColumn('common__model__settings', 'instagramname');
    }
}