<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version211 extends Doctrine_Migration_Base
{
    public function up()
    {
        //$this->removeColumn('user__model__user', 'assemblycenter');
    }

    public function down()
    {
        $this->addColumn('user__model__user', 'assemblycenter', 'boolean', '25', array(
             ));
    }
}