<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version215 extends Doctrine_Migration_Base
{
    public function up()
    {
        //$this->removeColumn('admin__model__cart', 'usercredittransaction_id');
    }

    public function down()
    {
        $this->addColumn('admin__model__cart', 'usercredittransaction_id', 'integer', '8', array(
             ));
    }
}