<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version216 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropTable('admin__model__car_brand_discount');
    }

    public function down()
    {
        $this->createTable('admin__model__car_brand_discount', array(
             'id' => 
             array(
              'primary' => '1',
              'type' => 'integer',
              'autoincrement' => '1',
              'length' => '8',
             ),
             'carbrand_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'eshop_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'usergroup_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'discount' => 
             array(
              'type' => 'float',
              'length' => '',
             ),
             'validfrom' => 
             array(
              'type' => 'date',
              'length' => '25',
             ),
             'validto' => 
             array(
              'type' => 'date',
              'length' => '25',
             ),
             'active' => 
             array(
              'type' => 'boolean',
              'length' => '25',
             ),
             ), array(
             'type' => '',
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => '',
             'charset' => 'utf8',
             ));
    }
}