<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version217 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropForeignKey('admin__model__car_model', 'admin__model__car_model_carbrand_id_admin__model__car_brand_id');
        $this->dropTable('admin__model__car_brand');
    }

    public function down()
    {
        $this->createTable('admin__model__car_brand', array(
             'id' => 
             array(
              'primary' => '1',
              'type' => 'integer',
              'autoincrement' => '1',
              'length' => '8',
             ),
             'name' => 
             array(
              'type' => 'string',
              'length' => '64',
             ),
             'api_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'slug' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             ), array(
             'type' => '',
             'indexes' => 
             array(
              'admin__model__car_brand_sluggable' => 
              array(
              'fields' => 
              array(
               0 => 'slug',
              ),
              'type' => 'unique',
              ),
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => '',
             'charset' => 'utf8',
             ));
    }
}