<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version218 extends Doctrine_Migration_Base
{
    public function up()
    {

    }

    public function down()
    {
        $this->createForeignKey('admin__model__car_model', 'admin__model__car_model_carbrand_id_admin__model__car_brand_id', array(
             'name' => 'admin__model__car_model_carbrand_id_admin__model__car_brand_id',
             'local' => 'carbrand_id',
             'foreign' => 'id',
             'foreignTable' => 'admin__model__car_brand',
             ));
    }
}