<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version242 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('admin__model__product', 'isavailable', 'boolean', '25', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('admin__model__product', 'isavailable');
    }
}