<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version240 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('admin__model__product_attachment', array(
             'id' => 
             array(
              'primary' => '1',
              'type' => 'integer',
              'autoincrement' => '1',
              'length' => '8',
             ),
             'product_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'file_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'urlpath' => 
             array(
              'type' => 'string',
              'length' => '',
             ),
             'hash' => 
             array(
              'type' => 'string',
              'length' => '64',
             ),
             'alt' => 
             array(
              'type' => 'string',
              'length' => '256',
             ),
             'datetimecreated' => 
             array(
              'type' => 'timestamp',
              'length' => '25',
             ),
             'datetimeupdated' => 
             array(
              'type' => 'timestamp',
              'length' => '25',
             ),
             'attachmenttype' => 
             array(
              'type' => 'string',
              'length' => '64',
             ),
             'datetimelastsynchronized' => 
             array(
              'type' => 'timestamp',
              'length' => '25',
             ),
             'attachmentdata' => 
             array(
              'type' => 'blob',
              'length' => '',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'utf8',
             ));
        $this->addColumn('admin__model__product_eshop', 'quantitymin', 'integer', '8', array(
             ));
        $this->addColumn('admin__model__product_eshop', 'quantitymax', 'integer', '8', array(
             ));
    }

    public function down()
    {
        $this->dropTable('admin__model__product_attachment');
        $this->removeColumn('admin__model__product_eshop', 'quantitymin');
        $this->removeColumn('admin__model__product_eshop', 'quantitymax');
    }
}