<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version237 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('admin__model__product_meta', 'admin__model__product_meta_product_id_admin__model__product_id', array(
             'name' => 'admin__model__product_meta_product_id_admin__model__product_id',
             'local' => 'product_id',
             'foreign' => 'id',
             'foreignTable' => 'admin__model__product',
             ));
        $this->addIndex('admin__model__product_meta', 'admin__model__product_meta_product_id', array(
             'fields' => 
             array(
              0 => 'product_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('admin__model__product_meta', 'admin__model__product_meta_product_id_admin__model__product_id');
        $this->removeIndex('admin__model__product_meta', 'admin__model__product_meta_product_id', array(
             'fields' => 
             array(
              0 => 'product_id',
             ),
             ));
    }
}