<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version244 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('admin__model__category_attachment', array(
             'id' => 
             array(
              'primary' => '1',
              'type' => 'integer',
              'autoincrement' => '1',
              'length' => '8',
             ),
             'category_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'urlpath' => 
             array(
              'type' => 'string',
              'length' => '',
             ),
             'hash' => 
             array(
              'type' => 'string',
              'length' => '64',
             ),
             'alt' => 
             array(
              'type' => 'string',
              'length' => '256',
             ),
             'datetimecreated' => 
             array(
              'type' => 'timestamp',
              'length' => '25',
             ),
             'datetimeupdated' => 
             array(
              'type' => 'timestamp',
              'length' => '25',
             ),
             'attachmenttype' => 
             array(
              'type' => 'string',
              'length' => '64',
             ),
             'datetimelastsynchronized' => 
             array(
              'type' => 'timestamp',
              'length' => '25',
             ),
             'attachmentdata' => 
             array(
              'type' => 'blob',
              'length' => '',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'utf8',
             ));
        $this->createTable('admin__model__category_meta', array(
             'id' => 
             array(
              'primary' => '1',
              'type' => 'integer',
              'autoincrement' => '1',
              'length' => '8',
             ),
             'category_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'code' => 
             array(
              'type' => 'string',
              'length' => '64',
             ),
             'value' => 
             array(
              'type' => 'string',
              'length' => '32',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'utf8',
             ));
        $this->addColumn('admin__model__category', 'isavailable', 'boolean', '25', array(
             ));
        $this->addColumn('admin__model__category_lang', 'note', 'string', '', array(
             ));
    }

    public function down()
    {
        $this->dropTable('admin__model__category_attachment');
        $this->dropTable('admin__model__category_meta');
        $this->removeColumn('admin__model__category', 'isavailable');
        $this->removeColumn('admin__model__category_lang', 'note');
    }
}