<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version247 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('admin__model__category_attachment', 'admin__model__category_attachment_file_id_common__model__file_id', array(
             'name' => 'admin__model__category_attachment_file_id_common__model__file_id',
             'local' => 'file_id',
             'foreign' => 'id',
             'foreignTable' => 'common__model__file',
             ));
        $this->addIndex('admin__model__category_attachment', 'admin__model__category_attachment_file_id', array(
             'fields' => 
             array(
              0 => 'file_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('admin__model__category_attachment', 'admin__model__category_attachment_file_id_common__model__file_id');
        $this->removeIndex('admin__model__category_attachment', 'admin__model__category_attachment_file_id', array(
             'fields' => 
             array(
              0 => 'file_id',
             ),
             ));
    }
}