<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version251 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('common__model__settings', 'productionmode', 'boolean', '25', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('common__model__settings', 'productionmode');
    }
}