<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version252 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('common__model__cron', array(
             'id' => 
             array(
              'primary' => '1',
              'type' => 'integer',
              'autoincrement' => '1',
              'length' => '8',
             ),
             'name' => 
             array(
              'type' => 'string',
              'length' => '256',
             ),
             'active' => 
             array(
              'type' => 'boolean',
              'length' => '25',
             ),
             'cronexpression' => 
             array(
              'type' => 'string',
              'length' => '128',
             ),
             'minute' => 
             array(
              'type' => 'string',
              'length' => '16',
             ),
             'hour' => 
             array(
              'type' => 'string',
              'length' => '16',
             ),
             'day' => 
             array(
              'type' => 'string',
              'length' => '16',
             ),
             'month' => 
             array(
              'type' => 'string',
              'length' => '16',
             ),
             'week' => 
             array(
              'type' => 'string',
              'length' => '16',
             ),
             'script' => 
             array(
              'type' => 'string',
              'length' => '64',
             ),
             'note' => 
             array(
              'type' => 'string',
              'length' => '1024',
             ),
             'nextrun' => 
             array(
              'type' => 'timestamp',
              'length' => '25',
             ),
             'lastrun' => 
             array(
              'type' => 'timestamp',
              'length' => '25',
             ),
             'lastfinish' => 
             array(
              'type' => 'timestamp',
              'length' => '25',
             ),
             'laststatus' => 
             array(
              'type' => 'string',
              'length' => '64',
             ),
             'datecreated' => 
             array(
              'type' => 'date',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'utf8',
             ));
        $this->createTable('common__model__cron_log', array(
             'id' => 
             array(
              'primary' => '1',
              'type' => 'integer',
              'autoincrement' => '1',
              'length' => '8',
             ),
             'cron_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'datetimestart' => 
             array(
              'type' => 'timestamp',
              'length' => '25',
             ),
             'datetimestop' => 
             array(
              'type' => 'timestamp',
              'length' => '25',
             ),
             'status' => 
             array(
              'type' => 'string',
              'length' => '32',
             ),
             'message' => 
             array(
              'type' => 'string',
              'length' => '',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'utf8',
             ));
        $this->createTable('common__model__cron_user', array(
             'id' => 
             array(
              'primary' => '1',
              'type' => 'integer',
              'autoincrement' => '1',
              'length' => '8',
             ),
             'cron_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'user_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('common__model__cron');
        $this->dropTable('common__model__cron_log');
        $this->dropTable('common__model__cron_user');
    }
}