<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version254 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('admin__model__order', 'datetimeupdated', 'timestamp', '25', array(
             ));
        $this->addColumn('admin__model__order', 'sync', 'boolean', '25', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('admin__model__order', 'datetimeupdated');
        $this->removeColumn('admin__model__order', 'sync');
    }
}