<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version256 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('user__model__user_meta', 'user__model__user_meta_user_id_user__model__user_id', array(
             'name' => 'user__model__user_meta_user_id_user__model__user_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'user__model__user',
             ));
        $this->addIndex('user__model__user_meta', 'user__model__user_meta_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('user__model__user_meta', 'user__model__user_meta_user_id_user__model__user_id');
        $this->removeIndex('user__model__user_meta', 'user__model__user_meta_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
    }
}