<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version259 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('admin__model__payment', 'externalid', 'integer', '8', array(
             ));
        $this->addColumn('admin__model__payment', 'code', 'string', '128', array(
             ));
        $this->addColumn('admin__model__shipping', 'externalid', 'integer', '8', array(
             ));
        $this->addColumn('admin__model__shipping', 'code', 'string', '128', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('admin__model__payment', 'externalid');
        $this->removeColumn('admin__model__payment', 'code');
        $this->removeColumn('admin__model__shipping', 'externalid');
        $this->removeColumn('admin__model__shipping', 'code');
    }
}