<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version260 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('admin__model__product_eshop', 'pricea', 'decimal', '18', array(
             ));
        $this->addColumn('admin__model__product_eshop', 'priceb', 'decimal', '18', array(
             ));
        $this->addColumn('admin__model__product_eshop', 'pricec', 'decimal', '18', array(
             ));
        $this->addColumn('admin__model__product_eshop', 'priced', 'decimal', '18', array(
             ));
        $this->addColumn('admin__model__product_eshop', 'actionprice', 'date', '25', array(
             ));
        $this->addColumn('admin__model__product_eshop', 'quantitya', 'integer', '8', array(
             ));
        $this->addColumn('admin__model__product_eshop', 'quantityb', 'integer', '8', array(
             ));
        $this->addColumn('admin__model__product_eshop', 'quantityc', 'integer', '8', array(
             ));
        $this->addColumn('admin__model__product_eshop', 'quantityd', 'integer', '8', array(
             ));
        $this->addColumn('admin__model__product_eshop', 'quantityactionprice', 'decimal', '18', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('admin__model__product_eshop', 'pricea');
        $this->removeColumn('admin__model__product_eshop', 'priceb');
        $this->removeColumn('admin__model__product_eshop', 'pricec');
        $this->removeColumn('admin__model__product_eshop', 'priced');
        $this->removeColumn('admin__model__product_eshop', 'actionprice');
        $this->removeColumn('admin__model__product_eshop', 'quantitya');
        $this->removeColumn('admin__model__product_eshop', 'quantityb');
        $this->removeColumn('admin__model__product_eshop', 'quantityc');
        $this->removeColumn('admin__model__product_eshop', 'quantityd');
        $this->removeColumn('admin__model__product_eshop', 'quantityactionprice');
    }
}