<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version257 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('admin__model__shipping_price', array(
             'id' => 
             array(
              'primary' => '1',
              'type' => 'integer',
              'autoincrement' => '1',
              'length' => '8',
             ),
             'shipping_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'maxweight' => 
             array(
              'type' => 'float',
              'length' => '',
             ),
             'maxwidth' => 
             array(
              'type' => 'float',
              'length' => '',
             ),
             'maxdepth' => 
             array(
              'type' => 'float',
              'length' => '',
             ),
             'maxheight' => 
             array(
              'type' => 'float',
              'length' => '',
             ),
             'pricewithoutvat' => 
             array(
              'type' => 'decimal',
              'length' => '18',
             ),
             'note' => 
             array(
              'type' => 'string',
              'length' => '',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('admin__model__shipping_price');
    }
}