<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version267 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('admin__model__balikovna', 'pickupplace_id', 'string', '64', array(
             ));
    }

    public function down()
    {

    }
}