<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version268 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('admin__model__product_watch_dog', array(
             'id' => 
             array(
              'primary' => '1',
              'type' => 'integer',
              'autoincrement' => '1',
              'length' => '8',
             ),
             'product_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'user_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'datetimecreated' => 
             array(
              'type' => 'timestamp',
              'length' => '25',
             ),
             'reported' => 
             array(
              'type' => 'boolean',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('admin__model__product_watch_dog');
    }
}