<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version261 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('admin__model__csob_payment', array(
             'id' => 
             array(
              'primary' => '1',
              'type' => 'integer',
              'autoincrement' => '1',
              'length' => '8',
             ),
             'order_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'date' => 
             array(
              'type' => 'date',
              'length' => '25',
             ),
             'time' => 
             array(
              'type' => 'time',
              'length' => '25',
             ),
             'csobid' => 
             array(
              'type' => 'string',
              'length' => '256',
             ),
             'csoburl' => 
             array(
              'type' => 'string',
              'length' => '',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'utf8',
             ));
        $this->createTable('admin__model__csob_payment_state', array(
             'id' => 
             array(
              'primary' => '1',
              'type' => 'integer',
              'autoincrement' => '1',
              'length' => '8',
             ),
             'csobpayment_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'orderstatetype_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'date' => 
             array(
              'type' => 'date',
              'length' => '25',
             ),
             'time' => 
             array(
              'type' => 'time',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('admin__model__csob_payment');
        $this->dropTable('admin__model__csob_payment_state');
    }
}