<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version275 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('admin__model__category_slug_history', 'acai_10', array(
             'name' => 'acai_10',
             'local' => 'category_id',
             'foreign' => 'id',
             'foreignTable' => 'admin__model__category',
             ));
        $this->createForeignKey('admin__model__product_slug_history', 'apai_16', array(
             'name' => 'apai_16',
             'local' => 'product_id',
             'foreign' => 'id',
             'foreignTable' => 'admin__model__product',
             ));
        $this->addIndex('admin__model__category_slug_history', 'admin__model__category_slug_history_category_id', array(
             'fields' => 
             array(
              0 => 'category_id',
             ),
             ));
        $this->addIndex('admin__model__product_slug_history', 'admin__model__product_slug_history_product_id', array(
             'fields' => 
             array(
              0 => 'product_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('admin__model__category_slug_history', 'acai_10');
        $this->dropForeignKey('admin__model__product_slug_history', 'apai_16');
        $this->removeIndex('admin__model__category_slug_history', 'admin__model__category_slug_history_category_id', array(
             'fields' => 
             array(
              0 => 'category_id',
             ),
             ));
        $this->removeIndex('admin__model__product_slug_history', 'admin__model__product_slug_history_product_id', array(
             'fields' => 
             array(
              0 => 'product_id',
             ),
             ));
    }
}