<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version270 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('admin__model__cart_log', array(
             'id' => 
             array(
              'primary' => '1',
              'type' => 'integer',
              'autoincrement' => '1',
              'length' => '8',
             ),
             'product_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'quantity' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'date' => 
             array(
              'type' => 'date',
              'length' => '25',
             ),
             'time' => 
             array(
              'type' => 'time',
              'length' => '25',
             ),
             'ipaddress' => 
             array(
              'type' => 'string',
              'length' => '64',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('admin__model__cart_log');
    }
}