<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version266 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('admin__model__order', 'admin__model__order_balikovna_id_admin__model__balikovna_id', array(
             'name' => 'admin__model__order_balikovna_id_admin__model__balikovna_id',
             'local' => 'balikovna_id',
             'foreign' => 'id',
             'foreignTable' => 'admin__model__balikovna',
             ));
        $this->addIndex('admin__model__order', 'admin__model__order_balikovna_id', array(
             'fields' => 
             array(
              0 => 'balikovna_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('admin__model__order', 'admin__model__order_balikovna_id_admin__model__balikovna_id');
        $this->removeIndex('admin__model__order', 'admin__model__order_balikovna_id', array(
             'fields' => 
             array(
              0 => 'balikovna_id',
             ),
             ));
    }
}