<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version280 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('admin__model__product_related', 'linktype', 'string', '64', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('admin__model__product_related', 'linktype');
    }
}