<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version291 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('admin__model__product_eshop', 'validfrom', 'timestamp', '25', array(
             ));
        $this->addColumn('admin__model__product_eshop', 'validto', 'timestamp', '25', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('admin__model__product_eshop', 'validfrom');
        $this->removeColumn('admin__model__product_eshop', 'validto');
    }
}