<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version290 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('admin__model__complaint', 'deliverycity', 'string', '128', array(
             ));
    }

    public function down()
    {

    }
}