<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version288 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('admin__model__address', 'admin__model__address_user_id_user__model__user_id', array(
             'name' => 'admin__model__address_user_id_user__model__user_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'user__model__user',
             ));
        $this->addIndex('admin__model__address', 'admin__model__address_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('admin__model__address', 'admin__model__address_user_id_user__model__user_id');
        $this->removeIndex('admin__model__address', 'admin__model__address_user_id', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             ));
    }
}