<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version292 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('user__model__old_user', array(
             'id' => 
             array(
              'primary' => '1',
              'type' => 'integer',
              'autoincrement' => '1',
              'length' => '8',
             ),
             'code' => 
             array(
              'type' => 'string',
              'length' => '64',
             ),
             'isadmin' => 
             array(
              'type' => 'blob',
              'length' => '',
             ),
             'loginname' => 
             array(
              'type' => 'string',
              'length' => '256',
             ),
             'password' => 
             array(
              'type' => 'string',
              'length' => '2056',
             ),
             'transfered' => 
             array(
              'type' => 'boolean',
              'length' => '25',
             ),
             'contactperson' => 
             array(
              'type' => 'string',
              'length' => '128',
             ),
             'contactphone' => 
             array(
              'type' => 'string',
              'length' => '64',
             ),
             'contactemail' => 
             array(
              'type' => 'string',
              'length' => '256',
             ),
             'companyname' => 
             array(
              'type' => 'string',
              'length' => '256',
             ),
             'companystreet' => 
             array(
              'type' => 'string',
              'length' => '256',
             ),
             'companycity' => 
             array(
              'type' => 'string',
              'length' => '256',
             ),
             'companyzipcode' => 
             array(
              'type' => 'string',
              'length' => '16',
             ),
             'companycountry' => 
             array(
              'type' => 'string',
              'length' => '64',
             ),
             'companyid' => 
             array(
              'type' => 'string',
              'length' => '32',
             ),
             'companyvatid' => 
             array(
              'type' => 'string',
              'length' => '32',
             ),
             'deliveryname' => 
             array(
              'type' => 'string',
              'length' => '256',
             ),
             'deliverystreet' => 
             array(
              'type' => 'string',
              'length' => '256',
             ),
             'deliverycity' => 
             array(
              'type' => 'string',
              'length' => '128',
             ),
             'deliveryzipcode' => 
             array(
              'type' => 'string',
              'length' => '16',
             ),
             'deliverycountry' => 
             array(
              'type' => 'string',
              'length' => '64',
             ),
             'currency' => 
             array(
              'type' => 'string',
              'length' => '64',
             ),
             'lang' => 
             array(
              'type' => 'string',
              'length' => '16',
             ),
             'paymentavailability' => 
             array(
              'type' => 'string',
              'length' => '32',
             ),
             'pricetype' => 
             array(
              'type' => 'string',
              'length' => '16',
             ),
             'discount' => 
             array(
              'type' => 'decimal',
              'length' => '18',
             ),
             'state' => 
             array(
              'type' => 'boolean',
              'length' => '25',
             ),
             'newsletter' => 
             array(
              'type' => 'boolean',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('user__model__old_user');
    }
}