<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version295 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('user__model__user', 'newsletter', 'boolean', '25', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('user__model__user', 'newsletter');
    }
}