<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version296 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('admin__model__day', array(
             'id' => 
             array(
              'primary' => '1',
              'type' => 'integer',
              'autoincrement' => '1',
              'length' => '8',
             ),
             'date' => 
             array(
              'type' => 'date',
              'length' => '25',
             ),
             'name' => 
             array(
              'type' => 'string',
              'length' => '128',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'utf8',
             ));
        $this->createTable('admin__model__meal', array(
             'id' => 
             array(
              'primary' => '1',
              'type' => 'integer',
              'autoincrement' => '1',
              'length' => '8',
             ),
             'day_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'user_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'mealtype' => 
             array(
              'type' => 'string',
              'length' => '128',
             ),
             'offcode' => 
             array(
              'type' => 'string',
              'length' => '64',
             ),
             'quantity' => 
             array(
              'type' => 'decimal',
              'length' => '18',
             ),
             'datecreated' => 
             array(
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('admin__model__day');
        $this->dropTable('admin__model__meal');
    }
}