<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version303 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('admin__model__recomendation', array(
             'id' => 
             array(
              'primary' => '1',
              'type' => 'integer',
              'autoincrement' => '1',
              'length' => '8',
             ),
             'name' => 
             array(
              'type' => 'string',
              'length' => '128',
             ),
             'type' => 
             array(
              'type' => 'string',
              'length' => '64',
             ),
             'description' => 
             array(
              'type' => 'string',
              'length' => '',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'utf8',
             ));
        $this->addColumn('admin__model__condition', 'type', 'string', '64', array(
             ));
        $this->addColumn('admin__model__condition', 'description', 'string', '', array(
             ));
        $this->addColumn('admin__model__condition', 'ispositive', 'boolean', '25', array(
             ));
    }

    public function down()
    {
        $this->dropTable('admin__model__recomendation');
        $this->removeColumn('admin__model__condition', 'type');
        $this->removeColumn('admin__model__condition', 'description');
        $this->removeColumn('admin__model__condition', 'ispositive');
    }
}