<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version304 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('admin__model__day_sleep', 'starttime', 'time', '25', array(
             ));
        $this->addColumn('admin__model__day_sleep', 'finishtime', 'time', '25', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('admin__model__day_sleep', 'starttime');
        $this->removeColumn('admin__model__day_sleep', 'finishtime');
    }
}