<?php

namespace common\logic\PPL;

use admin\logic\Order\CreatePdf;
use Admin_Model_Order as OrderModel;
use Admin_Model_Vat;
use common\logic\Eshop\Eshop;
use common\logic\Helper\QrPayment;
use Admin_Model_Payment as Payment;

use common\logic\Latte\LatteEngine;
use Exception;
use Mpdf\Mpdf;

class PackageListPdf extends CreatePdf
{
    const FILE_NAME = 'package-list';
    private $bankAccount;
    private $bankIban;
    const BANK_BIC = "AGBACZPP";
    const BANK_KS = "0308";
    const DUE_DAYS = '14';
    private $order;
    private $params;
    private $counter = 0;

    /**
     * @throws \Mpdf\MpdfException
     * @throws \PHPMailer\PHPMailer\Exception
     */
    public function __construct(array $orderIDs, ?string $note = null)
    {
        $orders = OrderModel::getOrderDetailsByIDs($orderIDs);
        $latte = LatteEngine::getInstance();
        $summary = $this->getSummary($orders);
        $content = $latte->renderToString(__DIR__ . '/templates/packageList.latte',
            [
                'orders' => $orders,
                'note' => $note,
                'eshop' => Eshop::getInstance(),
                'summary' => $summary
            ]);
        $mpdf = new Mpdf(['tempDir' => 'files', 'default_font' => 'poppins', 'format' => 'A4-L']);
        $mpdf->SetTopMargin(22);
        $mpdf->SetHTMLHeader('<img style="float:left; width: 25%" src="' . APPLICATION_PATH . '/../www/img/front/ppl_logo.png"/>');
        $mpdf->SetHTMLFooter('<div style="float:left">Stránka {PAGENO} / {nb}</div><div style="display: inline-block;text-align: right; "><small><strong>Vygenerováno: </strong>' . date('d.m.Y H:i:s') . '</div>');
        $mpdf->WriteHTML($content);

        $fileName = 'Seznam všech balíků PPL-' . date("Y_m_d");
        $extension = 'pdf';
        $fullFileName = $fileName . '.' . $extension;

        $mpdf->Output($fullFileName, 'I');

    }

    function AddPage($orientation = '', $condition = '', $resetpagenum = '', $pagenumstyle = '', $suppress = '', $mgl = '', $mgr = '', $mgt = '', $mgb = '', $mgh = '', $mgf = '', $ohname = '', $ehname = '', $ofname = '', $efname = '', $ohvalue = 0, $ehvalue = 0, $ofvalue = 0, $efvalue = 0, $pagesel = '', $newformat = '')
    {
        $this->counter = 0;
        return parent::AddPage($orientation, $condition, $resetpagenum, $pagenumstyle, $suppress, $mgl, $mgr, $mgt, $mgb, $mgh, $mgf, $ohname, $ehname, $ofname, $efname, $ohvalue, $ehvalue, $ofvalue, $efvalue, $pagesel, $newformat); // TODO: Change the autogenerated stub
    }

    public function Footer()
    {
        parent::Footer();
    }

    private function calculateVat()
    {
        $vatData = [];
        $data = [];
        foreach ($this->order->orderItems as &$item) {
            $data['VAT_Ratio'] = Admin_Model_Vat::getVatRatioByID($item['product']['productEshops'][0]['Vat_ID']);
            if (!isset($vatData[$data['VAT_Ratio']])) {
                $vatData[$data['VAT_Ratio']]['PriceTotalWithoutVat'] = floatval($item['PriceWithoutVat'] * $item['Quantity']);
                $vatData[$data['VAT_Ratio']]['PriceTotalWithVat'] = floatval($item['PriceWithVat'] * $item['Quantity']);
            } else {
                $vatData[$data['VAT_Ratio']]['PriceTotalWithoutVat'] += floatval($item['PriceWithoutVat'] * $item['Quantity']);
                $vatData[$data['VAT_Ratio']]['PriceTotalWithVat'] += floatval($item['PriceWithVat'] * $item['Quantity']);
            }

        }

        $shippingVatRatio = Admin_Model_Vat::getVatRatioByID($this->order->shipping->Vat_ID);

        if ($shippingVatRatio) {
            if (!isset($vatData[$shippingVatRatio])) {
                $vatData[$shippingVatRatio]['PriceTotalWithoutVat'] = floatval($this->order->PriceShippingWithoutVat);
                $vatData[$shippingVatRatio]['PriceTotalWithVat'] = floatval($this->order->PriceShippingWithVat);
            } else {
                $vatData[$shippingVatRatio]['PriceTotalWithoutVat'] += floatval($this->order->PriceShippingWithoutVat);
                $vatData[$shippingVatRatio]['PriceTotalWithVat'] += floatval($this->order->PriceShippingWithVat);
            }
        }

        $paymentVatRatio = Admin_Model_Vat::getVatRatioByID($this->order->payment->Vat_ID);

        if ($paymentVatRatio) {
            if (!isset($vatData[$paymentVatRatio])) {
                $vatData[$paymentVatRatio]['PriceTotalWithoutVat'] = floatval($this->order->PricePaymentWithoutVat);
                $vatData[$paymentVatRatio]['PriceTotalWithVat'] = floatval($this->order->PricePaymentWithVat);
            } else {
                $vatData[$paymentVatRatio]['PriceTotalWithoutVat'] += floatval($this->order->PricePaymentWithoutVat);
                $vatData[$paymentVatRatio]['PriceTotalWithVat'] += floatval($this->order->PricePaymentWithVat);
            }
        }


        return $vatData;
    }

    /**
     * Vrací info pro dodavatele
     * @return array
     */
    private function getContractor(): array
    {
        $eshop = Eshop::getInstance();
        return [
            'infoType' => translate('Dodavatel', $this->order->language->Code),
            'fullName' => $eshop->getSettings('ProjectName'),
            'street' => $eshop->getSettings('AddressStreet'),
            'zip' => $eshop->getSettings('AddressZipCode'),
            'city' => $eshop->getSettings('AddressCity'),
            'country' => 'CZ',
            'ic' => $eshop->getSettings('RegistrationNumber'),
            'dic' => $eshop->getSettings('VATNumber'),
            'bankAccount' => [
                'BankAccount' => $this->bankAccount,
                'IBAN' => $this->bankIban,
                'BIC' => self::BANK_BIC,
//                'paymentType' => translate('Příkazem', $this->order->language->Code),
                'paymentType' => translate($this->order->payment->Name, $this->order->language->Code),
                'VS' => $this->order->OrderNumber,
                'KS' => self::BANK_KS,
            ]
        ];
    }

    /**
     * Vrací info pro odběratele
     * @return array|null
     * @throws Exception
     */
    private function getCurrency(): \Admin_Model_Currency
    {
        return \Admin_Model_Currency::getCurrencyByID($this->order->Currency_ID);
    }

    /**
     * Vrací info pro odběratele
     * @return array|null
     * @throws Exception
     */
    private function getCustomer(): ?array
    {
        $customer = null;
        if ($this->order->InvoiceAddress_ID) {
            $inv = $this->order->invoiceAddress;
            $customer = [
                'infoType' => translate('Odběratel'),
                'fullName' => !empty($inv->CompanyName) ? $inv->CompanyName : $inv->getFullName(),
                'street' => $inv->getFullStreet(),
                'zip' => $inv->ZipCode,
                'city' => $inv->City,
                'country' => $inv->Country_ID ? $inv->country->getLang($this->order->Language_ID)->Name : null,
                'ic' => $inv->IC,
                'dic' => $inv->DIC,
                'phone' => $inv->Phone,
                'orderInfo' => [
                    'VS' => $this->order->OrderNumber,
                    'KS' => self::BANK_KS,
                    'OrderNumber' => $this->order->OrderNumber,
                    'OrderDate' => $this->order->Date
                ]
            ];
        }

        return $customer;
    }

    public function Output($name = '', $dest = '')
    {
        if (empty($name)) {
            $name = "invoice-{$this->order->OrderNumber}.pdf";
        }
        return parent::Output($name, $dest);
    }

    private function isBankPayment(): bool
    {
        return $this->order->payment->Type === Payment::TYPE_BANK;
    }

    private function getSummary(int|array|\Doctrine_Collection_OnDemand|\Doctrine_Collection $orders): array
    {
        $totalCODSummaryCZ = 0;
        $totalCODSummarySK = 0;
        $totalPackages = count($orders);
        $totalCODPackages = 0;

        foreach ($orders as $order) {
            $deliveryAddress = !$order->deliveryAddress ? $order->invoiceAddress : $order->deliveryAddress;

            if ($order->payment->Type === 'cod') {
                $totalCODPackages++;
                if ($deliveryAddress->country->Code2 == 'CZ')
                    $totalCODSummaryCZ += floatval($order->PriceTotalWithVat);
                if ($deliveryAddress->country->Code2 == 'SK')
                    $totalCODSummarySK += floatval($order->PriceTotalWithVat);
            }
        }

        return [
            'TotalPackages' => $totalPackages,
            'TotalCODPackages' => $totalCODPackages,
            'TotalCODSummarySK' => $totalCODSummarySK,
            'TotalCODSummaryCZ' => $totalCODSummaryCZ,
        ];
    }
}